### ISSUE TITLE
[@loopback/sequelize] contains & match (extendedOperators) are not working

### ISSUE THREAD

**Issue by vaibhavkumar-sf** [loopbackio/loopback-next#10272]
### Describe the bug

![image](https://github.com/loopbackio/loopback-next/assets/30282624/cff4e4d2-77cf-4ba2-a691-9d04c28565b2)
![image](https://github.com/loopbackio/loopback-next/assets/30282624/40994984-1e91-40c6-8ceb-22bd9f34191d)
![image](https://github.com/loopbackio/loopback-next/assets/30282624/9c04ba00-8ca6-4e36-aff3-87cfc1d49641)
<img width="705" alt="image" src="https://github.com/loopbackio/loopback-next/assets/30282624/244fa022-89a4-4038-abe6-8e09fe25577f">

Also for ExtendedOperator (Match), 
**There is no equivalent operator for "match" in sequelize.** 

We're using it like : 
```
/localhost:4005/app-facade/tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters?encountersType=both&filter={"limit":50,"where":{"and":[],"fullName":{"match":"%jiya:*&%"}}}
```

25%22%7D%7D%7D&encountersType=both Completed in 27ms
[2023-12-22T08:50:39.993Z] error :: App_Log -> Request GET /tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters/count?filter=%7B%22where%22%3A%7B%22and%22%3A%5B%5D%2C%22fullName%22%3A%7B%22match%22%3A%22%25jiya%3A%2A%26%25%22%7D%7D%7D&encountersType=both errored out. Error :: {} Error: There is no equivalent operator for "match" in sequelize.
Request GET /tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters/count?filter=%7B%22where%22%3A%7B%22and%22%3A%5B%5D%2C%22fullName%22%3A%7B%22match%22%3A%22%25jiya%3A%2A%26%25%22%7D%7D%7D&encountersType=both failed with status code 500. Error: There is no equivalent operator for "match" in sequelize.

### Logs

![image](https://github.com/loopbackio/loopback-next/assets/30282624/2f6da4ef-fd31-4900-8a37-9840703aaa3d)

### Reproduction

the issue is obvious and the provided information is enough to understand the problem.

**Comment by samarpanB** [comment]
Its a feature not yet implemented in sequelize extension.
