### ISSUE TITLE
[EPIC] More Relations (post-GA)

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#1450]
- ~HasManyThrough - see #2264~ 
- HasAndBelongsToMany - see #2308
- Polymorphic - see #2487
- EmbedsOne 
- EmbedsMany
- ReferencesMany - see #2488

**Comment by haotangio** [comment]
Hi team,
Are `EmbedsOne`, `EmbedsMany`, `ReferencesMany` relations ready to be used yet? Those are blocking features as most systems using MongoDB will definitely need them.

**Comment by saurabhg22** [comment]
Hi guys,
Until these relations are not officially supported, can someone provide some workaround for it or how can we create our own relation definitions?
