### ISSUE TITLE
[Spike] Deploy LB4 applications to Google Cloud Platform

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#1467]
Find out what's needed to deploy LB4 applications to Google Cloud Platform and write a short document describing the steps.

See #1446 for more details and acceptance criteria.

**Comment by dhmlau** [comment]
Moving out of GA scope, keeping deploying to IBM Cloud as the first priority in the same epic.

**Comment by shadyanwar** [comment]
@bajtos 
I have been trying to deploy an LB4 app to GCP with no luck.

Using the standard or the flexible environment, I get this error in the logs:
`sh: 1: lb-tsc: not found`. In the standard env, this happens after successful deployment and is reflected in the logs when trying to access the app. In the flexible env, this prevents the deployment completion, giving "Application startup error".

It seems like the node modules are not being installed. I tried adding this to package.json: `"gcp-build": "npm install",` but the same failure happens. I also tried changing `"start": "node .",` to `"start": "npm install && node .",` but no effect.

I tried some of the suggestions from [this issue](https://github.com/strapi/strapi/issues/2146) but no avail.

I used nodejs10.

Any pointers are appreciated.

**Comment by ajaysheoran2323** [comment]
@shadyanwar  Were you able to solve this?? I am facing same issue.

**Comment by raymondfeng** [comment]
The dev dependency `@loopback/build` is needed to transpile TS into JS. For deployment, if you have run `npm run build` to create the application package, use `node .` instead `npm start` to start the application as ` npm start` triggers `npm run build` for development purposes. Or you can change `npm start` to run `node .` directly.

**Comment by lonewolfaka9** [comment]
you can deploy Dockerized application on google cloud run and it will work like charm
