### ISSUE TITLE
Support transaction for mysql orm

### ISSUE THREAD

**Issue by hosiduy** [loopbackio/loopback-next#1599]
## Feature proposal
Hi loopback team, 
I am working with mysql db and need to use transaction in my project. But I haven't found document about db transaction on https://loopback.io/doc/en/lb4/. 
Is this feature built on lb-next? Do you have schedule for building this feature in future?

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by raymondfeng** [comment]
The RDBMS local transaction support is planned for LB4. We need to define a `Transactional` mixin for repositories. There is no concrete schedule yet for the delivery.

**Comment by uribalb** [comment]
@raymondfeng  Is that feature going to support MongoDB [transactions](https://www.mongodb.com/transactions) ?

**Comment by Vhauryn** [comment]
So loopback 4 has no transactions yet... wow... is there a workaround?

**Comment by HassanAbdelzaher** [comment]
we have oracle database and transacting is very important 
we modify the DataSource and working properly 


this is the solution for oracle

import { juggler } from '@loopback/repository';
import { Transaction, Connector } from 'loopback-datasource-juggler';
import { EventEmitter } from 'events';
import { IConnection, IConnectionPool } from 'oracledb';
export class OraTransaction extends EventEmitter implements Transaction {
  connection: IConnection;
  connector?: Connector;
  pool?: IConnectionPool;
  constructor(_connection: IConnection, _connector?: Connector) {
    super();
    if (!_connection) {
      throw new Error("can not start transaction because connection is not defined");
    }
    if (!_connector) {
      throw new Error("can not start transaction because connector is not defined");
    }
    this.connection = _connection;
    this.connector = _connector;
  }
  async commit() {
    if (this.connection) {
      await this.connection.commit();
    }
  }
  async rollback() {
    if (this.connection) {
      await this.connection.rollback();
    }
  }
  async close() {
    if (this.connection) {
      await this.connection.close();
    }
  }
}
export class OraDataSource extends juggler.DataSource {
  constructor(
    name: string, protected config: any
  ) {
    super(name, config);
    this.on('error', function (ee) {
      console.log('data source error ' + ee);
    })//must be because there is a bug on datasource with async so must be handled"
  }
  //override of connect must be
  connect(callback: (err: any, result: any) => void) {
    let cl = callback || function (err: any) {
      console.log(err);
    }
    super.connect(cl);
  }
  //this for support transaction with oracle database and initial test pass
  beginTransaction(): Promise<OraTransaction> {
    return new Promise((resolve, reject) => {
      //first connecting to startup pool creation
      this.connect(async (err, rs) => {
        try {
          if (err)
            reject(err);
          let pool: IConnectionPool = (this.connector as any)['pool'];
          if (!pool) {
            throw new Error("can not start transaction because connector pool is not defined");
          }
          let connection = await pool.getConnection();
          let t = new OraTransaction(connection, this.connector);
          resolve(t);
        }
        catch (err) {
          reject(err);
        }
      })
    })
  }
}

**Comment by dhmlau** [comment]
Talked to @bajtos @raymondfeng, what we should do regarding transaction support:
- shorter term: explain to users how to open a transaction and pass the transaction token/handles around in options.
- longer term: have a spike on a more elegant solution.

**Comment by lalitmcb** [comment]
One way is to do how Spring does. Define a @Transactional decorator. Wrap it up with a Dynamic proxy. The proxy intercepts the call and puts the underlying method in the context of the transaction.

I am still not very deep with Node/Typescript so not sure if dynamic proxies are available. Would be happy if I can contribute in it in some way.

**Comment by hoangleanhtu** [comment]
@lalitmcb I created component https://www.npmjs.com/package/loopback4-spring that provides:

- @services
- @transactional()

**Comment by lalitmcb** [comment]
Thanks, @hoangleanhtu . We will try it out.

**Comment by gordancso** [comment]
> @lalitmcb I created component https://www.npmjs.com/package/loopback4-spring that provides:
> 
> * @services
> * @transactional()

Thanks @hoangleanhtu. I tried to implement the package and it works as expected.

Just another supplement to the example. If the method is custom, `options` should always be passed thru `DefaultCRUDRepositoty` methods.

**Comment by hoangleanhtu** [comment]
@gordancso Thank for your suggestion.

New [version](https://www.npmjs.com/package/loopback4-spring#transaction-on-mongodb-replica-set) supports MongoDB as well.

**Comment by kietphan** [comment]
@hoangleanhtu I was tried it with postgres, but It not worked yet

**Comment by hoangleanhtu** [comment]
Hi @kietphan,

Please use version 1.0.6, it supports Postgres.

**Comment by kietphan** [comment]
@hoangleanhtu thank you,  it works as expected.

**Comment by bajtos** [comment]
Cross-posting https://github.com/strongloop/loopback-next/issues/2614#issuecomment-498565714 by @gordancso:

> [loopback4-spring](https://www.npmjs.com/package/loopback4-spring) arising from [Issue #1599](https://github.com/strongloop/loopback-next/issues/1599) is a good example of using decorator style to perform transaction.

**Comment by Lipinalipi** [comment]
Is there any examples for transaction in loopback 4?

**Comment by achrinza** [comment]
@Lipinalipi See: https://loopback.io/doc/en/lb4/Using-database-transactions.html
