### ISSUE TITLE
[User Scenario - Messaging/Eventing API] Subscribe to Kafka event and write to database

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#1925]
## Description / Steps to reproduce / Feature proposal
I want to create a LoopBack 4 application that subscribes to Kafka events and then write it to a database (e.g. Cassandra).

This user scenario can be considered as the first step for the "Support Messaging/Event API" epic: https://github.com/strongloop/loopback-next/issues/1884.

### Additional Information
https://github.com/ibm-cloud-architecture/refarch-asset-analytics
https://github.com/ibm-cloud-architecture/refarch-asset-analytics/tree/master/asset-dashboard-bff

**Comment by raymondfeng** [comment]
The 1st version of the demo - https://github.com/strongloop/loopback4-example-kafka
