### ISSUE TITLE
Connecting to graph databases

### ISSUE THREAD

**Issue by koalabi** [loopbackio/loopback-next#2053]
## Description / Steps to reproduce / Feature proposal
I'd like to be able to use lb4 with a graph database. Currently my preferred target would be OrientDB but, even if it were Neo4j (which is probably more mainstream today), I have a hard time finding out where to start (after much googling and reading the loopback website). It would probably be more straightforward with lb3 but it is for a few greencase applications, so I'd very much prefer to use lb4.

My main question is: how could one use a graph database, knowing that 1-to-many relations are not the dominant case (rather many-to-many) and that the model is not relational.

Any hint from the loobpack core team will be appreciated.

Kind regards,
Alain

## Expected Behavior

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by koalabi** [comment]
Hi Miroslav,

Thanks for your question and my apologies for the late answer (too busy these days! :-( ).

I mainly target 2 types of applications: one is more of the modeling kind (enterprise architecture models, business process models, software dependencies, ITIL CMDB's), where relations are many and of very diverse nature, and the other one is more related to knowledge modeling/management/linked data ("à la RDF" ;-)).

Moreover, I have needs in the short term and in the medium term. In the short term, it's enough to be able to retrieve the immediate neighborhood of a given node (full or partial list of edges connected to the node with the nodes at the other end). In other words, I don't need nor plan to perform sophisticated queries on the database (such as "shortest path from - to"). Such queries will probably come later on (in the medium term) but they are today only a remote possibility.

I have had a quick look at the lb3 neo4j connector. (It's not OrientDB of course but Neo4j is fine too). It might fit the bill but can I use it "out of the box" with lb4 ?

Kind regards,
Alain

**Comment by koalabi** [comment]
Additional comment, maybe: I don't need the relations to be strongly typed: a string rendition indicating the nature of each edge would be a good start. I imagine the highly dynamic nature of edge types in graph databases would make a type-safer approach a maintenance nightmare and an almost impossible task.

**Comment by bajtos** [comment]
I opened a pull request in juggler to implement `dataSource.execute`, see https://github.com/strongloop/loopback-datasource-juggler/pull/1671

**Comment by bajtos** [comment]
A related question on StackOverflow: [How to execute arbitrary SQL query](https://stackoverflow.com/q/53338050/69868)

**Comment by franverona** [comment]
By mixin @bajtos previous answer and some code of my own, I've created a way to use raw queries on repositories.

**Repository Helper**

```
import { DataSource } from "loopback-datasource-juggler";

export default class RepositoryHelper {

  public readonly dataSource: DataSource;

  constructor(dataSource: DataSource) {
    this.dataSource = dataSource;
  }

  async query(sql: string, params?: any, options?: any): Promise<void> {
    return new Promise((resolve, reject) => {
      const connector = this.dataSource.connector!;
      connector.execute!(sql, params, options, (err: any, ...results: any) => {
        if (err) {
          return reject(err);
        }

        if (results.length === 0) {
          return resolve();
        }

        if (results.length === 1) {
          return resolve(results[0]);
        }

        resolve(results);
      });
    });
  }
}
```

**Some repository**

```
import { DefaultCrudRepository, repository } from '@loopback/repository';
import { SomeModel } from '../models';
import { DatabaseDataSource } from '../datasources';
import { inject, Getter } from '@loopback/core';
import RepositoryHelper from './helper.repository';

export class SomeRepository extends DefaultCrudRepository<
  SomeModel,
  typeof SomeModel.prototype.id
  > {

  helper: RepositoryHelper;

  constructor(
    @inject('datasources.db') dataSource: DatabaseDataSource
  ) {
    super(SomeModel, dataSource);

    this.helper = new RepositoryHelper(this.dataSource);
  }

  async query(sql: string, params?: any, options?: any): Promise<void> {
    return await this.helper.query(sql, params, options);
  }
}
```

Then you can use your repository as follows:

```
const query = await this.tokenRepository.query('SELECT * FROM users');
console.log(query)
```

For example, inside an API call:

```
import { Filter, repository, Where } from '@loopback/repository';
import { param, get, getFilterSchemaFor } from '@loopback/rest';
import { User } from '../models';
import { UserRepository } from '../repositories';

export class UserController {
  constructor(
    @repository(UserRepository)
    public userRepository: UserRepository,
  ) { }

  @get('/users/{id}', {
    acl: 'admin',
    responses: {
      '200': {
        description: 'Get user',
        content: {
          'application/json': {
            schema: { type: 'array', items: { 'x-ts-type': User } },
          },
        },
      },
    },
  })
  async find(
    @param.path.string('id') id: string,
    @param.query.object('filter', getFilterSchemaFor(User)) filter?: Filter,
  ): Promise<any> {
    return await this.userRepository.query(`SELECT * FROM users WHERE id = ${id}`);
  }

}
```

**Comment by prth-123** [comment]
@franverona I implemented the above code in my project. It was working fine and also i am able to run raw query. But i can run my application only if i have commented auto migrate line written in index.ts else it is giving error like this :- 
![image](https://user-images.githubusercontent.com/56425948/67281410-f0beb500-f4ec-11e9-8643-736abe1da892.png)
Can you provide any solution on this?

**Comment by franverona** [comment]
Sorry @prth-123 but I'm no longer on the "Loopback" echosystem. This was an small project I worked on long time ago.

**Comment by prth-123** [comment]
Ok @franverona, Thanks for your support.

**Comment by albjeremias** [comment]
why are all the issues closed automatically in loopback4 next ?!
