### ISSUE TITLE
Why do we need @property decorators? Can't we just use type introspection?

### ISSUE THREAD

**Issue by clayrisser** [loopbackio/loopback-next#2157]
I honestly don't understand the reasoning behind the property decorator. If it does add extra metadata, shouldn't it still just be optional?

The following just seems redundant . . .

```ts
@property({
  type: 'string',
  required: false
})
username?: string
```

**Comment by bajtos** [comment]
I think there are good reasons for this, could you @raymondfeng please explain?

**Comment by raymondfeng** [comment]
@codejamninja The parameter of `@property` is optional. For example, you can do:
```ts
@property()
username?: string
```

But TypeScript does not provide the full reflection. For example, we won't know `username` is optional. Other metadata attributes can be added for the property using `@property` too.

**Comment by mschnee** [comment]
Here's another example:
```ts
@property({jsonSchema: { type: 'integer', minimum: 0}})
someUint: number;

// bson_id is a custom validation formatter
@property({jsonSchema: { type: 'string', format: 'bson_id' }})
someSpecificId: string;
```

I agree that it's poorly documented.  Writing custom formatters for AJV is extremely powerful: especially because you can use them for openapi schema validation and it "just works" any place the field is validated.  Let's say you want to ensure that string matches a format called `bson_id`:
```ts
// in your Application Context
this.bind(RestBindings.REQUEST_BODY_PARSER_OPTIONS).to({
  validation: {
    formats: {
      bson_id: (input: string) => ObjectId.isValid(input),
    },
  },
});
```
