### ISSUE TITLE
(Model) - Validate Uniqueness of - equivalent for LB4

### ISSUE THREAD

**Issue by Dallsant** [loopbackio/loopback-next#2184]
Is there an equivalent for this in LB4? I could do it manually on SQL, but on NoSQL it's a different story,  https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validatesuniquenessof sorry if it's a stupid question.

**Comment by Dallsant** [comment]
I found out you can do it with Mongo, but, it'd like to know if there's any way to achieve these validations at the model level with LB4. Good afternoon.

**Comment by dhmlau** [comment]
@bajtos @raymondfeng , is there any workaround on this? Thanks.

**Comment by dhmlau** [comment]
Talked to @raymondfeng, he mentioned that the workaround for now is to use `repository.count()` to get how many records the match the criteria. 

cc @madaky
