### ISSUE TITLE
Generate model classes by applying custom transformation on existing models

### ISSUE THREAD

**Issue by mi5ha** [loopbackio/loopback-next#2187]
Was wondering, can you define a Loopback model, so that objects of that model are created by executing some complex query on top of other models? Or models must be 1 to 1 mapped to database tables that they are connected to?

**Comment by bajtos** [comment]
Hi @mi5ha, in LoopBack 4, models are primarily used to describe data schema. The behavior (e.g. CRUD persistence via a database) is provided by [Repositories](https://loopback.io/doc/en/lb4/Repositories.html) and [Services](https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html). Then there are controller that are defining REST API endpoints and implementing them by calling out to repositories and services (typically).

So in your case, the part "objects of that model are created by executing some complex query on top of other models" can be implemented inside a controller (but that's difficult to reuse and test in isolation), inside a custom repository class (although I am not sure if your behavior fits "repository" pattern?) or in a new layer that will sit between controllers and repositories - see https://github.com/strongloop/loopback-next/issues/2239.

This is something we are still investigating, we don't yet have any prescribed/recommended way.

Please let me know if I have answered your question?

I think this can be useful for more people, can you suggest a place in our documentation where you would be looking for this kind of information?

**Comment by bajtos** [comment]
Sorry for taking so long to respond.

> In all our applications, we always have models as they are defined in persistence layer (database) and then we have domain models. 

At the moment, it's possible to define domain models decoupled from the database - just create a new class and decorate it with `@model()` and `@property()` decorators. 

We don't have tooling to generate such models from other models (or database schema).

I see how it could be useful, but to be honest, I don't think we will have time to look into that any time soon.
