### ISSUE TITLE
Memory connector should enforce referential integrity

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2333]
The memory connector should enforce foreign key and uniqueness constraints for HasMany, HasOne and BelongsTo relations.

For example, when creating an order using `/post/{userId}/orders` for a `userId` which is not that of a user, I would've expected some sort of a check that would've ensure that the `userId` exists. The connector should throw an error for an `userId` not in the database. 

See https://github.com/strongloop/loopback-next/issues/1718 for background and https://github.com/strongloop/loopback-next/issues/2332 for the SQL story.

See https://github.com/strongloop/loopback-connector-rest/issues/134 for a `Connector` helper to parse different styles of index/fk definitions into a format that's easy to consume by connectors.

## Acceptance criteria

- [ ] Modify the built-in `memory` connector to enforce unique indexes defined at model and property level, leverage the new helper implemented by https://github.com/strongloop/loopback-connector-rest/issues/134. See #1672  for the description of different ways on how model indexes can be defined. See https://github.com/strongloop/loopback-datasource-juggler/pull/1672 for prior implementation that was not finished.
- [ ] Modify the buit-in `memory` connector to enforce FOREIGN KEY constraints defined at model and property level, leverage the new helper implemented by https://github.com/strongloop/loopback-connector-rest/issues/134. See #1672 for the description of different ways on how model indexes can be defined.
- [ ] Warn the user about index/foreign-key options that are not supported by `memory` connector (see out-of-scope below).

### Out of scope

- "Plain" indexes without uniqueness check
- `onUpdate` and `onDelete` options for foreign keys

**Comment by bajtos** [comment]
The pull request https://github.com/strongloop/loopback-datasource-juggler/pull/1672 contains an early version of UNIQUE index support for our memory connector.

**Comment by jannyHou** [comment]
@strongloop/loopback-next Let's add the acceptance criteria for this story.

**Comment by bajtos** [comment]
I think we need to work on #2606 first and the implement any follow-up stories.
