### ISSUE TITLE
Spike: Strong relations in MongoDB

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2342]
Research what tools are offered by **MongoDB** for ensuring referential integrity.

Come up with a proposal on how LoopBack applications should implement the following relations:
  - 1-N (hasMany)
  - N-1 (belongsTo) 
  - 1-1 (hasOne/belongsTo)

For example, we can recommend referencesMany or embedsMany, but also find out that a completely new relation type is needed.

See https://github.com/strongloop/loopback-next/issues/2127 for wider context and https://github.com/strongloop/loopback-next/issues/1718#issuecomment-446906249 for explanation of strong vs. weak relations.

## Acceptance criteria

- [ ] A document explaining what mechanisms are offered by MongoDB to preserve consistency (integrity). (Start by studying MongoDB documentation and guides to build this understanding yourself.)
- [ ] A proposal: what LoopBack relations we want to recommend for MongoDB
- [ ] Arguments showing why we recommended the chosen relations, why other relations won't work with MongoDB. (This will build on top of the document from the first task.)
- [ ] User stories to implement the missing relation types identified as needed. If needed, create spike stories to figure out implementation details of some/all of these relation types.
- [ ] A pull request to update the overview created in #2341 with our recommendation (item 2) and our arguments (item 3). If we end up recommending relation types that are not implemented yet, then the overview should be updated with links to GH stories tracking these missing features.

**Comment by jannyHou** [comment]
timebox to 3 days.

**Comment by hadasiddhant** [comment]
Hello,

I am using loopback 4 for a startup and got stuck here referencing for mongodb one to many relations like the customer and order. Is there a solution for this?

**Comment by bajtos** [comment]
In general, NoSQL databases like MongoDB were not designed to support referential integrity. It's an intentional tradeoff they are making in favor of other properties, like easier scalability or resistance to network partitioning (see [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem)).

MongoDB is an object/document database where model relations are typically implemented by embedding related models. E.g. when a blog `Post` has many `Comment` instances, these comments would be stored directly in the owning `Post` entry.

My knowledge of MongoDB is limited and outdated, it's possible that MongoDB offers now solutions for achieving some degree of relational integrity - that's something we need to research as part of this story.

We don't have a solution you could use out-of-the-box now. You can use one-to-many relation with MongoDB if you can ensure referential integrity using other means. Alternatively, if it's an option, consider switching to an SQL database like PostgreSQL.
