### ISSUE TITLE
Spike: Strong relations in Cassandra

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2344]
Research what tools are offered by **Cassandra** for ensuring referential integrity.

Come up with a proposal on how LoopBack applications should implement the following relations:
  - 1-N (hasMany)
  - N-1 (belongsTo) 
  - 1-1 (hasOne/belongsTo)

For example, we can recommend referencesMany or embedsMany, but also find out that a completely new relation type is needed.

See https://github.com/strongloop/loopback-next/issues/2127 for wider context and https://github.com/strongloop/loopback-next/issues/1718#issuecomment-446906249 for explanation of strong vs. weak relations.

## Acceptance criteria

- [ ] A document explaining what mechanisms are offered by Cassandra to preserve consistency (integrity). (Start by studying Cassandra documentation and guides to build this understanding yourself.)
- [ ] A proposal: what LoopBack relations we want to recommend for Cassandra
- [ ] Arguments showing why we recommended the chosen relations, why other relations won't work with Cassandra. (This will build on top of the document from the first task.)
- [ ] User stories to implement the missing relation types identified as needed. If needed, create spike stories to figure out implementation details of some/all of these relation types.
- [ ] A pull request to update the overview created in #2341 with our recommendation (item 2) and our arguments (item 3). If we end up recommending relation types that are not implemented yet, then the overview should be updated with links to GH stories tracking these missing features.

**Comment by dhmlau** [comment]
There's a lower usage of the Cassandra connector compared to other connectors.  So this task has lower priority.
