### ISSUE TITLE
Polymorphic relation type

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2487]
Support polymorphic relation type.

For example, as single `AccessToken` model class can belong to multiple user-like model classes, using AccessToken's `principalType` property to distinguish between the targets.

See also LB 3.x docs: https://loopback.io/doc/en/lb3/Polymorphic-relations.html

**Comment by dhmlau** [comment]
cc @aharbis
I think this is something you're looking for.

**Comment by aharbis** [comment]
Thanks @dhmlau! Yes, this is a huge feature for our use-case. I'm happy to assist in design / testing / contributing where I can.

**Comment by hanut** [comment]
Is this being actively pursued or is contribution welcome ?
Also, is there any interim solution while a long term implementation is built.

**Comment by dhmlau** [comment]
@hanut, it's not being actively pursued but contribution is always welcome.

> Also, is there any interim solution while a long term implementation is built.

@bajtos might be able to shed some light on this. 

cc @hacksparrow

**Comment by hanut** [comment]
@bajtos @dhmlau 
In that case would it be okay if I pick it up to solve ?
My current project requires it urgently and seeing as I have been in love with Loopback since lb2, I really don't want to use anything else.

**Comment by dhmlau** [comment]
> In that case would it be okay if I pick it up to solve ?

Absolutely!  Let me assign it to you then. Thank you!

**Comment by bajtos** [comment]
Hi @hanut, thank you for picking up this task! Please let us know if you need any help, the fastest option is to reach out in `#loopback-contributors` channel in our Slack (invite: https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw).

Adding a new relation type usually involves a lot of design decisions to be made and many lines of code. It's best to open a draft pull request as early as you have something to show. This way we can discuss the right direction early on and avoid extensive rework (and wasted efforts) later on.

Good luck! 🍀 I am looking forward to see you proposal. :v:

**Comment by hanut** [comment]
@bajtos @dhmlau 
Cool. Im looking going to get started on this asap.

**Comment by hanut** [comment]
I have been working on an implementation and am stuck with a few considerations -
1. Polymorphic relations are basically just hasOne/hasMany <-> belongsTo relations with extra steps ie. adding in the type field to specify which type of related model is being referenced. However including the related data involves performing joins/lookups on the different tables/collections that are being referenced so I have a couple of performance concerns.
2. What level would this relation target ? I mean, for mongo (via the mongo connector) it would require $lookups and for sql it would need joins. Or should the inclusion happen at the db level (via query) or within the application layer (possibly using multiple queries).
3. The relations can also be established by adding multiple attributes for the fk of each entity type and only filling the one that is used. This shifts the operational complexity at framework layer to the database layer. (Joining the primary table with as many tables as there are foreignKey types)


For my use case, I implemented polymorphic relations using simple hasMany <-> belongsTo relations, one for each type of the morphable type. It works fine but at the expense of having nulls in the database.

I would like to get your view on this as I am pretty stuck with how to move forward with it.

**Comment by dhmlau** [comment]
For prosperity, I'm cross posting the reply from @bajtos on Slack:

> Hi Hanut, I agree that in an ideal ORM, we would use SQL joins and MongoDB $lookups to perform the joins. We haven't implemented that in LoopBack so far, because it's non-trivial to support all different databases. Instead, we perform such queries in two steps:
> 1. Query the source models to obtain a list of PK/FK values.
> 2. Query the target models using IN (inq) operator to find all models matching the PK/FK values obtained in the step 1.
>
> This seems to be working reasonably well, plus it allows you to have relations across databases (e.g. Users stored in legacy system-of-record SQL database can have "hasMany" relation to Sessions stored in MongoDB used by the front edge).
> To implement a polymorphic relation, you should follow the current design and find a place where to inject your new logic that will decide which models (SQL tables) to query depending on the discriminator value.
> You can take a look at the current implementation in juggler for inspiration.
> - https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/relation-definition.js#L220-L241
> - https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/relation-definition.js#L275-L283
> - https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/relation-definition.js#L1542-L1552
> - https://github.com/strongloop/loopback-datasource-juggler/blob/251ced811b80177f47efb6a3270ed6d279263c46/lib/include.js#L829-L887

**Comment by GwendalBroudin** [comment]
Hi any progress on this topic?

**Comment by OnTheThirdDay** [comment]
There can be a workaround for this. For example, we want to store Media, which can either be an Image or a Video, then:
**Media hasOne PolymorphicMedia
PolymorphicMedia belongsTo Media
Image extends PolymorphicMedia
Video extends PolymorphicMedia**

After building these classes and relations, in order to allow PolymorphicMedia (Image, Video) instances to be included when querying Media, the InclusionResolver for PolymorphicMedia within MediaRepository needs to be modified:
```
// modify the registerInclusionResolver part of media.repository.ts
this.registerInclusionResolver(
  'polymorphicMedia',
  getInclusionResolver({Image: imageRepositoryGetter, Video: videoRepositoryGetter, })
);
```
and here is the `getInclusionResolver`:
```
export interface TargetRepoDict<Target extends Entity, TargetRelations extends object> {
  [repoType: string]: Getter<
    DefaultCrudRepository<Target, StringKeyOf<Target>, TargetRelations>>;
}

export interface MediaOfCategories {
  [mediaType: string]: Media[];
}

export interface TargetOfCategories<Target> {
  [mediaType: string]: (Target & object)[];
}

export function getInclusionResolver<Target extends Entity, TargetRelations extends object>(getTargetRepo: TargetRepoDict<Target, TargetRelations>,): InclusionResolver<Media, Target> {
  return async function fetchHasOneModel(
    entities: Media[],
    inclusion: InclusionFilter,
    options?: Options,
  ): Promise<((Target & object) | undefined)[]> {
    if (!entities.length) return [];

    // const sourceKey = relationMeta.keyFrom;
    // this is hard-coded, should be dynamically extracted from the relation definition
    const sourceKey = "id";
    const sourceIds = entities.map(e => (e as AnyObject)[sourceKey]);
    // const targetKey = relationMeta.keyTo as StringKeyOf<Target>;
    // this is hard-coded, should be dynamically extracted from the relation definition
    const targetKey = "mediaId" as StringKeyOf<Target>;

    const scope =
      typeof inclusion === 'string' ? {} : (inclusion.scope as Filter<Target>);

    const entitiesCategorized: MediaOfCategories = {};

    entities.forEach((value, index, allItems) => {
      if (!entitiesCategorized[value.concreteType]) {
        entitiesCategorized[value.concreteType] = [];
      }
      entitiesCategorized[value.concreteType].push(value);
    });

    const targetCategorized: TargetOfCategories<Target> = {};
    let targetCategorizedArray: (Target & object)[] = [];

    for (let k of Object.keys(entitiesCategorized)) {
      const targetRepo = await getTargetRepo[k]();
      const targetsFound = await findByForeignKeys(
        targetRepo,
        targetKey,
        sourceIds,
        scope,
        options,
      );
      targetCategorized[k] =
        targetsFound;
      targetCategorizedArray = targetCategorizedArray.concat(targetCategorized[k]);
    }

    return flattenTargetsOfOneToOneRelation(sourceIds, targetCategorizedArray, targetKey);
  }
}
```

After all this, querying Medias should return both Images and Videos stored in the database.

This is not very reusable, and should actually be implemented as a relation repository factory, but anyway it allows polymorphic types to be referenced without breaking the relational constraints.

**Comment by OnTheThirdDay** [comment]
This issue has now been solved by https://github.com/loopbackio/loopback-next/commit/f4b8158387222ec64fe7ef6971da8151f2016dda

**Comment by achrinza** [comment]
Closed by: https://github.com/loopbackio/loopback-next/pull/8026
Continuation of work: https://github.com/loopbackio/loopback-next/discussions/8463
