### ISSUE TITLE
ReferencesMany relation type

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2488]
A ReferencesMany relation embeds an array of foreign keys to reference other objects. 

An example model instance:

```js
{
  id: 1,
  name: 'John Smith',
  accounts: [
    "saving-01", "checking-01",
  ]
}
```

See also LB 3.x docs: https://loopback.io/doc/en/lb3/Embedded-models-and-relations.html

**Comment by alparslanyilmaaz** [comment]
```
 @property({
    type: 'array',
    itemType: 'string',
  })
  exampleArray?: string[];

  @hasMany(() => MainComponent, {keyFrom: 'exampleArray', keyTo: 'id'})
  mainComponent: MainComponent[];
```
Does any one know, how to use keyFrom as array.

My problem is, I have an array which includes the foreing key id's as an array. I am trying to get those id's with their instances.

**Comment by achrinza** [comment]
Hi @alparslanyilmaaz, please either [open a new question issue](https://github.com/strongloop/loopback-next/issues/new?labels=question&template=Question.md) or ask in the [Slack org](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw). This is so that it's easier to discover your query and so that we can keep the comments related to the topic at hand.

**Comment by mrbatista** [comment]
@bajtos Please assign the task to me.

**Comment by Sweet-Bob** [comment]
In most frameworks, hasMany do this behaviour by default (return only ids), but when you pass { include: 'entity' }, it behave like embedded.

**Comment by hadnet** [comment]
Is this relation not implemented in LB 4 yet?

**Comment by njtnestor** [comment]
I need this relation, when will be implemented?

**Comment by DavidKrpt** [comment]
We are also using mongodb, and we have to either use hasManyThrough in those cases where referencesMany would be the obvious best choice according to mongodb data modelling best practices, or imitate referencesMany with custom repository methods. Either way it is inconvenient and has overhead costs.

If there are any details about the implementation of this feature, can you please share them ?

Also, can you recommend other workarounds besides the two I mentioned above?

**Comment by mikeevstropov** [comment]
@bajtos Hi! Do you have time to take a look at https://github.com/loopbackio/loopback-next/pull/8271 Relation works fine but CI failing
