### ISSUE TITLE
`lb4 model ModelName` fails when project directory structure is changed

### ISSUE THREAD

**Issue by pconerly** [loopbackio/loopback-next#2584]
## Description / Steps to reproduce / Feature proposal
I moved the directory of my loopback src from `project/src/` to `project/src/server`.
When I did `lb4 model ModelName` it failed

## Current Behavior
Fails when project directory structure changes

## Expected Behavior
Provide an option for the CLI to change "src" destination of where to find the `/models` folder.
Also add this option for the other cli code generators.

**Comment by dhmlau** [comment]
@pconerly, looking at the code https://github.com/strongloop/loopback-next/blob/master/packages/cli/lib/utils.js#L513-L518, it's hard coded here in where the artifacts being expected.  

I believe it will be a feature for us to make it recognizing different project structure. In the meanwhile, may I know what's your use case to put the LB artifacts in a different structure than the generated one?  Thanks.
