### ISSUE TITLE
Populate `{ModelName}Relations` through the CLI

### ISSUE THREAD

**Issue by nabdelgadir** [loopbackio/loopback-next#2988]
## Description / Steps to reproduce / Feature proposal

Once https://github.com/strongloop/loopback-next/pull/2960 is landed, `lb4 model` will add a generic empty `{ModelName}Relations` interface to the model class file.

Cross-posting from https://github.com/strongloop/loopback-next/pull/2960#discussion_r287668716:

@bajtos:

> Entries for individual relations would be added to {ModelName}Relations either manually by the application developer or by `lb4 relation` command.

## Current Behaviour

`lb4 model` generates empty interface, e.g.: 

```ts
export interface TodoRelations {}
```

`lb4 relation` does not add any navigational properties to this empty interface.

## Expected Behaviour

- [ ] Enhance `lb4 relation` to populate `{ModelName}Relations`

Example:

```ts
export interface TodoRelations {
 todoList?: TodoListWithRelations;
}
```

```ts
export interface TodoListRelations {
  todos?: TodoWithRelations[];
  image?: TodoListImageWithRelations;
}
```

**Comment by dhmlau** [comment]
Not sure if I'm missing something.  For the current `lb4 relation` flow, 
- create the source and target models
- create the repositories for both
- run the `lb4 relation` command to specify the model relation.  

But from the description of this issue, it seems like when we're running `lb4 repository`, we already have the relations defined?

**Comment by bajtos** [comment]
> Entries for individual relations would be added to {ModelName}Relations either manually by the application developer or by `lb4 repository` command.

Ah, that was a typo on my side. I meant `lb4 relation`. Let me fix the issue description.

The problem is that at the momemt, `lb4 model` creates an empty `{ModelName}Relations` interface. When `lb4 relations` adds a new relation, it is not adding navigational properties to that interface, the developer has to update the interface manually. The goal of this user story is to fix that.
