### ISSUE TITLE
MySQL tables are created for Model referenced in Entity

### ISSUE THREAD

**Issue by ludohenin** [loopbackio/loopback-next#3050]
## Description / Steps to reproduce / Feature proposal

When using `Model` class (not `Entity`) referenced in an `entity` property type, is it normal to see model related tables created in MySQL ?

```ts
@model()
export class MyModel extends Model {
  @property()
  myModelProps: string;
}

@model()
export class MyEntity extends Entity {
  @property({type: MyModel})
  myEntityProps: MyModel;
}
```

From here I get 2 tables created:
* MyModel <-- useless
* MyEntity <-- persistence corectly works here

**Comment by raymondfeng** [comment]
We probably need to introduce a flag to tell `MyModel` is not for persistence:

```
@model({persistent: false})
export class MyModel extends Model {
  @property()
  myModelProps: string;
}
```

**Comment by ludohenin** [comment]
As I understood it, we have `Model` for it means and we have `Entity` for persisted model but I'm probably wrong. A flag seems to be OK otherwise.

**Comment by bajtos** [comment]
> is it normal to see model related tables created in MySQL ?

When you say "see model related tables created", what did create the tables?

If you are using the built-in `app.migrateSchema` function, it should be creating tables only for models/entities that have a Repository class bound to the application.

Could you please create a small app reproducing the issue? See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by bajtos** [comment]
> As I understood it, we have `Model` for what it means and we have `Entity` for persisted model but I'm probably wrong.

Both Models and Entities can be persisted. The difference between a Model and an Entity is that Entity includes a primary key property (or more properties) that can be used to uniquely identify Entity instances. Model does not have any primary key, but it can be still persisted e.g. using KeyValue API where the key is always provided by the caller.

**Comment by ludohenin** [comment]
@raymondfeng I made a repo to showcase the issue https://github.com/ludohenin/lb-playground

if you look a the `User` model the `preferences` refers to a LB model, the (useless) table `Preferences` is created when I migrate. Data are persisted whitin the user one as expected.
