### ISSUE TITLE
Spike: Unregister runtime artifacts for Controller class

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#3124]
## Description / Steps to reproduce / Feature proposal
Originated from https://github.com/strongloop/loopback-next/issues/2619

Please see @bajtos' comment: https://github.com/strongloop/loopback-next/issues/2619#issuecomment-500740693 for details

### Acceptance Criteria
- [ ] When a controller + repo + model is unregistered, there must be no memory references remaining, so that V8 can release and collect the memory. 
- [ ] Test case: write a loop creating & unregistering model+repo+controller. The process should use relatively constant memory, the memory usage must not grow.
  - [ ] The test should not run it as part of `npm test` workflow

**Timebox to 3 days**

**Comment by bajtos** [comment]
> Test case: write a loop creating & unregistering model+repo+controller. The process should use relatively constant memory, the memory usage must not grow.

I am expecting that such test will require at least several seconds (if not minutes) to run. We should not run it as part of `npm test` workflow.
