### ISSUE TITLE
Spike: Unregister runtime artifacts for Repository and Service proxy

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#3125]
## Description / Steps to reproduce / Feature proposal
Originated from https://github.com/strongloop/loopback-next/issues/2619

Please see @bajtos' comment: https://github.com/strongloop/loopback-next/issues/2619#issuecomment-500740693 for details

### Acceptance Criteria
- [ ] When the artifact is unregistered, there must be no memory references remaining, so that V8 can release and collect the memory. 
- [ ] Test case: write a loop creating & unregistering the artifact. The process should use relatively constant memory, the memory usage must not grow.
   - keep that test outside of npm test, i.e. as a standalone script that can be run manually, e.g. via npm run test-memory-leaks.

**Comment by bajtos** [comment]
> Test case: write a loop creating & unregistering the artifact. The process should use relatively constant memory, the memory usage must not grow.

I am expecting that such test will require at least several seconds (if not minutes) to run. We should not run it as part of `npm test` workflow.

**Comment by dhmlau** [comment]
@bajtos, should we remove the 2nd bullet in the acceptance criteria?

**Comment by bajtos** [comment]
No no, it's important to have a test we can run to verify that unregistration works as intended. I am just asking to keep that test outside of `npm test`, i.e. as a standalone script that can be run manually, e.g. via `npm run test-memory-leaks`.

**Comment by dhmlau** [comment]
@bajtos, I've updated the acceptance criteria. Thanks.
