### ISSUE TITLE
Spike: Investigate setting up Windows CI workflow for connectors

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#3161]
## Description / Steps to reproduce / Feature proposal
@rmg suggested to shut down ci.strongloop.com which is mostly used for Windows testing.  

This spike is to investigate how we can use AppVeyor or Azure Pipelines for Windows testing on the connectors. There are some more information on Azure Pipelines from @virkt25. See:  https://github.com/strongloop/loopback-next/issues/1752

### Acceptance Criteria
- [ ] Investigate Azure Pipelines to see if it is suited for the Windows testings on connector.
   - [ ] Pick a connector to test it on (e.g. MongoDB)
- [ ] Document the process for setting it up (if it ends up being used).

cc @bajtos @b-admike 

**Timebox to 5 days**

**Comment by bajtos** [comment]
I am proposing to start investigating Azure Pipelines first. If it's easy to setup CI for our connectors there, then I would not bother with AppVeyor.

**Comment by dhmlau** [comment]
I've updated the title and acceptance criteria. Thanks.

**Comment by rmg** [comment]
GitHub has opened up Actions (https://github.com/features/actions) to limited beta, scheduled to become generally available on November 13.

What is particularly relevant to this spike is that it is based on a fork of Azure Pipelines and the services are run on Azure VMs.

Also useful is that it supports Linux, Windows, _and_ macOS.

**Comment by bajtos** [comment]
An article describing how to migrate a Node.js Travis CI build to GitHub actions: https://blog.testdouble.com/posts/2019-11-21-first-look-at-github-actions/
