### ISSUE TITLE
Support for unique index violation proper response instead of 500

### ISSUE THREAD

**Issue by amrsalama** [loopbackio/loopback-next#3258]
## Suggestion

Unique index violation (for example) in mongodb issues mongo driver error `'E11000 duplicate key error collection: loopback4.users index: username_1 dup key: { : "user" }'`
and rejected with status code `500` response.

It would be nice if we have proper response (for example) `422` instead of `500`.

I know that I can customize Sequence and handle it in catch section before `reject`. But can we have it auto rejected with proper status code instead? Like any other validation rejection.

## Use Cases

- Unique validation error.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dougal83** [comment]
This is dependant on the data connector in use, what about others?  That aside you can customise the model/controller to emit the error feedback that you require(like 409 Conflict). See example below:

[loopback4-example-shopping model declaration](https://github.com/strongloop/loopback4-example-shopping/blob/6758853069005782167f234e4c81c8384353caf8/packages/shopping/src/models/user.model.ts#L11-L20)
[loopback4-example-shopping controller](https://github.com/strongloop/loopback4-example-shopping/blob/6758853069005782167f234e4c81c8384353caf8/packages/shopping/src/controllers/user.controller.ts#L47-L69)

I had the same concern as you but submitted the above solution as a compromise.  The constraint was placed on the model to give a specific name to check against.  If you have a better alternative I'd love to hear your ideas.

**Comment by amrsalama** [comment]
@dougal83 Thanks for your reply. You are right about the the connector dependency and I think this is the big issue to handle. 

I think handling the problem in controller may leads to duplicate codes (in POST, PUT, PATCH).
My approach for now is to handle it in the Sequence

```js
async handle(context: RequestContext) {
  try {
    const {request, response} = context;
    const route = this.findRoute(request);
    const args = await this.parseParams(request, route);
    const result = await this.invoke(route, args);
    this.send(response, result);
  } catch (err) {
    if (err.name === 'MongoError' && err.code === 11000) {
      Object.assign(err, {
        statusCode: 422,
        name: 'UnprocessableEntityError',
        message:
          'The request body is invalid. See error object `details` property for more info.',
        code: 'VALIDATION_FAILED',
      });
    }
    this.reject(context, err);
  }
}
```

But I need to reject with identical loopback response without writing `message`, `code`, and `details` myself, any ideas ?

**Comment by dougal83** [comment]
@amrsalama Ultimately you are limited by the data connector, which can always be made more flexible.

Is anything stopping you making a universal block of error handling code and reusing it (DRY)?:

````ts
    if (err.name === 'MongoError' && err.code === 11000) {
        throw new HttpErrors.UnprocessableEntity('message')
    }
````
Each to their own but I'll mostly be verbosely describing my controllers as it fits my usage.

**Comment by amrsalama** [comment]
@dougal83 

```ts
    try {
      // create the new user
      const savedUser = await this.userRepository.create(user);
      delete savedUser.password;

      return savedUser;
    } catch (error) {
      // MongoError 11000 duplicate key
      if (error.code === 11000 && error.errmsg.includes('index: uniqueEmail')) {
        throw new HttpErrors.Conflict('Email value is already taken');
      } else {
        throw error;
      }
    }
```
Here we use `try/catch` inside controller to handle the `uniqueness` rejection by Mongo (Inner). And we have another `try/catch` block in Sequence (Outer).

But it would be nicer if we can handle this problem in the outer `try/catch` in Sequence.

I can't throw exception in `catch` block of the Sequence (app would crash and stop).

**Comment by Archer-Thane** [comment]
I have run the loopback4-example-shopping and run serveral times post /users and there are no error with code 11000.
take a look at[ this picture](https://imgur.com/a/QovWXXO).

**Comment by dougal83** [comment]
> I have run the loopback4-example-shopping and run serveral times post /users and there are no error with code 11000.
> take a look at[ this picture](https://imgur.com/a/QovWXXO).

Hi Archer

Can you please expand the User collection in the db and confirm that the UniqueEmail constraint exists?
 
![image](https://user-images.githubusercontent.com/2735881/70543692-b2478d00-1b62-11ea-9076-6ff8e1637605.png)

**Comment by dougal83** [comment]
> But it would be nicer if we can handle this problem in the outer `try/catch` in Sequence.
> 
> I can't throw exception in `catch` block of the Sequence (app would crash and stop).

@amrsalama Apologies for missing this message.  I see your point, there is no one right way to handle this, but I simply implemented the most expedient solution.  Feel free to submit a pull request to replace this code if you have an alternative.
