### ISSUE TITLE
Add support for seeders

### ISSUE THREAD

**Issue by amrsalama** [loopbackio/loopback-next#3291]
## Suggestion

This feature is inspired by [Laravel seeding](https://laravel.com/docs/5.8/seeding) system.
We can have CLI command to generate seeders for repositories, for example in `src/seeders` directory.

## Examples

Example for seeder file
```ts
import {UserRepository} from '../repositories';

interface Seeder {
  run(): Promise<void>;
}

export class UserSeeder implements Seeder {
  constructor(private userRepo: UserRepository) {}

  async run() {
    await this.userRepo.create({
      username: 'admin',
      password: 'password',
      email: 'admin@domain.com',
      name: 'John Doe',
    });
  }
}
```

In `application.ts`, following what was stated in [migrations docs](https://loopback.io/doc/en/lb4/Database-migrations.html#implement-additional-migration-steps)
```ts
async migrateSchema(options?: SchemaMigrationOptions) {
  await super.migrateSchema(options);
  new UserSeeder(await this.getRepository(UserRepository)).run();
}
```

Of course we can enhance this feature by adding more flags to `npm run migrate` to allow seeding `--seed`.

And to achieve the maximum benefit of the seeding system, We can define `factory` feature in the `Entity` model to allow auto generated instances from models.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dougal83** [comment]
There is also the option of [seeding via docker](https://phauer.com/2018/local-development-docker-compose-seeding-stubs/) that is worth considering.

**Comment by dhmlau** [comment]
@amrsalama, I've also created a blog post on how to seed a database using the life cycle observers in LoopBack 4.  https://medium.com/loopback/loopback-quick-tip-seeding-database-using-life-cycle-observer-8ddca55fea5c.

**Comment by dougal83** [comment]
> @amrsalama, I've also created a blog post on how to seed a database using the life cycle observers in LoopBack 4. https://medium.com/loopback/loopback-quick-tip-seeding-database-using-life-cycle-observer-8ddca55fea5c.

@dhmlau Good article.  You could expand this example by using [faker](https://www.npmjs.com/package/faker) for other data types.

**Comment by dhmlau** [comment]
Thanks @dougal83! Good to know about this package. :)

**Comment by dhmlau** [comment]
I think this seeder capability would make a good LoopBack extension (instead of putting as part of the core). @strongloop/loopback-maintainers , what's your thoughts on that?
