### ISSUE TITLE
Support RegExp Filter for nested attributes

### ISSUE THREAD

**Issue by dacamposol** [loopbackio/loopback-next#3295]
## Steps to reproduce

1. Having a REST API, with a MongoDB as datasource, that retrieves documents as the following one.
2. Having at least the following example in the collection, so we are sure that the collection is not empty.

`{
  "_id" : 00001,
  "firstAttribute": {
    "nestedOne":"abcde"
  },
  "secondAttribute":"abcde"
}`

3. Perform request to the previously defined API with the following filter defined:

`GET /collection?filter={"where":{"firstAttribute.nestedOne":{"regexp":"/^ab/i"}}}`

## Current Behavior

3a. Returns an empty collection

## Expected Behavior

3a. Returns the document shown as example 

## Notes

If instead to perform the RegExp filter over a nested attribute we perform it to a non-nested one, the filter works without problems. 

Example: `GET /collection?filter={"where":{"secondAttribute":{"regexp":"/^ab/i"}}}` will return the example document.
## Acceptance Criteria
- [ ] `regexp` should work for nested properties for Mongo and in memory db. Check if it works in SQL db like MySQL. If it doesn't work, up an issue for that.

**Comment by bajtos** [comment]
@b-admike @hacksparrow could you PTAL? I feel this may be related to the changes you implemented recently for coercion of nested properties. Not necessarily a bug or regression, perhaps a missing feature similar to what you worked on.

**Comment by bajtos** [comment]
@dacamposol it would help us a lot if you could create a small application that we can build & run locally, so that we don't have to build one ourselves. See https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs

**Comment by dacamposol** [comment]
I've forked your repository and in the following branch: https://github.com/dacamposol/loopback-next/tree/regex-where-filter-mongodb you can find an example (I've modified the HelloWorld application in the examples folder)

Basically with the previous application if you perform

`GET /users?filter={"where":{"name":{"like":"Daniel", "options":"i"}}}` 

You'll receive the only element of the collection, that follows this pattern:

```{"_id":{"$oid":"5d1dfa761c9d4400000918d5"},"name":"Daniel Campos","dni":"123456789Q","userdata":{"name":"Daniel Campos","dni":"123456789Q"}}```

Otherwise, if you perform the request

`GET /users?filter={"where":{"userdata.name":{"like":"Daniel", "options":"i"}}}` 

You receive an empty collection, when is expected to receive the same document.

**Comment by bajtos** [comment]
Thank you @dacamposol for the sample application ❤️ 

@hacksparrow @b-admike PTAL

**Comment by hacksparrow** [comment]
@bajtos the behavior is the same for `loopback-connector-mongodb@4.2.0` and `loopback-connector-mongodb@5.0.0`.

**Comment by hacksparrow** [comment]
Also, it's not limited to `loopback-connector-mongodb`. The issue is reproducible in the memory connector too.

**Comment by hacksparrow** [comment]
It is reproducible in a LB3 app too. The cause is likely in `loopback-connector` or `loopback-datasource-juggler`.

@bajtos how do we prioritize this?

**Comment by dacamposol** [comment]
In the meantime, if someone faces the same problem, the easiest workaround is to use a different MongoDB connector. Personally I've added the following code to the repository.ts class to prevent big changes in the code meanwhile the problem it's solved:

```{typescript}
import {MongoClient, Db} from 'mongodb';
import * as databaseData from '../datasources/db.datasource.json';

public extendedFind(
    rawFilter?: string,
    limit?: number,
    skip?: number,
    order?: string,
  ): Promise<ModelObject[]> {
    if (rawFilter) {
      let orderFilter = 'lfd';
      let orderValue = -1;

      if (order) {
        orderFilter = order.split(' ')[0];
        orderValue = order.split(' ')[1] === 'ASC' ? 1 : -1;
      }

      return new Promise<ModelObject[]>((resolve, rejected) => {
        MongoClient.connect(
          `mongodb://${databaseData.user}:${databaseData.password}@${
            databaseData.host
          }:${databaseData.port}/${databaseData.database}`,
          {useNewUrlParser: true},
          (connectionError, client) => {
            if (connectionError) {
              rejected(connectionError);
            } else {
              let db: Db = client.db(databaseData.database);
              let collection = db.collection('ModelObject');

              collection
                .find(JSON.parse(rawFilter))
                .skip(skip ? skip : 0)
                .limit(limit ? limit : 15)
                .sort({[orderFilter]: orderValue})
                .toArray(
                  (collectionError: Error, items: ModelObject[]) => {
                    if (!collectionError) {
                      resolve(items);
                    } else {
                      rejected(collectionError);
                    }
                  },
                );
              client.close();
            }
          },
        );
      });
    } else {
      return this.find();
    }
  }
```

**Comment by dhmlau** [comment]
@hacksparrow, could you please add the acceptance criteria? Thanks.

**Comment by agnes512** [comment]
Reproduce steps for `lb3` app:
App model json file like:
```js
{
  "name": "item",
  "properties": {
    "name": {
      "type": "string"
    },
    "itemData": {
       {"name": {
          "type": "string"
       }
     },
    "id": ...
   }
}
```
data:
```js
item:
{
{"id": 1, "name": "good", "itemData": {"name": "food"}}
}
```
`GET /items?filter={"where":{"name":{"regexp":"/oo/i"}}}`
This gives me `{"id": 1, "name": "good", "itemData": {"name": "food"}}`

`GET /items?filter={"where": "itemdata.name":{"regexp": /ll/i"}}}`
This gives me `[]` instead of `{"id": 1, "name": "good", "itemData": {"name": "food"}}`

**Comment by bajtos** [comment]
Since this does not work in LB3 either, I am re-labelling this to a feature request.
