### ISSUE TITLE
Reject queries with incompatible "filter.fields" and "filter.include"

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#3455]
The filter property `fields` allows callers to limit which model properties are returned by the database. This creates a problem when the primary or the foreign key is excluded from the data, because then we cannot resolve included models.

```ts
categoryRepo.find({
  fields: ['name'],
  include: [{relation: 'products'}],
});
```

In LB3, I think we were silently ignoring `include` filter in such case.

I am proposing to be more explicit in LB4 and reject such queries with a 4xx (Bad Request) error.

Later, we can improve our implementation to automatically add PK/FK properties to the `fields` configuration and remove PK/FK properties from the data returned back to the user, so that inclusions are resolved as expected and yet the data contains only the specified properties.

See also https://github.com/strongloop/loopback-next/pull/3387

## Acceptance criteria

TBD - will be filled by the team.

**Comment by InvictusMB** [comment]
@bajtos Do you think #5592 is a viable solution for this?

**Comment by bajtos** [comment]
> Do you think #5592 is a viable solution for this?

Yes, if we can fix resolvers to transparently add the necessary `fields`, then there is no need reject queries excluding PK/FK fields.
