### ISSUE TITLE
Improve lb4 discover to discover relations

### ISSUE THREAD

**Issue by godartm** [loopbackio/loopback-next#3490]
## Suggestion

Actually a models can be discovered from a supported datasource by running the lb4 discover command.
But this didn't detect relation between table .
But for me, the strong advantage of the discover option is to detect the relation beetween model and create the navigational property.
If the datasource support this feature (For exemple: mysql),

## Use Cases

This will allow us to save time when creating model for an existing database.
For exemple if you want to migrate to loopback 4 with an existing database.

What shortcomings exist with current approaches?

Actually the model is create right but the navigational property is not created.
  

## Examples

An exemple how the feature can be use is to run  lb4 discover with a new extra argument or just add this feature by default.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@bajtos, do you think it would be part of the [strong relation epic](https://github.com/strongloop/loopback-next/issues/2331)?

**Comment by morfie78** [comment]
Any update on this?

**Comment by aspectgfg** [comment]
Was able to add relation support.
https://github.com/aspectgfg/loopback-next
Only changes were to grab model defs with relations/foreignKeys, and then run the Relation Generator for each relation.
It's not good enough for a PR though, do with it what you will.

**Comment by mbnoimi** [comment]
I believe this feature request is a vital one just like feature request #6002
