### ISSUE TITLE
[Spike/Discussion] The proposal of the new requestBody decorator

### ISSUE THREAD

**Issue by jannyHou** [loopbackio/loopback-next#3493]
### Description

A follow up story of https://github.com/strongloop/loopback-next/issues/2654
In the spike story https://github.com/strongloop/loopback-next/issues/2654, @jannyHou proposed a new signature `@requestBody(spec, model, schemaOptions)` to simplify the way of providing schema configs, the design is explained in [file](https://github.com/strongloop/loopback-next/blob/5877f0cc0201af59f2a9636a09753207c599ab26/packages/openapi-v3/_spike-request-body.md).

This story is created for further discussion: 

The conversations are mainly tracked in: https://github.com/strongloop/loopback-next/issues/2654, https://github.com/strongloop/loopback-next/pull/3398 and https://github.com/strongloop/loopback-next/pull/3466#discussion_r308650887

There are different proposals from @bajtos (I will summarize Miroslav's opinions later)
    - `@requestBody(specWithOptions, model)`
    - or `@requestBody(spec, getModelSchemaRef(model, options))`
    - or any better signatures

## Acceptance criteria

- [ ] Let's agree on the proposal first
- [ ] If we agree on the original proposal mentioned in [file](https://github.com/strongloop/loopback-next/blob/5877f0cc0201af59f2a9636a09753207c599ab26/packages/openapi-v3/_spike-request-body.md), decide which signatures should be disabled
  - Related discussion: follow the chat in https://github.com/strongloop/loopback-next/pull/3466/files#r308655533

**Comment by emonddr** [comment]
Let's have a meeting to discuss this first.
