### ISSUE TITLE
Feature request: navigate through different model

### ISSUE THREAD

**Issue by godartm** [loopbackio/loopback-next#3499]
Hi ,

## Suggestion

Add the possibility to get a model trought different model  based on primary key.

## Use Cases

Lets imagine i have model foo , bar , baz and all have an ID as primary key.

foo have a relation with bar,
bar have a relation with baz.

How can i retrieve baz from foo ?

Actually i can do

- fooRepository.bar(id)
- barRepository.baz(id)

## Examples

It should be possible to do : 
```
 fooRepository.bar(id).baz(id)
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by nabdelgadir** [comment]
@godartm Let's say you have 

Foo: 
`{id: 1, name: 'foo 1'}`

Bar:
`{id: 1, name: 'bar 1', fooId: 1}`
`{id: 2, name: 'bar 2', fooId: 1}`

Baz:
`{id: 1, name: 'baz 1', barId: 1}`
`{id: 2, name: 'baz 2', barId: 2}`
`{id: 3, name: 'baz 3', barId: 1}`

Just so I understand this issue correctly, what's your desired outcome when you do something like `fooRepository.bar(1).baz(1)`? Because `fooRepository.bar(1).find()` would return:

```
[{id: 1, name: 'bar 1', fooId: 1},
{id: 2, name: 'bar 1', fooId: 1}]
```

So when you do `fooRepository.bar(1).baz(1)`, should it return the following?

```
[{id: 1, name: 'baz 1', barId: 1},
{id: 3, name: 'baz 3', barId: 1}]
```

**Comment by godartm** [comment]
Yes you understand right the issue =)

**Comment by nabdelgadir** [comment]
@godartm Thanks! LoopBack doesn't currently have a way to do this directly, so I created a custom controller class as an example:

```ts
import {Filter, repository} from '@loopback/repository';
import {get, getModelSchemaRef, param} from '@loopback/rest';
import {Child} from '../models';
import {GrandparentRepository, ParentRepository} from '../repositories';

export class GrandparentChildController {
  constructor(
    @repository(GrandparentRepository)
    protected grandparentRepository: GrandparentRepository,
    @repository(ParentRepository)
    protected parentRepository: ParentRepository,
  ) {}

  @get('/grandparents/{gid}/{pid}/children', {
    responses: {
      '200': {
        description: "Array of Children belonging to Grandparent",
        content: {
          'application/json': {
            schema: {type: 'array', items: getModelSchemaRef(Child)},
          },
        },
      },
    },
  })
  async find(
    @param.path.number('gid') gid: number,
    @param.path.number('pid') pid: number,
    @param.query.object('filter') filter?: Filter<Child>,
  ): Promise<Child[]> {
    const parents = await this.grandparentRepository.parents(gid).find();
    const parentIds = parents.map(p => p.id);

    const children: Child[] = [];
    const parentsChildren = await this.parentRepository
      .children(pid)
      .find(filter);

    parentsChildren.forEach(child => {
      if (
        !children.some(c => child.id === c.id) && // check duplicates
        parentIds.includes(child.parentId)  // make sure it's the child of a parent of the specified grandparent
      ) {
        children.push(child);
      }
    });

    return children;
  }
}
```

In this case `Foo` = `Grandparent`, `Bar` = `Parent`, and `Baz` = `Child`. 

I'm sure there's a way to make this more efficient, but this is just something to go off of. Please let me know if you have any other questions.

**Comment by godartm** [comment]
Thanks for the reply , and thanks for the exemple. =) 

I can be good to request a feature about this  and update the doc to explain how to do this use case.

**Comment by nabdelgadir** [comment]
You can update the current issue description with the fields from the [Feature request template](https://github.com/strongloop/loopback-next/issues/new?labels=feature&template=Feature_request.md) or open a new issue and close this one. 😄

**Comment by godartm** [comment]
@nabdelgadir i have updated this issue, can you add the "Feature" label please =)
