### ISSUE TITLE
Improve docs on defineCrudRestController

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-next#3862]
There was a long discussion on the PR https://github.com/strongloop/loopback-next/pull/3842 about dependency injection for controllers created using `defineCrudRestController`. We decided to land the PR and follow up with a new issue or PR which would cater to the expressed concerns in a more specific manner.

Comment by @bajtos:

> I am proposing to land the current version and open a new issue or a new pull request to discuss how to improve the example code snippet.

**Acceptance Criteria**

- [ ]  A spike on subclassing or naming the object returned by `defineCrudRestController`. For details refer to this discussion https://github.com/strongloop/loopback-next/pull/3842#pullrequestreview-295696365.

**Comment by dhmlau** [comment]
@hacksparrow, could you please add the acceptance criteria for this task? Thanks.

**Comment by dhmlau** [comment]
Seems like it's no a high priority item. Moving out from Q3.
