### ISSUE TITLE
Firebase Authentication package built-in

### ISSUE THREAD

**Issue by lazzyms** [loopbackio/loopback-next#3931]
Feature Request :
Add a package/connector for firebase-authentication. This should replace loopback's default user authentication. A developer just needs to add firebase config.

**Comment by lonewolfaka9** [comment]
+1

**Comment by achrinza** [comment]
Do consider using the 👍 (thumbs up) button on the main comment to show interest for the feature. This would help keep the thread clean.

**Comment by tahir-jamil** [comment]
hi @bajtos  any update on it ? 
this feature really helps backend developers to switch from firebase to loopback
