### ISSUE TITLE
Import model from JSON Schema

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#3961]
## Suggestion

At the moment, `lb4` offers different ways for creating model classes (`src/models/{name}.model.ts`):

- Using an interactive prompt via `lb4 model`
- Importing from database schema via `lb4 discover`
- Importing from a LB3 app via `lb4 import-lb3-model`

It would be great allow developers to create model classes from JSON Schemas too.

## Examples

Let's say I have a file with the following content:

```json
{
  "title": "Product",
  "properties": {
     "name": {"type": "string"},
     "description": {"type": "string"},
  },
  "additionalProperties": false,
  "required": ["name"],
}
```

Using a new `lb4` command, I would like to get the following model class defined:

```ts
@model({
  settings: {
    strict: true, // <- inferred from "additionalProperties: false"
  },
})
export class Product extends Entity {
  @property({required: true})
  name: string;

  @property({required: false})
  description?: string;
}
```
## Acceptance criteria

TBD - will be filled by the team.

**Comment by marioestradarosa** [comment]
@bajtos , can't the generator just generate the appropriate constructor and import the JSON file automatically ?  Currently it is supported right? (to import the json file directly)
