### ISSUE TITLE
Define a DataTransferObject model with a subset of model properties

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#3962]
## Suggestion

Quite often, we want different endpoints to accept or return only a subset of model properties.

At the moment, it's possible to opt-into navigational properties for relations, exclude a list of properties or make all properties optional.

I would like a more general approach that will allow to define a DTO object using a white-list of allowed properties.

For example, when implementing a `login` endpoint, I may want to say that only `email` and `password` properties are accepted. This can be e.g. achieved by implementing a new `JsonSchemaOption` field like `pick`:

```ts
class UserController {
  async login(
    @requestBody(
      content: {
        'application/json': {
          schema: getModelSchemaRef(User, {title: 'LoginCredentials', pick: ['email', 'password']}),
        },
      },
    )
    credentials: Pick<User, 'email' | 'password'>,
  ) {
    // login implementation
  }
}
```

This approach is problematic:
- We have to repeat the list of properties to pick, once in `getModelSchemaRef`, second time in argument type.
- It's not possible to share this DTO between multiple methods

To push this a bit further: As discussed elsewhere, the `password` should be stored on a different model than the `User`, therefore we need a more powerful tool:
 - Pick `email` from the `User` model. (This needs to support more than just one property to be picked.)
 - Add `password` as a required property of type `string`. (This needs to support more than a single added property.)

## Use Cases

- login method as shown above
- building API endpoints that provide different views on the same backing database (models)

## Examples

See above.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Salketer** [comment]
Meh, why not let your model define it? We do this quite often in our app:

```
// user.model.ts
export const LoginCredentialsSchema = getModelSchemaRef(User, {title: 'LoginCredentials', pick: ['email', 'password']});
export type LoginCredentials = Pick<User, 'email' | 'password'>
```

That would keep things reusable and I think that since you're playing with the model's "shapes", there's no better place than to have them with it.

> We have to repeat the list of properties to pick, once in getModelSchemaRef, second time in argument type.

This tough, is always cumbersome... Wouldn't the decorator be able to create the schema by itself using the parameter's type?
