### ISSUE TITLE
PostgreSQL, Array Type queries

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [loopbackio/loopback-next#4005]
We need a feature/option in LoopBack for Where clause, to include raw condition statements for select statements.

We are dealing with array type, we have verified that Loop Models CRUD works with Array type, however fails for the Select with where statement where we need to filter the array by using @< or @> statements. I have checked the source code in loopback-postgresql connector, loopback-connector/sql.js files, found no relevant support for PostgreSQL Array filtering.

http://www.postgresqltutorial.com/postgresql-array/

Especially contains @> operator.
https://www.postgresql.org/docs/9.6/functions-array.html

Does loopback has option to include plain conditions like "lang @< ARRAY['JS', 'NODE']" in the where clause? This will enable us to use loopback where/filter capabilities whatever supported and additional one can be added by us with raw conditions. 

```js
where: {
   and: [
             "lang @< ARRAY['JS', 'NODE']" ,
             {name: 'Krish'}
        ]
}
```

**Comment by ewrayjohnson** [comment]
I had a similar problem with the ts_vector datatype.  I tried to enhance the connector but was only able to create a partial solution because of the way the connector framework delegates to the connector.  I’ve read that custom datatypes are the solution, but I am skeptical because there doesn’t also appear to be support for custom operators/predicates.

**Comment by ewrayjohnson** [comment]
See this:  https://github.com/strongloop/loopback-connector-postgresql/issues/4#issuecomment-42847309

**Comment by gopalakrishnan-subramani** [comment]
Thank you @ewrayjohnson , we need to see how to implement the same. We tried adding a operator called 'contains', but found that when it reach postgresql connectors' _buildWhere function, the operands converted to '[Object object]' string instead of the actual Object type as it is.
