### ISSUE TITLE
feature : verify/re-establish connection in connector.execute(sql)

### ISSUE THREAD

**Issue by emonddr** [loopbackio/loopback-next#4125]
Executing custom sql by directly calling connector.execute(sql) has never been the 
recommended approach and is highly experimental and subject to change; as mentioned in
https://loopback.io/doc/en/lb3/Executing-native-SQL.html 

The recommended approach in LB3 and LB4 is to let the model/juggler-datasource/connector code path have control over executing SQL queries since this code is mature and verifies a connection before executing any SQL.

In December 2018, an `execute` method was added to the juggler 4.x datasource.

https://github.com/strongloop/loopback-datasource-juggler/commit/fda332d60b428c05b0fbf9c5e6aff389468cbd1f#diff-9e9565730a5d5c0bdf028ccde9dd3a4e

@raymondfeng was suggesting that we can add similar logic as 

`stillConnecting()` used in the CRUD functions for a model

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L470

to  datasource.execute(sql,...) and/or connector.execute(sql,...) so that we ensure there is a
connection before any SQL is executed.

This can be done in juggler 4.x for the datasource, and possibly ported to juggler 3.x .

Not sure about the fate of connector.execute(sql) if we now have datasource.execute(sql)

# Acceptance Criteria 

- [ ] datasource.execute(sql) ensures a connection before executing sql
- [ ] connector.execute(sql) ensures a connection before executing sql ?
- [ ] Changes backported from juggler 4.x to 3.x 
- [ ] Add additional mocha test cases 
- [ ] Update documentation
- [ ] Blog

**Comment by bajtos** [comment]
> Not sure about the fate of connector.execute(sql) if we now have datasource.execute(sql)

Please note that `dataSource.execute` is just a sugar wrapper adding promise support, it delegates most of the work to `connector.execute` as can be seen here:

https://github.com/strongloop/loopback-datasource-juggler/commit/fda332d60b428c05b0fbf9c5e6aff389468cbd1f#diff-9e9565730a5d5c0bdf028ccde9dd3a4eR2628

**Comment by bajtos** [comment]
> Changes backported from juggler 4.x to 3.x

I'd like to discuss this task. 

1. I believe `dataSource.execute` was added to 4.x version, it's not available in 3.x at all.
2. 3.x is in LTS mode, we shouldn't be adding new features. If `dataSource.execute` is not available in 3.x, then we shouldn't be adding it now (IMO).

**Comment by jannyHou** [comment]
Some background of the issue we are facing(Dom can correct me if anything wrong): with a running lb3 app, shuts down the database server then recovers, then sends a query to the database using `connector.execute()`, the connection for datasource won't establish automatically. 
User need to connect manually like 
```js

ds.connector.connect((err)=> {
  if (err) return cb(err);
  ds.connector.execute('cmd', cb);
})
```

We'd like to add the auto connect logic into the `execute` function, and by having a juggler level or loopback-connector level `execute` we can avoid adding dup logic in each connector.

So @bajtos do you think it makes more sense to add the auto connect in `loopback-connector`?
