### ISSUE TITLE
bug(cli): type is missing when using type alias for string

### ISSUE THREAD

**Issue by derdeka** [loopbackio/loopback-next#4211]
## Steps to reproduce

I've defined a type alias `export type UUID = string;` to be used whenever a UUID is used. This helps the developers to easily read the application code and understand which type of string is expected there.

Id's in Models are defined this way:

```
@property({
  id: true,
  generated: true,
  jsonSchema: {
    pattern: PATTERN_UUID,
  },
})
id?: UUID;
```

When creating controller code by `lb4 relation`, the type of the `ID` is not correctly resolved.

## Current Behavior

When using `lb4 relation` the cli does not correctly resolve the type of the `ID`, something like this is generated:

![image](https://user-images.githubusercontent.com/13640166/69641285-3a586d80-1060-11ea-8150-bcff661021d0.png)

## Expected Behavior

If possible, resolve to native types !?

## Additional information

`
@loopback/cli version: 1.26.0
`

**Comment by raymondfeng** [comment]
Please try to add `type: 'string'` to `jsonSchema`. I don't think TS emits the right design:type for `id?: UUID`. Can you check the corresponding transpliled `js` file under `dist`?

**Comment by bajtos** [comment]
I see two aspects here:

1. Our CLI tool should not use empty string as the type when emitting `@param.path.()`. When the type is not known, it can e.g. prompt the user to pick one of the types supported by our param decorators.

2. As @raymondfeng mentioned, we are not able to infer target type when an alias is used. IMO, you should specify `type` inside `@property` decorator (not in `jsonSchema`):

```ts
  @property({
    id: true,
    type: 'string',
    generated: true,
    jsonSchema: {
      pattern: PATTERN_UUID,
    },
  })
  id?: UUID;
```

The second item above opens an interesting question - how to allow developers to create custom property types that can provide both TypeScript typings but also LB4 property metadata? Ideally, the part `{type: 'string', jsonSchema: {pattern: PATTERN_UUID}}` should be encapsulated in the `UUID` type. This is useful for MongoDB's ObjectID type too, which we want to treat as an alias for string (see https://github.com/strongloop/loopback-next/issues/3456). I feel this discussion is out of scope of this issue though, let's open a new GH issue if we want to continue the discussion.

**Comment by derdeka** [comment]
> 2\. As @raymondfeng mentioned, we are not able to infer target type when an alias is used. IMO, you should specify `type` inside `@property` decorator (not in `jsonSchema`):

I had a look into my transpiled files now - the design type is `String` for type alias `UUID` in my case. The interferring of the target type seems to work somehow even with a type alias. I guess the cli tool could do this too. Needs more investigation.
