### ISSUE TITLE
Enhance Repository patch functions to allow MongoDB Update Operators

### ISSUE THREAD

**Issue by nflaig** [loopbackio/loopback-next#4379]
# Suggestion

Currently it is not possible to use advanced [MongoDB operators](https://docs.mongodb.com/manual/reference/operator/). A good start would be to enhance the `Repository` update implementations to allow [MongoDB update operators](https://docs.mongodb.com/manual/reference/operator/update/).

This feature is already supported by LoopBack 3 but not yet usable in Loopback 4 without a workaround, as described [here](https://github.com/strongloop/loopback-next/issues/3342).

# Acceptance criteria
- [ ] First-class support for MongoDB update operators

**Comment by bajtos** [comment]
Related: https://stackoverflow.com/q/59552507/69868

**Comment by nflaig** [comment]
@bajtos the approach described [here](https://stackoverflow.com/questions/57800435/how-to-use-mongodb-extended-operators-in-loopback-4) seems to be working. It is still some kind of a workaround
