### ISSUE TITLE
How do I customize how query strings, headers, and bodies are parsed?

### ISSUE THREAD

**Issue by ritch** [loopbackio/loopback-next#448]
We should create an example and docs for implementing my own opinionated version of parsing params.

Scenarios to cover:

 - I want to use my custom JSON parser because some reasons (it's faster, more secure, whatever)
 - I want to use non-JSON formatting, e.g. XML

**Comment by bajtos** [comment]
Removing from GA scope, both use cases listed in the issue/story description are not a part of our scope as defined in #1449

**Comment by chibuike-uduma** [comment]
Lemme review and work on it
