### ISSUE TITLE
Discovery not preserving "generated" and "type" properties

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#4557]
## Steps to reproduce

This is originated from https://github.com/strongloop/loopback-next/issues/4505. 

1. I create a model with the following id property. It is `generated` using the `gen_random_uuid()` function in postgresql database. 
```
@property({
    type: 'string',
    id: true,
    generated: true,
    useDefaultIdType: false,
    postgresql: {
      dataType: 'uuid',
      extension: 'pgcrypto',
      defaultFn: 'gen_random_uuid()', 
    },
  })
  id?: string;
```

2. Run migrate script, so that the table definition looks like:

```
# \d review
                             Table "public.review"
 Column  |           Type           | Collation | Nullable |      Default      
---------+--------------------------+-----------+----------+-------------------
 id      | uuid                     |           | not null | gen_random_uuid()
 date    | timestamp with time zone |           | not null | 
 comment | text                     |           | not null | 
Indexes:
    "review_pkey" PRIMARY KEY, btree (id)
```

3. Now, I create another LB4 app and run the `lb4 discover`. 
The generated id property is:
```
  @property({
    type: 'string',
    required: true,
    id: 1,
    postgresql: {
      columnName: 'id',
      dataType: 'uuid',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  id: string;
```
## Current Behavior

However, there are 2 problems with the generated code above:
**Problem 1** - "generated" property is lost
If I run the above snippet as-is to `POST`, it will fail because it's expecting an id value in the payload. 

**Problem 2** - in a GET call, the `id` value displays null in API Explorer even though everything looks right from the database

i.e. in API explorer, it returns:
```
[
  {
    "id": "null",
    "date": "2020-02-03T20:46:11.253Z",
    "comment": "test"
  },
  {
    "id": "null",
    "date": "2020-02-03T20:46:11.253Z",
    "comment": "test2"
  }
]
```

## Expected Behavior
In order to fix it, I made the following changes:
```
@property({
    type: 'string',
    // required: true,  //<-- remove/comment this line
    id: 1,
    generated: true,  //<--- add this line
    useDefaultIdType: false,  //<-- add this line
    postgresql: {
      columnName: 'id',
      dataType: 'uuid',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  id?: string; // <-- make this optional
```

I'm not sure if this is related to Postgresql database only. 

### Acceptance Criteria 
- [ ] If the table column (for sql database) is generated, `lb4 discover` should generate the property with `generated: true` and `required: false`.

**Comment by dhmlau** [comment]
cc @agnes512

**Comment by agnes512** [comment]
Thanks for bringing up the issue. 

From my understanding, some fields are for migration usage only such as `generated` and `useDefaultIdType`. These tags tell a connector how to create a table. 

As for the result of `lb4 discover`, I have two concerns here:
- the `generated` field is not needed as it is for migration 
- `required` here not just means the column cannot be null, but also means that it needs to be included in the POST request. However, this will conflict with the controller if we answer the prompt with **YES**:
  `? Is the id omitted when creating a new instance? Yes`

So I think to fix the case that 'if a table has some fields auto generated', the `required` field  of the corresponding property should be ignored ( false). Thoughts?

**Comment by dhmlau** [comment]
> So I think to fix the case that 'if a table has some fields auto generated', the required field of the corresponding property should be ignored ( false). Thoughts?

Yes, I think that's the issue.

**Comment by dhmlau** [comment]
> the generated field is not needed as it is for migration 

I think one of the usage for LoopBack is that you can discover a table in one database and then use database migrate script to generate the table in another database. So IMHO this should be preserved as well.

**Comment by agnes512** [comment]
Found another bug: it adds the free form property 
```
  // Define well-known properties here

  // Indexer property to allow additional data
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [prop: string]: any;
```
to models that are using SQL DBs, which may raise errors as this feature is only supported by NoSQL DBs.

**Comment by mbnoimi** [comment]
Is there any progress on this bug?
Practically I'm unable to use lb4 because I've a huge database so `lb4 discover` is vital in [my case](https://stackoverflow.com/questions/64676381/how-to-control-primary-key-creation-in-lb4-discover/).

**Comment by mbnoimi** [comment]
@dhmlau Do you've any plan to fix this bug in the next milestone?
