### ISSUE TITLE
[Spike] How to migrate Angular 1.x and 2+ LB3 client

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#4610]
Originated from epic: https://github.com/strongloop/loopback-next/issues/3954

A spike on migrating Angular 1.x and 2+ LB3 client.

### Acceptance Criteria 
- [ ] Find out whether [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) a good solution
   - If yes, how to migrate?
   - If no, what would be our recommended solution in the context of migration guide?
- Expected outcome:
   - [ ] our recommended approach and description on how to do it. 
   - [ ] create a follow up task, if needed, to add the instruction as part of the migration guide

**Comment by derdeka** [comment]
@dhmlau I did POCs for [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator) and [ng-openapi-gen](https://github.com/cyclosproject/ng-openapi-gen) in the last weeks and can share some stuff. Both of them have their upsides and downsides, but are very different to [loopback-sdk-builder](https://github.com/mean-expert-official/loopback-sdk-builder). My hope was to find a kind of drop-in-replacement for `loopback-sdk-builder` to limit the required refactorings to my frontend application to a minimum in the first step, but both of them need big changes.

How do you want to run the spike? I suggest to create two alternative frontends for loopback4-example-shopping to test both sdks. How to start?

**Comment by dhmlau** [comment]
@derdeka, it would be great if you could share the information between OpenAPI generator and ng-openapi-gen. Thanks! 

I just discussed with @bajtos, it might be good to:
- take the [CoffeeShop application](https://loopback.io/doc/en/lb3/Introducing-the-Coffee-Shop-Reviews-app.html) as the starting point - it's a smaller app than the shopping app
- generate the client using LB3 SDK client and OpenAPI generator (or ng-openapi-gen). 
- compare the differences
WDYT?

Also, we're not sure if we should only investigate the Angular 2+ client route, perhaps there are much fewer users on Angular 1.x?

**Comment by derdeka** [comment]
> * take the [CoffeeShop application](https://loopback.io/doc/en/lb3/Introducing-the-Coffee-Shop-Reviews-app.html) as the starting point - it's a smaller app than the shopping app

@dhmlau AFAIK there is no coffeeshop app written in `lb4` yet. Correct?

**Comment by dhmlau** [comment]
@derdeka, I'm so sorry that I missed your message. There is no specific CoffeeShop example yet, however, I just created a validation example https://github.com/strongloop/loopback-next/pull/4895 which uses a `CoffeeShop` model.

**Comment by dhmlau** [comment]
Also, the LB4 app in #4895 (validation example) won't have model relations.

**Comment by dhmlau** [comment]
From our last maintainers call, @derdeka mentioned that the client generated by the client generators he looked at are not quite similar to the one generated by LB3 Angular SDK. 

@raymondfeng @derdeka, could you please fill us in on the approach suggested by @raymondfeng? Would like to see how we can move forward with this. Thanks!
