### ISSUE TITLE
Docs on creating an lb4 app using bottom-up approach

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#4697]
Related stale issues: #1512 #1513 #1514 #1515
Similar PR: #4629

The docs do not provide a method to build lb4 apps using a bottom-up approach. This can make it difficult for new users to understand the responsibilities of the different components in lb4.

* This means users may have to dig through previous GitHub issues, pull requests and blog posts.
* As a result, the users' ability to leverage the extensibility of lb4 may be hindered.
* This increases friction in adopting lb4.

## Suggestion

Add a "writing from scratch" page for each components in lb4 Some potential candidates from the top of my head are:

- [ ] `application`
- [ ] `controller`
- [ ] `datasource`
- [ ] `model`
- [ ] `repository`
- [ ] `route`
- [ ] `service`

## Use Cases

This can be invaluable for new users who may not be as familiar with the LoopBack 4 design.

## Examples

TBD

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Tronix117** [comment]
Agreed, the doc needs to be improved a lot, there is a lot of room to make clean code, however it's really hard to do it due to lack of documentation. For exemple : https://loopback.io/doc/en/lb4/Services.html does not explain what is a service for, and what are its capabilities. It needs a lot of efforts to understand compared to other framework making it way simpler to start from scratch.

**Comment by dhmlau** [comment]
@achrinza @Tronix117, thanks for the feedback. I'd +1 for any improvements on the docs. :) 

@achrinza, I'm not sure if I understand what you mean by `Add a "writing from scratch" page for each components`. Would you like to submit a draft PR to continue the discussion? Even a skeleton with some brief description could help. 

@Tronix117, for the [Services page](https://loopback.io/doc/en/lb4/Services.html), it mentions there are 3 types of services. Do you think it lacks of examples of each type?  Again, PR is welcomed! 

Thanks!
