### ISSUE TITLE
MariaDB - Temporal Data Tables feature

### ISSUE THREAD

**Issue by RipkensLar** [loopbackio/loopback-next#4705]
## Suggestion

Hi, since the loopback-connector-mysql repository has like zero activity, I am asking this here as well because we need this feature in production in the future.
My original issue: https://github.com/strongloop/loopback-connector-mysql/issues/409

I am planning on using temporal data tables with MariaDB.

## Use Cases and Examples

I am unsure if this is already implemented or possible to use, but I would expect that there would be a option to enable system versioning, for example like this:
```
@model(
  {
    settings: {
      mysql: {
        table: 'user'
      },
      system_versioning: true,
      strict: false
    }
  }
)
```

For more information, see:
https://mariadb.com/kb/en/temporal-data-tables/

I would appreciate any kind of help.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by achrinza** [comment]
@RipkensLar Thanks for the feature suggestion! I'm not too familiar with MySQL/MariaDB, but AFAIK this is a MariaDB-exclusive feature.

If that's the case, I think this (along with the other diverged features) may be a good reason for a separate MariaDB connector.

**Comment by RipkensLar** [comment]
System-versioned tables are SQL:2011 standard, but temporal data tables are MariaDB-exclusive.
