### ISSUE TITLE
feat(lb3-compat): Loopback3 compatibilty extension/package

### ISSUE THREAD

**Issue by derdeka** [loopbackio/loopback-next#4747]
## Suggestion

I suggest to create a `@loopback/lb3-compat` package to reimplement the builtin `lb3` models and behavior with `lb4` components like `interceptors` etc.

## Use Cases

To support `lb3` migrations it might be helpful to rebuild the `lb3` behavior and models in `lb4` for a faster migration path for exisiting applications. It does not make sense that each user needs to do this by going through the docs.

This could be also helpful for importing `lb3` models into `lb4`. Relates to #4737.

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@derdeka, thanks for your suggestion. For the built-in LB3 models, do you mean `User` and `ACL` models? @jannyHou is creating a extension/component for JWT authentication, so whoever trying to use JWT authentication in LB doesn't need to follow the same steps. :). See https://github.com/strongloop/loopback-next/issues/4903.  Is that something you have in mind? 

The benefit of having such extension is that it would benefit not only LB3 users who are migrating their application to LB4, but also someone who is building LB4 app from scratch.
