### ISSUE TITLE
@response(204, ... ) will not create the same type of response as schema definition.

### ISSUE THREAD

**Issue by AlexDM0** [loopbackio/loopback-next#4841]
## Current Behavior

If I want to use decorators for response, I cannot seem to get a correct 204 in the explorer.

If I use the schema definition:
```
  @post('/example', {responses: {204: { description: "Hello world"}}})
  example(
    @param.query.number("test") test : number,
  ) : void {
    // do something
  }
```

I get a clean 204 in the explorer: 
```
Code | Description | Links
-- | -- | --
204 | Hello world
```

If I use the decorator however:

```
 @post('/example')
  @response(204, {description:"Hello world"})
  example(
    @param.query.number("test") test : number,
  ) : void {
    // do something
  }
```

I get the typeselector for the response:
```
Code | Description | Links
204 | No ContentMedia typeapplication/jsonControls Accept header.Example ValueSchema(no example available)
```

Since I cannot stack the ```@response``` decorators once I use the schema as described above, I can't easily compose my responses if the default return type is 204. 

Finally, if I define no schema and no response decorator, the default return code is 200 which should be success with data instead of 204, which would make more sense if no data return type has been specified.

## Link to reproduction sandbox

This works with the simple lb4 app empty project and a controller with that endpoint. Look at the explorer to see the difference.

## Additional information

None required.

## Related Issues

I searched for 204 but I could not find anything similar.

**Comment by dougal83** [comment]
Hey @mschnee, Could you please take a look?

**Comment by achrinza** [comment]
Apologies but I'm not too sure what's the issue. The explorer is showing what has been set in the controller:

![image](https://user-images.githubusercontent.com/25147899/76511179-bea6f300-648d-11ea-99d4-ba62d7898dd7.png)

In this case, 2 things are shown:

- `test` request parameter
- `204` response `description`

## Link to reproduction sandbox

https://github.com/achrinzatest/loopback4-sandbox-4841

## Additional information

```bash
$ node -e 'console.log(process.platform, process.arch, process.versions.node)' && npm
ls --prod --depth 0 | grep loopback
win32 x64 12.16.0
loopback4-sandbox-4841@1.0.0 C:\Users\rifaa\Documents\loopback4-sandbox-4841
+-- @loopback/boot@2.0.0
+-- @loopback/context@3.0.0
npm+-- UNMET PEER DEPENDENCY @loopback/core@2.0.0
 +-- @loopback/openapi-v3@3.0.0ERR!
+-- UNMET PEER DEPENDENCY @loopback/repository@2.0.0 peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0

npm ERR!+-- @loopback/rest@3.0.0
 peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
+-- @loopback/rest-explorer@2.0.0npm
 +-- @loopback/service-proxy@2.0.0ERR!
 peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
```

**Comment by achrinza** [comment]
AFAIK, based on the [docs](https://loopback.io/doc/en/lb4/Decorators_openapi.html#oasresponse), `oas.response()` is a convenience wrapper that takes in a `Model` and auto-generates the OAS response object. As such, no other modification can be done. The docs also state that the `description` field is auto-generated:

>
> the response description to the string value in the http-status module
>

## Link to reproduction sandbox

https://github.com/achrinzatest/loopback4-sandbox-4841

## Additional information

```bash
$ node -e 'console.log(process.platform, process.arch, process.versions.node)' && npm ls --prod --depth 0 | grep loopback
win32 x64 12.16.0
loopback4-sandbox-4841@1.0.0 C:\Users\rifaa\Documents\loopback4-sandbox-4841
+-- @loopback/boot@2.0.0
+-- @loopback/context@3.0.0
+-- UNMET PEER DEPENDENCY @loopback/core@2.0.0
npm+-- @loopback/openapi-v3@3.0.0
ERR!+-- UNMET PEER DEPENDENCY @loopback/repository@2.0.0
 peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
+-- @loopback/rest@3.0.0
npm+-- @loopback/rest-explorer@2.0.0
ERR!+-- @loopback/service-proxy@2.0.0
 peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/repository@^1.16.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
npm ERR! peer dep missing: @loopback/core@^1.12.0, required by @loopback/model-api-builder@2.0.0
```

**Comment by AlexDM0** [comment]
I see you have indeed reproduced it in your sandbox. Let me know if there's anything more I can do to help out!

**Comment by achrinza** [comment]
I suspect the following may be causing the issue:

https://github.com/strongloop/loopback-next/blob/4cf24ea4b9befc6def6fb92d1785fdfd2715832d/packages/openapi-v3/src/decorators/response.decorator.ts#L48-L55

Will need to do some more digging...

I'd like to hear input from @mschnee as the author of #4550.
