### ISSUE TITLE
Better Way to Announce Breaking Changes to Help Users Find Them

### ISSUE THREAD

**Issue by agnes512** [loopbackio/loopback-next#4864]
_Inspired by https://github.com/strongloop/loopback-next/issues/4156_

We have `CHANGELOG.md` to keep track all the updates/changes. But not all users would check the files. And it doesn't remind users what changes might need to make after upgrading to new version of LB4.

We'd like to improve the way how we communicate breaking changes and make the migration guides easier to find like what we did in #4080. So that it's easier for users to find what are updated and what changes need to be done to make the old version of LB4 apps compatible with new updates.

## Acceptance Criteria

TBD

**Comment by dhmlau** [comment]
One suggestion from @raymondfeng, during our last estimation meeting, is to have the change log to aggregate all the change logs from all the packages, so that breaking changes are more easily discovered.

**Comment by dougal83** [comment]
The upgrade process could potentially be expanded in future to automatically update changes but it would be quite a lot of work!  Prior art being Angular's ng update schematics.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-next/pull/4866
