### ISSUE TITLE
API Smoke test - seems no tool available to test response matches the response format as described in OpenAPI spec 3.0 generated by Loopback 4.

### ISSUE THREAD

**Issue by vishalvisd** [loopbackio/loopback-next#4870]
As in documentation and [here ](https://github.com/strongloop/loopback-next/issues/644), dredd is the tool for doing API smoke testing but dredd doesn't support openapi 3.0 and loopback 4 doesnot generates swagger spec. In such a scenario how can we do the testing?

We are doing bottom up approach i.e., APIs have been implemented, Loopback creates the spec json/xml. Now, we want to test the APIs implementation against the spec

**Comment by emonddr** [comment]
@raymondfeng  ^

**Comment by raymondfeng** [comment]
A simple script can fetch the openapi spec, for example:

```sh
cd <project-root>
npm start
curl http://localhost:3000/openapi.json (or yaml)
```

We can possibly add a `lb4 generate-openapi-spec` command.

**Comment by emonddr** [comment]
Thanks, @raymondfeng .

https://loopback.io/doc/en/lb4/Defining-the-API-using-code-first-approach.html#reviewing-your-api-specification

mentions the openapi.json and openapi.yaml .

**Comment by emonddr** [comment]
@vishalvisd , have you tried our recommendations?

**Comment by vishalvisd** [comment]
I have edited the question title since I think the replies gave me a sense that the my query was not clear. It is no big deal to get the spec json, but the question is how can we write a test case that would validate the API response's format is matching the format described in the spec.  I had tried Dredd, but it's not working with OAS 3, and Loopback 4 doesn't generate OAS 2(swagger)

**Comment by dougal83** [comment]
Dredd has experimental support for openapi v3. Why not wait for it to mature or get involved in that project? Also can mocha testing cover the scenarios?
