### ISSUE TITLE
Auto generation while in vagrant provisioning

### ISSUE THREAD

**Issue by DanielChuDC** [loopbackio/loopback-next#4891]
## Steps to reproduce
Using Vagrant file for generic/rhel8, install npm and node, install @loopback/cli, then trying to create loopback project with cli. 

## Current Behavior
The vagrant keep telling me `Generation is aborted: SyntaxError: Unexpected end of JSON input`
and `unable to prepare context: path "loopback-example" not found`

## Expected Behavior
Expected the lb4 project generated

## Additional information
sudo npm install -g @loopback/cli -y
sudo lb4 app loopback-example -y 
> where the error pop out

**Comment by achrinza** [comment]
Hi @DanielChuDC, thanks for the report! Any reason why `sudo` is used? I'm not familiar with this specific environment but in most, it's generally not recommended to run Node.js or NPM with `sudo` privileges.

Could you try without `sudo`?

**Comment by DanielChuDC** [comment]
@achrinza I tried with no sudo too. then to prevent there is permission issue, then I added sudo. The problem persist.

**Comment by dougal83** [comment]
@DanielChuDC 
I have heard mumbles about Vagrant and filesystems in the past... Could you try `mkdir test-folder` to confirm permissions?

**Comment by emonddr** [comment]
@DanielChuDC ,

Actually, can you please more details:
1. What OS you are on 
2. What Vagrant version you are using 
3. Is it a community vagrant file or custom made vagrant file 

Thx

:)

**Comment by DanielChuDC** [comment]
@dougal83 @emonddr Thank you for your reply. 
@dougal83 I tried mkdir test-folder and it works.

@emonddr The informatino below
MacOS Catalina 10.15.3
Vagrant version Installed Version: 2.2.6
I custom made vagrant file based on  generic/rhel8.

I will upload the file soon

**Comment by dougal83** [comment]
OK, not permission issue directly then, but unfortunately I avoid macOS like the plague so I cannot help further myself. 🤷‍♂

**Comment by DanielChuDC** [comment]
Hi @emonddr and @dougal83 ,

I made a branch in my project for testing this issue.

Feel free to clone this project, checkout branch ` loopback-cli-generate`

Fulfill the prerequisite and vagrant up

The error message shown below.

<img width="1186" alt="Screenshot 2020-03-22 at 12 07 52 PM" src="https://user-images.githubusercontent.com/52316624/77242135-32878f00-6c36-11ea-834e-70d184884edf.png">

**Comment by DanielChuDC** [comment]
https://github.com/DanielChuDC/multiarch-vagrant-rhel
