### ISSUE TITLE
Extend authentication decorator to apply security to operations

### ISSUE THREAD

**Issue by dougal83** [loopbackio/loopback-next#4990]
## Suggestion

Extend [@authenticate decorator](https://loopback.io/doc/en/lb4/Decorators_authenticate.html) to apply security to operations.  Initial iteration could start with `http` authentications schemes and possibly extended to rudimentary base `apiKey` scheme implementation. A caveat is that a `securitySchemes` object must be provided by the authentication strategy.

Further expansion later for other schemes in the [auth specification docs](https://swagger.io/docs/specification/authentication/).  

Related:
#4416 feat: adds @tags convenience decorator
#4693 feat(Authentication) enable authentication strategies to contribute OASEnhancer

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Salketer** [comment]
I was looking for this. As you say #4693 allows the strategy to define the scheme to the specs. I think that every @Authenticate('strategyName') should allow the target strategy to merge its security spec to the decorated path.

**Comment by dougal83** [comment]
> Another approach to consider: introducing a new decorator `@security()` in `@loopback/openapi-v3`. This way the generated OpenAPI security spec is not coupled with the `@loopback/authentication`.

@jannyHou Personally I'd like to see both the `@security()` decorator and an extension of the `@authenticate()` functionality as described above. Negating the need to add unnecessary markup for a feature that naturally follows is a plus, especially when it is a key feature that will be used repetitively.

**Comment by deepakrkris** [comment]
@jannyHou could you please fill in the acceptance criteria for this issue ?

**Comment by nflaig** [comment]
@dougal83 what do think about extending AuthenticationStrategy with a function which allows strategies to provide the security spec and then a spec enhancer would update the openapi spec based on the authentication metadata, see [gist](https://gist.github.com/nflaig/d8b6b30d0d328eae11eefe3e4ff50dce) for a draft how this could look like
