### ISSUE TITLE
Include filter hasMany but exclude if relation empty

### ISSUE THREAD

**Issue by fikarisasi** [loopbackio/loopback-next#4995]
I have a /customers controller and get their data using this filter:
```
{
	"offset": 0,
	"limit": 10,
	"include": [{
		"relation": "demands",
		"scope": {
			"include": [{
				"relation": "item"
			}]
		}
	}]
}
```
the result is:
```
  [{
  	"name": "John",
  	"demands": [{
  		"qty": 10,
  		"item_id": 1,
  		"customer_id": 1,
  		"item": {
  			"id": 1,
  			"name": "Pasta"
  		}
  	}]
  }, {
  	"name": "Rachel"
  }]
```
I want the result that excluding Rachel because she doesn't have demands, I tried this but the result is still the same:
```
{
	"offset": 0,
	"limit": 10,
	"where": {
		"demands": {
			"neq": null
		}
	},
	"include": [{
		"relation": "demands",
		"scope": {
			"include": [{
				"relation": "item"
			}]
		}
	}]
}
```
any idea how can I achieve this?
```
  [{
  	"name": "John",
  	"demands": [{
  		"qty": 10,
  		"item_id": 1,
  		"customer_id": 1,
  		"item": {
  			"id": 1,
  			"name": "Pasta"
  		}
  	}]
  }]
```

**Comment by emonddr** [comment]
@fikarisasi , at the moment we don't support the filter you have specified above. Please read https://loopback.io/doc/en/lb4/HasMany-relation.html#querying-related-models to view the queries we do support.

In the meantime, as a workaround, in the controller method, you can always analyze  the result returned from the repository, strip out the data you don't want (result objects without `demands` property, and return this modified result set from the controller method.

**Comment by achrinza** [comment]
Loosely-related #4299

**Comment by fikarisasi** [comment]
> @fikarisasi , at the moment we don't support the filter you have specified above. Please read https://loopback.io/doc/en/lb4/HasMany-relation.html#querying-related-models to view the queries we do support.
> 
> In the meantime, as a workaround, in the controller method, you can always analyze the result returned from the repository, strip out the data you don't want (result objects without `demands` property, and return this modified result set from the controller method.

any idea how to strip out the data with the correct limit filter? I already tried to strip out the data but it doesn't return the correct limit filter. For example, if I limit the data to 10, and result objects with `demands` property are only 2, it only shows 2 result objects instead of showing 10 data. This is wrong since I use skip and limit filter for pagination in the client-side.

**Comment by RuslanUshakov** [comment]
Any updates?

**Comment by RuslanUshakov** [comment]
@emonddr If you try to filter data by related models and use limit it does not work properly. 
For instance here is the filter:
`{
  "limit": 5,
  "offset": 0,
  "where": {},
  "order": [
    "id asc"
  ],
  "include": [
    {
      "relation": "site",
      "scope": {
        "where": {
          "name": {
            "like": "%mysite%"
          }
        }
      }
    }
  ]
}`

`mysite` is the 7th item. But i cannot get it since i have limit 5. I just receive first 5 items without relations.
