### ISSUE TITLE
Partial patch not working as expected

### ISSUE THREAD

**Issue by bluewayll** [loopbackio/loopback-next#5074]
Hello guys,

Referring to this bug :
https://github.com/strongloop/loopback-next/issues/4938

After updating my packages i can now do a partial patch with partial verification but not as expected.

## Steps to reproduce

With : 

`schema: getModelSchemaRef(Product, {partial: 'deep'})`

Patch this object : 

`{ name: "test name", image: { link: "test link", description: "test description" } }`

With : 

`{ image: { description: "test description 2 2 2 2" } }`

## Current Behavior

Result : 

`{ name: "test name", image: { description: "test description 2 2 2 2" } }`

## Expected Behavior

Result : 

`{ name: "test name", image: { link: "test link", description: "test description 2 2 2 2" } }`

## Additional information

`linux x64 10.16.3`

`├── @loopback/boot@2.0.3
├── @loopback/context@3.3.0
├── @loopback/core@2.2.1
├── @loopback/openapi-v3@3.1.2
├── @loopback/repository@2.1.0
├── @loopback/rest@3.2.0
├── @loopback/rest-explorer@2.0.3
├── @loopback/service-proxy@2.0.3
├── @packages/loopback-connector-couchbase@1.0.11
├── loopback-connector-rest@3.6.0
`

## Related Issues

https://github.com/strongloop/loopback-next/issues/4938

**Comment by dhmlau** [comment]
@jannyHou, perhaps this is related to something you're investigating now?

cc @agnes512

**Comment by raymondfeng** [comment]
@bluewayll What database do you use? I don't think our default repository implementation supports deep patching.

**Comment by bluewayll** [comment]
@raymondfeng I am using couchbase as a database.

**Comment by fidgi** [comment]
FYI, we implement a workaround using [json8-merge-patch](https://github.com/sonnyp/JSON8/tree/master/packages/merge-patch). In summary, we merge the PATCH request body (rfc7396 compliant) into the target document and pass the result to the repository.

**Comment by a3diti** [comment]
the `partial: 'deep'` is non-functional at all, i am going to try [json8-merge-patch](https://github.com/sonnyp/JSON8/tree/master/packages/merge-patch)

**Comment by a3diti** [comment]
@dhmlau It should be considered to patch an array using only the selected array item number, it can be helpful for small operations
