### ISSUE TITLE
getModelSchemaRef with exclude on property 

### ISSUE THREAD

**Issue by Listu** [loopbackio/loopback-next#5134]
## Steps to reproduce

Use getModelSchemaRef with properties in the requestBody's schema and exclude some properties in the getModelSchemaRef.

ex:

`@requestBody({
  content: {
    'application/json': {
      schema: {
        properties: {
          workspace: getModelSchemaRef(Workspace, { exclude: ['id']}),
          userId: {
            type: 'string',
          }
        }
      }
    },
  },
})`

## Current Behavior

Only userId will appear in the OpenAPI explorer.

**Comment by dhmlau** [comment]
@Listu, could you please provide more information on how your `@requestBody` decorator look like? The above snippet doesn't seem to be complete? 

Please also take a look at https://github.com/strongloop/loopback-next/blob/master/examples/todo/src/controllers/todo.controller.ts#L37-L46 on the use of `getModelSchemaRef`. Thanks.

**Comment by dhmlau** [comment]
Better yet, if you have a sample app to help us to reproduce the problem, that would be great. Thanks.

**Comment by Listu** [comment]
@dhmlau the decorator is complete.

Simpler case without the userId:

`@requestBody({
      content: {
        'application/json': {
          schema: {
            properties: {
              workspace: getModelSchemaRef(Workspace, {exclude: ['id']})
            }
          }
        },
      },
    })
    body: any`

Only `{}` is displayed in the Example Value of the route.

If I remove exclude, it works and I get in the Example Value:

`{
  "workspace": {
    "id": "string",
    "name": "string",
    "status": "string",
    "roleIds": [
      "string"
    ],
    "entityIds": [
      "string"
    ],
    "groupIds": [
      "string"
    ]
  }
}`
