### ISSUE TITLE
Automatically determine response status code from @oas.response decorator.

### ISSUE THREAD

**Issue by mschnee** [loopbackio/loopback-next#5149]
## Suggestion
The `@oas.response` convenience decorator lets us easily decorate controller methods .
However, as the developer, you are still responsible for setting the response code if you aren't going to return a default `200` status:

```ts
class MyController {
  @response(200, SuccessModel, AnotherSuccessModel)
  @response(409, MessageTooSmallModel)
  @get('/echo/{message}')
  public async echoMessage(
    @param.path.string('message') message?: string,
    @inject(RestBindings.Http.RESPONSE) res: Response
  ) {
    if (message.length < 15) {
      res.status(409)
      return new MessageTooSmallModel({message: 'minimum length is 15 characters'});      
    } else {
      return new SuccessModel({message});
    }
  }
}
```

While not necessarily inclusive of all possible response models, it is a safe assumption:
- if the developer decorated a path method with `@response(someCode, SomeModel, SomeOtherModel)`, 
- and the invocation of that path method responds with- or throws- an instance of `SomeModel` or `SomeOtherModel`, 
- then the developer intended to set the response status to be `someCode`

## Questions 
- Where would this go?
- Is this something that can be configured by adding an optional extension in a given RestApplication?
- Is the best place for this lookup inside of the Sequence handler?  
- And if so,  is the implementation a simple function that gets called on demand in the try/catch blocks of a sequence handler?

## Acceptance Criteris
TBD

**Comment by dhmlau** [comment]
@jannyHou, could you please take a look? Thanks.

**Comment by mschnee** [comment]
Additional thoughts- if a developer invokes `res.status()`, that should be authoritative, and nothing should change that.

**Comment by deepakrkris** [comment]
moving to backlog, will assign target milestone in estimation meeting
