### ISSUE TITLE
Schema migration not working with BindingScope.TRANSIENT

### ISSUE THREAD

**Issue by matte23n** [loopbackio/loopback-next#5243]
Hi, i had to put the annotation `@bind({scope: BindingScope.TRANSIENT})` over my Datasource class, i figured out that the `app.migrateSchema()` is not working with this annotation in place... is this a bug or is there a reason for it not working?
Thanks

**Comment by deepakrkris** [comment]
@matte23n can you please post a code sample here

**Comment by matte23n** [comment]
Yeah bro, this is what I have in my postgres.datasource.ts:

`@bind({scope: BindingScope.TRANSIENT})
@lifeCycleObserver('datasource')
export class PostgresDataSource extends juggler.DataSource
....`

And in my index.ts i'm doing `await app.migrateSchema();`

The problem is that with the annotation `@bind({scope: BindingScope.TRANSIENT})` the schema migration is not working, if i comment that all works nicely
