### ISSUE TITLE
Add `lb4 openapi --test` to generate integration tests from openapi specs

### ISSUE THREAD

**Issue by raymondfeng** [loopbackio/loopback-next#5399]
## Suggestion

- Add `--test` option to `lb4 openapi` command to generate integration tests from an openapi spec. The tests are similar as https://github.com/strongloop/loopback-next/blob/master/examples/todo/src/__tests__/acceptance/todo.acceptance.ts.

## Examples

```sh
lb4 openapi --test --url todo-openapi.json
```

## Acceptance criteria

- Implement `--test` code generation as well as tests
- Document `--test` option

**Comment by fidgi** [comment]
:+1:  I vote for this one. It would be of a great help for us.
