### ISSUE TITLE
Update list of lb4 connector

### ISSUE THREAD

**Issue by JacquesBonet** [loopbackio/loopback-next#5416]
## Steps to reproduce

In this lb4 documentation page https://loopback.io/doc/en/lb4/Community-connectors.html,
are listed communities connectors.

## Current Behavior

Unfortunatly, not all these connectors are not compatible with lb4.

## Expected Behavior

List only lb4 compatible connector

**Comment by dhmlau** [comment]
@JacquesBonet, thanks for bringing this up. We probably need to revisit this page.
Is there any connectors that you know that won't work with LoopBack 4? If so, would you like to submit a PR to remove it? Thanks.

**Comment by JacquesBonet** [comment]
Ok for the PR

**Comment by dhmlau** [comment]
Thanks. Let me assign this issue to you then.
