### ISSUE TITLE
[eslint] Improve code base with explicit return type

### ISSUE THREAD

**Issue by raymondfeng** [loopbackio/loopback-next#5532]
## Suggestion

As part of typescript-eslint v3 upgrade, we disable the following rule:

```
// Disable warning  Missing return type on function for now
'@typescript-eslint/explicit-module-boundary-types': 'off',
```

See https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md

https://github.com/strongloop/loopback-next/pull/5513#discussion_r429055531

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Arathy-sivan** [comment]
What is the difference between eslint and vscode feature in loopback4 ?
$ lb4 app
? Project name: todo-list
? Project description: A todo list API made with LoopBack 4.
? Project root directory: (todo-list)
? Application class name: (TodoListApplication)
? Select features to enable in the project:
 ◉ Enable eslint: add a linter with pre-configured lint rules
 ◉ Enable prettier: install prettier to format code conforming to rules
 ◉ Enable mocha: install mocha to run tests
 ◉ Enable loopbackBuild: use @loopback/build helpers (e.g. lb-eslint)
 ◉ Enable vscode: add VSCode config files
 ◉ Enable docker: include Dockerfile and .dockerignore
 ◉ Enable repositories: include repository imports and RepositoryMixin
 ◉ Enable services: include service-proxy imports and ServiceMixin
 # npm will install dependencies now
 Application todo-list was created in todo-list.

**Comment by bajtos** [comment]
@Arathy-sivan 
> What is the difference between eslint and vscode feature in loopback4 ?

Your question is off-topic here. Please post your question to [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50) or [Slack chat](
(https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw)
