### ISSUE TITLE
Create model instance from plain-data object at controller methods

### ISSUE THREAD

**Issue by fenixsolorzano** [loopbackio/loopback-next#5572]
## Suggestion

When method hits with a request body we can set it to have a model type, but in the method body the model is just plain-data object.

## Use Cases

Since models are classes I'd like to create computed properties for the model like getters, and also have functions to calculate stuff based on the properties that the class has.

## Examples

```ts
@post('/cards/')
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Card, {
            title: 'Card'
          }),
        },
      },
    })
    card: Card,
  ): Promise<CardResponse> {
    // Trying to access a computed property of Card form `card` variable is no possible here
    console.log(card.computedGetProperty) //outputs undefined
  }
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by InvictusMB** [comment]
This looks more like a bug to me. If I expect a `Card` instance, I should get a `Card` instance not a POJO.
Otherwise the definition should say something like `card: Raw<Card>`

But for now, wouldn't `new Card(card).computedGetProperty()` do the job for you?

**Comment by fenixsolorzano** [comment]
Yeah @InvictusMB I did that

**Comment by dhmlau** [comment]
Does this docs page provide something you're looking for? https://github.com/strongloop/loopback-next/blob/master/docs/site/Dynamic-models-repositories-controllers.md

**Comment by hacksparrow** [comment]
Requirement is not very clear to me.

**Comment by InvictusMB** [comment]
@hacksparrow 
The issue is that an object passed to the controller method does not match the signature of that method. In the example above we have a `Card` in the signature but get a plain JS object of a similar shape instead of a `Card` class instance.

This is somewhat related to #2707

**Comment by jannyHou** [comment]
Thank you @InvictusMB seems this story is asking for the same feature as #2707. @fenixsolorzano do you mind if we move all the discussion there? (trying to keep the backlog smaller)
