### ISSUE TITLE
Implement REST/OpenAPI functionality as an extension

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-next#5697]
As discussed in https://github.com/strongloop/loopback-next/pull/5545#issuecomment-640717051, let's extract the REST/OpenAPI parts from `src/packages` to an extension.

This will involve creating a new HTTP Application package in place of the current `src/packages/rest` package, mostly by trimming down and making some modifications to the existing code. The extracted code with some modifications would become the REST/OpenAPI extension and will be located at `extensions/rest`.

Since LoopBack will be using the new HTTP Application package and the new extension would still be named `@loopback/rest`, this will be a breaking change and will require a major release.

## Acceptance Criteria

- [ ] Create a general-purpose HTTP Application package.
- [ ] Move out `src/packages/rest-crud` to `extensions/rest-crud`.
- [ ] Move out `src/packages/rest-explorer` to `extensions/rest-explorer`.
- [ ] Extract the REST/OpenAPI-specific parts from `src/packages/rest` and implement as an extension.
- [ ] The new HTTP Application should be able to bind the REST/OpenAPI extension to re-create all of the existing REST/OpenAPI functionality.
- [ ] Update all documentation involving `@loopback/rest` to reflect the state of the updated architecture and codebase.
- [ ] Document the new REST/OpenAPI extension in detail (this will solve many of the current documentation issues).

**Comment by dhmlau** [comment]
This will also the CLI template, at least for `lb4 app`.

**Comment by raymondfeng** [comment]
> Create a general-purpose HTTP Application package.
 
We should probably expand `@loopback/express` to be a general purpose `ExpressServer`, which contains a middleware based sequence to handle common http req/res processing, such as CORS, Helmet, Caching, Access Logging, ...

> Move out src/packages/rest-crud to extensions/rest-crud.
> Move out src/packages/rest-explorer to extensions/rest-explorer.

It's not necessary. An extension is a logic concept. Theses two packages can stay in `packages`.

> Extract the REST/OpenAPI-specific parts from src/packages/rest and implement as an extension.

The `RestServer` can extend from `ExpressServer` by contributing additional middleware/action, such as `FindRoute`, `ParseParams`, and `InvokeMethod` to handle OpenAPI based routes/controllers. 

> The new HTTP Application should be able to bind the REST/OpenAPI extension to re-create all of the existing REST/OpenAPI functionality.

Yes, the sequence can be extended with more REST/OpenAPI middleware/actions.

> Update all documentation involving @loopback/rest to reflect the state of the updated architecture and codebase.

The `@loopback/rest` should stay. We just need to expand `@loopback/express` to be the base for HTTP based protocols.

> Document the new REST/OpenAPI extension in detail (this will solve many of the current documentation issues).

+1.

**Comment by raymondfeng** [comment]
Here is what I see:

1. The base `ExpressServer` backed by `HttpServer. Its primary function is a chain of middleware. Business logic can be added in the form of route handlers. We can have a `ExpressApplication` to combine `Application` and `ExpressServer`.

2. The `RestServer` extends `ExpressServer` with additional middleware - FindRoute, ParseParams, and InvokeMethod. `RestApplication` continues to be `Application + RestServer`.

3. The `GraphQLServer` extends `ExpressServer` with the resolver middleware that routes GraphQL requests to application level resolvers.

**Comment by bajtos** [comment]
The proposal described in https://github.com/strongloop/loopback-next/issues/5697#issuecomment-642375568 looks reasonable to me.

We need to find a way how to make this changes incrementally and keep the required effort small. We need to invest to our efforts into improving our documentation and getting closer to feature parity with LB3 this year. With our limited resources, there is only little time available for big refactorings.
