### ISSUE TITLE
CRUD repository functions return different ID formats with MongoDB as datasource

### ISSUE THREAD

**Issue by nflaig** [loopbackio/loopback-next#5733]
This bug seems to be specific to MongoDB in combination with the default crud repository. The crud repository tests do not catch this because the tests only use either stubs or a in-memory data source.

## Steps to reproduce

The issue can be reproduced by using the default crud repository with MongoDB as data source.

Example code snippet

```ts
it("should return the same user model instance for create and find", async () => {
    const createdUser = await userRepository.create(givenUser());
    const foundUser = await userRepository.findById(createdUser.id);

    // this test does not pass due to different id format
    expect(createdUser).to.deepEqual(foundUser);
});
```

## Current Behavior

The entity id returned from `repository.create` is a `ObjectID` and the entity id returned from `repository.find` is a `string`.

## Expected Behavior

The entity id should have the same format and the test shown in the code snippet should pass.

## Additional information

Entity id as ObjectID example:

![image](https://user-images.githubusercontent.com/38436224/84578964-399fe280-adca-11ea-8a69-dc2ada5cff99.png)

Entity id as string example:

![image](https://user-images.githubusercontent.com/38436224/84578973-550aed80-adca-11ea-9362-91eedf1f7ab4.png)

**Comment by dhmlau** [comment]
We might need to set `strictObjectIDCoercion: true` here. 
```
@model({settings: {
  strictObjectIDCoercion: true
}})
export class User extends Entity {
}
```

See https://loopback.io/doc/en/lb4/MongoDB-connector.html#handling-objectid.

**Comment by nflaig** [comment]
When setting `strictObjectIDCoercion: true` it returns a string for both created and found entities. However, `const foundUser = await userRepository.findById(createdUser.id);` does not work anymore, it does not find the user.

I feel like the best would be to only deal with strings as ids and never return ObjectIds and let the repository/connector handle conversion if required.

One thing to add is that I only noticed the issue after updating lb4 dependencies before that all `deepEqual` tests of entities were passing.
