### ISSUE TITLE
[Docs] Create a comparison between Loopback 4 and other popular frameworks

### ISSUE THREAD

**Issue by mitsos1os** [loopbackio/loopback-next#5760]
## Suggestion

A blog post (as suggested in [#630](https://github.com/strongloop/loopback-next/issues/630))  or a framework comparison table that showcases the differentiating factors and why should someone choose LB4 instead of other popular frameworks.

## Use Cases

So what is it that makes LB4 different than the other frameworks? Having a side by side comparison with other popular frameworks, will help newcomers understand what is offered from LB4 and possibly hint them to the right direction which is not obvious from the start. Also feature comparison like all in one functionality such authentication - authorization, existence of common CRUD interface for all supported DB's out of the box, integrated ORM etc...

Related to #5113

## Examples

Basic example could be: https://loopback.io/lb3/resources#compare However I think it should go in a little bit deeper

**Comment by dhmlau** [comment]
FWIW, we have a blog post explaining LoopBack can be a good choice for Express developers: https://strongloop.com/strongblog/express-to-loopback/. It's not from the angle as https://loopback.io/lb3/resources#compare because it's not a fair comparison. 

Personally, I agree that it's a good idea to have such comparison.

**Comment by HrithikMittal** [comment]
Hey @dhmlau Can you suggest some frameworks with them. I can compare it and write a blog over it.Thanks

**Comment by mitsos1os** [comment]
@HrithikMittal You can check out NestJS, FeathersJS, AdonisJS

**Comment by zenVentzi** [comment]
Trying to pick a new framework for our team. Any news? Most interested in comparison between LP4 and Nest.js

**Comment by raymondfeng** [comment]
@zenVentzi You should check out https://stackshare.io/stackups/loopback-vs-nestjs#:~:text=Developers%20describe%20LoopBack%20as%20%22Build,with%20little%20or%20no%20coding.&text=On%20the%20other%20hand%2C%20NestJS,detailed%20as%20%22A%20progressive%20Node and https://stackoverflow.com/questions/60948693/nestjs-vs-loopback-4
