### ISSUE TITLE
[Demo] Provide official implementation of realword.io

### ISSUE THREAD

**Issue by mitsos1os** [loopbackio/loopback-next#5762]
## Suggestion

Provide an official implementation of the popular [realword](https://realworld.io/) example with Loobpack 4 using best practices as showcased from the documentation.

## Use Cases

I understand that this could be considered achieved by the [shopping-example](https://github.com/strongloop/loopback4-example-shopping). However, being able to see exactly the same spec being implemented by different frameworks is a very good helper in demonstrating the framework capabilities and also act as a guide for people to switch over from other frameworks.

**Comment by dhmlau** [comment]
That's an interesting idea! It would be good to see the community taking this challenge. :)

**Comment by alcmontejo** [comment]
looks interesting, I'l explore this weekend.. :)

**Comment by raymondfeng** [comment]
Some thoughts on how to jump start the effort:

- Use `lb4 app` to scaffold the backend application
- Use `lb4 openapi` to generate controllers and models against `https://github.com/gothinkster/realworld/blob/master/api/swagger.json`
- Use `lb4 datasource` to add a DB
- Use `lb4 repository` to bind models to the DB
- Add security layer with JWT

**Comment by alcmontejo** [comment]
thanks for the pointers,.
