### ISSUE TITLE
[API docs] Provide more tsdocs for methods in DefaultCRUDRepository

### ISSUE THREAD

**Issue by jannyHou** [loopbackio/loopback-next#5804]
## Suggestion

We should add more detailed tsdocs for CRUD operations in `DefaultCrudRepository`

## Examples

For example, method update:
https://github.com/strongloop/loopback-next/blob/8701cce8b208c952e4d41f0570124e389506d808/packages/repository/src/repositories/legacy-juggler-bridge.ts#L433

The API doc would be:

Specify the new data as the 1st param(entity). This method infers entity id from the new data and performs update on the corresponding record.

For example:

old data: `{id:1, name: ‘loopback’, city: ‘trt’}`
new data: `{id: 1, name: ‘loopback’, city: ‘nyc’}`
Run `update(new <ModelName>({id: 1, city: 'nyc'}))` to update the instance.

## Acceptance criteria

- [ ] Update the API docs for CRUD operators.

**Comment by madaky** [comment]
> Run update(new Data({id: 1, city: 'nyc'})) 

IMO, this should be more precise to

`
update(new <ModelName>(<Updated Model Properties>));
`
