### ISSUE TITLE
Configure showCommonExtensions property for SwaggerUI

### ISSUE THREAD

**Issue by shnplr** [loopbackio/loopback-next#5810]
## Suggestion

I would like to be able to enable the `showCommonExtensions` property as documented [https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/](url)

## Use Cases

To provide additional information to API consumers about request parameters

## Examples

```
const ui = SwaggerUIBundle({
        url: '<%- openApiSpecUrl %>',
        dom_id: '#swagger-ui',
        deepLinking: true,
        showCommonExtensions: true,
...
      })
```

## Acceptance criteria

- [ ] Add `showCommonExtensions` as the template variables in 
        https://github.com/strongloop/loopback-next/blob/695ba58fda37763467c07016bdaa15a7399cd0e6/packages/rest-explorer/templates/index.html.ejs#L40

- [ ] `showCommonExtensions` can be configured via [RestExplorer](https://loopback.io/doc/en/lb4/Self-hosted-rest-api-explorer.html#basic-use)

```ts
this.configure(RestExplorerBindings.COMPONENT).to({
  showCommonExtensions: true,
});
```

**Comment by jannyHou** [comment]
@shnplr Thanks for the suggestion, we can enable it through the template parameter in https://github.com/strongloop/loopback-next/blob/695ba58fda37763467c07016bdaa15a7399cd0e6/packages/rest-explorer/templates/index.html.ejs#L40
