### ISSUE TITLE
Cannot read property "match" of undefined when running "lb4 openapi ...."

### ISSUE THREAD

**Issue by argupta23** [loopbackio/loopback-next#5936]
When running the following command

`
lb4 openapi ~/sigfox_api_v2.json --validate
`

I get the following error

`Loading /home/argxxx/sigfox_api_v2.json...
Generation is aborted: TypeError: Cannot read property 'match' of undefined`

using the file as is from the link
[https://sigfox-api.ingeniousthings.fr/v2/api-docs?group=1-sigfox-api-v2](url)

[https://support.sigfox.com/apidocs](url)

I also tried loading the file into Swagger Editor and it seems to load fine.

I exported a copy of the same as "JSON" and "YAML"  Swagger V2 and ran the commands again which yields the same error

I then exported the file as Swagger OpenApiV3 and it yielded the following error

`Loading /home/argupta/sigfox_apiv2_openapiv3.json...
Generation is aborted: SyntaxError: Error resolving $ref pointer "/home/argupta/sigfox/apiv2/swagger/testv2/#/definitions/commonDevice".
`

Is there a way in lb4 where I can get more information on what seems to be wrong in the file?

Appreciate any help and guidance in getting this resolved.

Thanks

**Comment by raymondfeng** [comment]
The links don't work for me. It seems that a `$ref` with `#/definitions/commonDevice` cannot be resolved. Do you have `commonDevice` schema under `definitions`?

**Comment by argupta23** [comment]
@raymondfeng,

Thanks for the the quick turnaround. 

Yes, I did check that the reference to the #/definitions/commonDevice does exist. 

I am attaching a zipped version of the file to see if you can check if it is an issue with the file or some issue within loopback-next. see attached file called jsonandyaml.zip

"$ref": "#/components/schemas/commonDevice"
Within the yaml file it is referenced at line 9157 
within the json file it is referenced at 11683

is there any debugging I can turn on to help you with?
[jsonandyaml.zip](https://github.com/strongloop/loopback-next/files/4921746/jsonandyaml.zip)

Appreciate any help getting this resolved. 

BTW, I am not sure why the links don't open up when clicked, but one could copy the url and paste it into a new tab and it should work. I am doing something wrong during the edit, please let me know and I will correct myself.

**Comment by raymondfeng** [comment]
Line 9157 of the yaml:

```yaml
- $ref: '#/definitions/commonDevice'
```

This is a dangling reference. It should be:
```yaml
- $ref: '#/components/schemas/commonDevice'
```

**Comment by argupta23** [comment]
@raymondfeng 

Thank you for the pointer, after correcting that I found 5 other instances in the file that I had to replace. With that fixed I am back to square one
[sigfox_openapiv3.zip](https://github.com/strongloop/loopback-next/files/4921942/sigfox_openapiv3.zip)

`lb4 openapi ~/sigfox_apiv2_openapiv3.yaml --validate
Loading /home/argupta/sigfox_apiv2_openapiv3.yaml...
Generation is aborted: TypeError: Cannot read property 'match' of undefined
`

Is there a way to add mode verbose within the lb4  set of commands to get more details?

I am attaching the updated file that has the other corrections.

**Comment by raymondfeng** [comment]
You can set env var `DEBUG` to loopback:cli:* to see the stack trace.

**Comment by argupta23** [comment]
@raymondfeng 

I enabled the trace as you suggested and below is the output.

`  loopback:cli:base-generator TypeError: Cannot read property 'match' of undefined
  loopback:cli:base-generator     at escapeIdentifier (/usr/lib/node_modules/@loopback/cli/generators/openapi/utils.js:159:13)
  loopback:cli:base-generator     at getMethodName (/usr/lib/node_modules/@loopback/cli/generators/openapi/spec-helper.js:146:35)
  loopback:cli:base-generator     at buildMethodSpec (/usr/lib/node_modules/@loopback/cli/generators/openapi/spec-helper.js:198:22)
  loopback:cli:base-generator     at /usr/lib/node_modules/@loopback/cli/generators/openapi/spec-helper.js:425:7
  loopback:cli:base-generator     at Array.map (<anonymous>)
  loopback:cli:base-generator     at buildControllerSpecs (/usr/lib/node_modules/@loopback/cli/generators/openapi/spec-helper.js:424:47)
  loopback:cli:base-generator     at generateControllerSpecs (/usr/lib/node_modules/@loopback/cli/generators/openapi/spec-helper.js:441:10)
  loopback:cli:base-generator     at loadAndBuildSpec (/usr/lib/node_modules/@loopback/cli/generators/openapi/spec-loader.js:63:27)
  loopback:cli:base-generator     at async OpenApiGenerator.loadAndBuildApiSpec (/usr/lib/node_modules/@loopback/cli/generators/openapi/index.js:236:22) +1s`

enabling some console log within spec-helper I was able to figure out what was causing the issue.

Thanks again for all your help and guidance.

argupta

**Comment by argupta23** [comment]
@raymondfeng @bajtos 

Sorry I need to reopen this issue.

I am using the latest version of Lb4 and I re-ran the "lb4 openapi" on the previously attached swagger file.
I was able to generate the appropriate models and controllers from that file.
Then I added a "mongodb" datasource and ran "lb4 repository" via command line on one of the models

It did create the repository for that model, but when I tried to start the program I ran into the following errors

```
src/repositories/device.repository.ts:7:3 - error TS2344: Type 'Device' does not satisfy the constraint 'Entity'.
  Type 'Device' is missing the following properties from type 'Entity': getId, getIdObject, toJSON, toObject

7   Device,
    ~~~~~~

src/repositories/device.repository.ts:14:11 - error TS2345: Argument of type 'typeof Device' is not assignable to parameter of type 'typeof Entity & { prototype: Device; }'.
  Type 'typeof Device' is missing the following properties from type 'typeof Entity': getIdProperties, getIdOf, buildWhereForId, modelName, definition

14     super(Device, dataSource);
             ~~~~~~
```

The generated "Device.model.ts" contains

```
import {model, property} from '@loopback/repository';
import {ObjectId} from './object-id.model';

/**
 * The model class is generated from OpenAPI schema - Device
 * Device
 */
@model({name: 'Device'})
export class Device {
  constructor(data?: Partial<Device>) {
    if (data != null && typeof data === 'object') {
      Object.assign(this, data);
    }
  }

  @property({
    required: true, jsonSchema: {
      type: 'string',
    }
  })
  id: string;

  @property({
    jsonSchema: {
      minimum: 32,
      maximum: 32,
      pattern: '([a-fA-F0-9]{32})$',
      type: 'string',
    }
  })
  pek?: string;

  @property({
    jsonSchema: {
      type: 'string',
    }
  })
  name?: string;

  @property({
    jsonSchema: {
      minimum: 16,
      maximum: 16,
      pattern: '([a-fA-F0-9]{16})$',
      type: 'string',
    }
  })
  data_downlink?: string;

  @property({
    jsonSchema: {
      $ref: '#/components/schemas/ObjectID',
    }
  })
  userId?: ObjectId;

}

export interface DeviceRelations {
  // describe navigational properties here
}

export type DeviceWithRelations = Device & DeviceRelations;
```
The generated "Device.repository.ts" contains

```
import {DefaultCrudRepository} from '@loopback/repository';
import {Device, DeviceRelations} from '../models';
import {MongodbDataSource} from '../datasources';
import {inject} from '@loopback/core';

export class DeviceRepository extends DefaultCrudRepository<
  Device,
  typeof Device.prototype.id,
  DeviceRelations
> {
  constructor(
    @inject('datasources.mongodb') dataSource: MongodbDataSource,
  ) {
    super(Device, dataSource);
  }
}
```

searching for the issue, I came across #2058 which suggested that I update the model file to read as

```
import {Entity, model, property} from '@loopback/repository';
import {ObjectId} from './object-id.model';

/**
 * The model class is generated from OpenAPI schema - Device
 * Device
 */
@model({name: 'Device'})
export class Device extends Entity{
  constructor(data?: Partial<Device>) {
    // if (data != null && typeof data === 'object') {
    //   Object.assign(this, data);
    // }
    super(data)
  }

```
This allowed me to get around the error.

Is this a bug in the openapi generator or something else?

Can I please request your help to look into this matter?
