### ISSUE TITLE
Add foreign key discover with `lb4 discover`

### ISSUE THREAD

**Issue by mathias22osterhagen22** [loopbackio/loopback-next#6002]
## Suggestion

Actually, to perform an `lb4 discover --schema mytable` works well but unfortunately, it doesn't generate the foreign key settings (it doesn't include the "belongs too" or "hasMany" but to me, it's still ok to manage it by ourselves to avoid problems).

Like instead of this: 
![image](https://user-images.githubusercontent.com/60438474/88384791-5fe37580-cdad-11ea-910a-7999b17a2e9e.png)

Detect the foreign key and their name and insert them into the model settings : 
![image](https://user-images.githubusercontent.com/60438474/88384825-712c8200-cdad-11ea-8629-fa2dfa9e20fb.png)

## Use Cases

To discover table and setup model(s) without having to manually set the foreign key one by one into the models (I'm currently working on a huge database and have to insert hundred of them manually :'( ).

## Examples

Should be enabled by default and be disabled by a flag like `lb4 discover --no-foreign-key` 

## Acceptance criteria

TBD - will be filled by the team.

**Comment by mbnoimi** [comment]
+1
Foreign key generation is very vital feature, I'm very excited to see it available in lb4.

**Comment by mbnoimi** [comment]
BTW, I was using Django inspectdb but when I left Django I missed it a lot.
