### ISSUE TITLE
Model boolean property with default value not translated into DB

### ISSUE THREAD

**Issue by amzac-rait** [loopbackio/loopback-next#6051]
## Steps to reproduce

DB is MariaDB 10
Create a simple entity with a boolean property :
```  
  @property({
    type: 'boolean',
    default: true
  })
  isCallable?: boolean;
```

Execute migration

## Current Behavior

In database, default value is still NULL
(if default is set to `false`, it's also NULL)

## Expected Behavior

Default value in database should reflect the annotated model

## Additional information

Note that I've worked around the issue and found that :
This does not work  
```
  @property({
    type: 'boolean',
    default: 'true',
  })
  isCallable?: boolean;
```

This does not work either :
```
  @property({
    type: 'boolean',
    default: true,
     mysql: {
       default: 1
     }
  })
  isCallable?: boolean;
```

But this works :
```
  @property({
    type: 'boolean',
    default: true,
    mysql: {
      default: '1'
    }
  })
  isCallable?: boolean;
```

Have a good day

**Comment by agnes512** [comment]
Hey, there is similar question https://github.com/strongloop/loopback-next/issues/5899#issuecomment-668789293
As for your case, for the database to have the default value defined, it would be 
```ts
  @property({
    type: 'boolean',
    mysql: {
      dataType: 'boolean',
      default: 1
    }
  })
  isCallable?: boolean;
```
in the db:
```
+------------+--------------+------+-----+---------+----------------+
| Field      | Type         | Null | Key | Default | Extra          |
+------------+--------------+------+-----+---------+----------------+
| id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| name       | varchar(512) | NO   |     | NULL    |                |
| isCallable | tinyint(1)   | YES  |     | 1       |                |
+------------+--------------+------+-----+---------+----------------+
```
I will update the [corresponding docs](https://loopback.io/doc/en/lb4/MySQL-connector.html#default-clauseconstant) shortly.

**Comment by amzac-rait** [comment]
Alright, I'll use your annotation.
Thanks for your feedback

**Comment by amzac-rait** [comment]
@agnes512 

Using your annotation, I still have to set the "default" property as a string ( `default: '0'` ) to make it work. 

Forgot to mention some package.json info 

```
    "@loopback/core": "^2.9.2",
    "@loopback/openapi-v3": "^3.4.6",
    "@loopback/repository": "^2.10.0",
    "loopback-connector-mysql": "^5.4.4",
```

Hope it can help

**Comment by agnes512** [comment]
I was using MySQL, not sure if it's the same as MariaDB D:
