### ISSUE TITLE
CLI v2.12.0: lb4 model command with model name argument HANG 

### ISSUE THREAD

**Issue by alcmontejo** [loopbackio/loopback-next#6078]
## Steps to reproduce

1. Update CLI to @loopback/cli version: 2.12.0
2. Create new APP
3. Create new Model with additional model name argument
`$ lb4 model [<name>]`

## Current Behavior

CLI will not proceed and appears to be  HANG.

## Expected Behavior

CLI should proceed with the selection of model base class

## Link to reproduction sandbox

Can be reproduced in any existing lb4 sample app

## Additional information

> node -e 'console.log(process.platform, process.arch, process.versions.node)'

win32 x64 12.18.3

> npm ls --prod --depth 0 | grep loopback

@loopback/example-todo@3.7.0 C:\projects\open-source\loopback4-example-todo
+-- @loopback/boot@2.4.1
+-- @loopback/core@2.9.3
+-- @loopback/repository@2.11.0
+-- @loopback/rest@6.0.0
+-- @loopback/rest-explorer@2.2.8
+-- @loopback/service-proxy@2.3.6
+-- loopback-connector-rest@3.7.0

## Related Issues

lb4 command hangs: https://github.com/strongloop/loopback-next/issues/3187

**Comment by alcmontejo** [comment]
kindly label as `CLI` tnx

**Comment by alcmontejo** [comment]
btw, not reproducible in MAC using below:

> node -e 'console.log(process.platform, process.arch, process.versions.node)'

darwin x64 10.16.3

> npm ls --prod --depth 0 | grep loopback

@loopback/example-todo@3.7.0 ***/loopback4-example-todo
├── @loopback/boot@2.4.1
├── @loopback/core@2.9.3
├── @loopback/repository@2.11.0
├── @loopback/rest@6.0.0
├── @loopback/rest-explorer@2.2.8
├── @loopback/service-proxy@2.3.6
├── loopback-connector-rest@3.7.0

**Comment by dhmlau** [comment]
@alcmontejo, which node.js version are you on? 
I just tried with my Windows 10 machine with Node.js 12.14.1 (using nvm), it seems to be working fine. 

I ran `lb4 app` and then `lb4 model` to create new app and then new model.

**Comment by alcmontejo** [comment]
@dhmlau  yep it works for me w/out the 3rd argument (name of the object). However, when I supply the model name in initial command `lb4 model [<name>]` that where it hangs. 

Im on nodejs `v12.18.3`

**Comment by dhmlau** [comment]
You're right! `lb4 model` works but `lb4 model <name>` not. I was able to reproduce it on Windows but not Mac. 
Not sure if it's related to `inquirer` like last time. @agnes512, could you please take a look? Thanks.
