### ISSUE TITLE
rest-crud remove endpoint

### ISSUE THREAD

**Issue by vicentefederico** [loopbackio/loopback-next#6086]
I have generated  my endpoints  model with rest-crud. 
how can I do to remove particulare endpoint?
such like at delete method. I do not intend to use it and it gives greater security a mi DB

**Comment by alcmontejo** [comment]
I think you can implement `defineCrudRestController ` as workaround for now -> https://github.com/strongloop/loopback-next/tree/master/packages/rest-crud#creating-a-crud-controller

**Comment by achrinza** [comment]
Sounds like a possible feature that could be added.

**Comment by alcmontejo** [comment]
@achrinza yep agree, it would be nice if we can toggle endpoint through config.

**Comment by bajtos** [comment]
In my experience from LB3, making REST API endpoints configurable introduces a lot of complexity in our codebase and makes it difficult for our users to learn about all different configuration options to use.

The idea behind `rest-crud` is to allow users to quickly scaffold *the default* REST API. If your project has outgrown the default REST API shape, then I recommend to use `lb4 repository` and `lb4 controller` instead. Then you have full control of the REST API and you can simply remove the delete endpoint from your controller class.

I have been thinking about a mixed approach too, where you may want to use the same controller/REST API for multiple models. I have designed `ModelApiBuilder` with this use case in mind, I believe all building blocks are already in place.

1. Repository & REST semantics provided by `lb4 rest-crud` are implemented by [@loopback/rest-crud](https://github.com/strongloop/loopback-next/tree/70741829678b5a0dc9c277a12674725c8a2efb1d/packages/rest-crud), which is a small extension providing `CrudRestApiBuilder` that plugs into our existing boot/model-api-booter infrastructure and implements factories to create a repository and a controller class.

2. You can write your own ModelApiBuilder implementation, for example by forking `@loopback/rest-crud` package. In this implementation, you can change the controller class as you like. Just make sure to pick a unique pattern (don't use `CrudRest`).

3. Then you need to add your new component to your app, and change your model-config files to use a different `pattern`, the one defined in your extension.

The missing piece is CLI support. It would be great to have a more CLI command that's more flexible than `lb4 rest-crud`, one that will ask the user what pattern to use. (Example command names to consider: `lb4 model-api` or `lb4 publish-model`.) Ideally, the command should detect which patterns are available in the app (which model-api builders are registered), and offer the user a list to pick from.

**Comment by Lambdac0re** [comment]
+1
