### ISSUE TITLE
Docs:  adding a how-to "Configuring datasource" page

### ISSUE THREAD

**Issue by agnes512** [loopbackio/loopback-next#6091]
continuation of https://github.com/strongloop/loopback-next/pull/6061.
Finish the page "Configuring Datasource"

## Acceptance criteria
- [ ] add contents:
- how to configure the connector ( what properties the connector configuration
  might take
- how type maps ("LoopBack Types" may help)
  - to database (Database Migration), e.g String -> Varchar, Boolean -> Tinyint
  - from database (Discovery), e.g Bigint -> int, Text -> String
- how to customize table/column names
- how to discover/migration tables/models
- list connector specific topics, e.g transaction, objectId, and read should check the corresponding connector pages.
- add links to connector reference
- [ ] Move https://loopback.io/doc/en/lb4/DataSources.html#creating-a-datasource-at-runtime from "Datasource"

**Comment by dhmlau** [comment]
related to https://github.com/strongloop/loopback-next/issues/5646.
