### ISSUE TITLE
Docs: adding "Connecting to databases  tutorials"

### ISSUE THREAD

**Issue by agnes512** [loopbackio/loopback-next#6093]
Continuation of #6061
Finish the content in `tutorials/connectors/Connecting-to-databases.md`

## Acceptance Criteria 
- [ ] Add contents:
- Briefly introduce what is connectors and what connectors LB provides.
- List the connector tutorials we have in connector ref (MySQL, PostgreSQL, Oracle, and MongoDB)
- Add the link to connector ref

**Comment by mbryk** [comment]
This issue is still linked from the "[Connecting to Back-end Service Tutorials](https://loopback.io/doc/en/lb4/Connecting-to-back-end.html)" page. Will that page be receiving any documentation? Thank you!
