### ISSUE TITLE
Cleaner controller files

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-next#6121]
Currently controller files look something like this:

```ts
...
  @post('/authors', {
    responses: {
      '200': {
        description: 'Author model instance',
        content: {'application/json': {schema: getModelSchemaRef(Author)}},
      },
    },
  })
  async create(
    @requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Author, {
            title: 'NewAuthor',
            exclude: ['id'],
          }),
        },
      },
    })
    author: Omit<Author, 'id'>,
  ): Promise<Author> {
    return this.authorRepository.create(author);
  }

  @get('/authors/count', {
    responses: {
      '200': {
        description: 'Author model count',
        content: {'application/json': {schema: CountSchema}},
      },
    },
  })
  async count(
    @param.where(Author) where?: Where<Author>,
  ): Promise<Count> {
    return this.authorRepository.count(where);
  }

  @get('/authors', {
    responses: {
      '200': {
        description: 'Array of Author model instances',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: getModelSchemaRef(Author, {includeRelations: true}),
            },
          },
        },
      },
    },
  })
  async find(
    @param.filter(Author) filter?: Filter<Author>,
  ): Promise<Author[]> {
    return this.authorRepository.find(filter);
  }
...
```

How about we reduce it to something like the following? It is the same three methods.

```ts
...
@post('/authors', createSpec)
async create(
  @requestBody(bodySpec)
  author: Omit<Author, 'id'>,
): Promise<Author> {
  return this.authorRepository.create(author);
}

@get('/authors/count', countSpec)
async count(
  @param.where(Author) where?: Where<Author>,
): Promise<Count> {
  return this.authorRepository.count(where);
}

@get('/authors', findSpec)
async find(
  @param.filter(Author) filter?: Filter<Author>,
): Promise<Author[]> {
  return this.authorRepository.find(filter);
}
...
```

Controller files may not be something that's frequently edited, but whenever someone happens to look at it, they should feel good about it. Currently repository method calls are like needles in a haystack of specification objects.

**Comment by raymondfeng** [comment]
I agree that the controller class is a too noisy. Do we want to have a side file or move the spec objects toward the end of the file?

**Comment by hacksparrow** [comment]
A side file would be a better solution, IMO.

**Comment by hacksparrow** [comment]
@raymondfeng Even better - construct the OAS from the return type of the controller method without needing to include any object. It is some work to do, but not impossible, and makes a huge difference in the DX and perception of the framework.

If someone wants to specify their own OAS let them do, if none is specified LoopBack generates it for them.

**Comment by raymondfeng** [comment]
@hacksparrow We already allows introspection of TypeScript classes, either using `x-ts-type` or `getModelSchemaRef`. Please note TypeScript cannot reflect `Promise<MyModel>`. or `MyModel[]`.

**Comment by raymondfeng** [comment]
> A side file would be a better solution, IMO.

A side file can be more difficult to maintain and navigate.

**Comment by hacksparrow** [comment]
The primary goal is to reduce the noise, let's go ahead with the easiest solution - move the spec objects toward the end of the file.

**Comment by Salketer** [comment]
We created shorthands for a project I work on...

```
@requestBody({
      content: {
        'application/json': {
          schema: getModelSchemaRef(Author, {
            title: 'NewAuthor',
            exclude: ['id'],
          }),
        },
      },
    })
```

Becomes

`@requestBody.Model(Author)`

I'm not too sure how else one should tackle that... While it might be too verbose looking at multiple functions, you are most likely gonna work on one action at a time and having everything in sight when you do is very helpful IMO. 

I have a harder time with the lack of synergy between different decorators like the HTTP verbs and `@authenticate` that where authenticate does not apply the security specs by itself.

What about binding providers to fill the spec accordingly?
