### ISSUE TITLE
passport-login support for Azure, Linkedin

### ISSUE THREAD

**Issue by argupta23** [loopbackio/loopback-next#6218]
## Suggestion

Are there any plans for adding support for Azure and Linkedin user authentication to the current example?

I understand that twitter is being looked into.

Thanks

**Comment by dhmlau** [comment]
@argupta23, thanks for bringing this up. Do you see any significant differences when authenticating with Facebook/Google (which the [passport-login example](https://github.com/strongloop/loopback-next/tree/master/examples/passport-login) covered) vs LinkedIn?
