### ISSUE TITLE
Wrong query parse in nested condition where filter for REST query to JSON query

### ISSUE THREAD

**Issue by ntsd** [loopbackio/loopback-next#6222]
I'm trying to use a filter for the REST query when "AND" condition inside the "OR" condition.

Here's the document about how to query [Link](https://loopback.io/doc/en/lb4/Where-filter.html#and--or)

for example in my URL params

``` URL
filter[where][or][0][and][0][status]="ONLINE"&
filter[where][or][0][and][1][type]="USER"&
filter[where][or][1][and][0][status]="ONLINE&
filter[where][or][1][and][1][type]="ADMIN"
```

What I get for the filter query parser. I don't know why there's "[]" inside of the query.

``` JSON
{
  "where": {
    "or": [
      {
        "and": [
          { "[status]": "ONLINE" },
          { "[type]": "USER" }
        ]
      },
      {
        "and": [
          { "[status]": "ONLINE" },
          { "[type]": "ADMIN" }
        ]
      }
    ]
  }
}
```

This is what is expected. it works on the JSON query.

``` JSON
{
  "where": {
    "or": [
      {
        "and": [
          { "status": "ONLINE" },
          { "type": "USER" }
        ]
      },
      {
        "and": [
          { "status": "ONLINE" },
          { "type": "ADMIN" }
        ]
      }
    ]
  }
}
```

**Comment by achrinza** [comment]
lb4 uses Express.js urlencoded parser, which uses [`qs`](https://www.npmjs.com/package/qs). By default, `qs` has default hard limits - such as 5 levels of nesting - as a security feature. Though I'll need to look into it further to confirm this.

A way to get around this limitation is to use [stringified JSON](https://loopback.io/doc/en/lb4/Querying-data.html#using-stringified-json-in-rest-queries):

```
?filter={"where":{"or":[{"and":[{"status":"ONLINE"},{"type":"USER"}]},{"and":[{"status":"ONLINE"},{"type":"ADMIN"}]}]}}
```

This removes the need for `qs` and will be directly parsed as plain JSON.

**Comment by ntsd** [comment]
> lb4 uses Express.js urlencoded parser, which uses [`qs`](https://www.npmjs.com/package/qs). By default, `qs` has default hard limits - such as 5 levels of nesting - as a security feature. Though I'll need to look into it further to confirm if Express.js keeps these defaults, and how to override them.
> 
> A way to get around this limitation is to use [stringified JSON](https://loopback.io/doc/en/lb4/Querying-data.html#using-stringified-json-in-rest-queries):
> 
> ```
> ?filter={"where":{"or":[{"and":[{"status":"ONLINE"},{"type":"USER"}]},{"and":[{"status":"ONLINE"},{"type":"ADMIN"}]}]}}
> ```
> 
> This removes the need for `qs` and will be directly parsed as plain JSON.

Thanks for the answer. I see how JSON URL params work. Agree with I should parse query in the front end instead of using the backend process. Maybe I need to test **qs** for the bug.

**Comment by spupek** [comment]
I think the problem lies within @loopback-rest coercion/coerce-parameter.ts file. The the top level query parameter values are coerced by their defined types. In case of an object, after coercion the object is returned, but the object itself is **not recursively** inspected further according to the schema specification.

I am facing with a similar issue, when having a query schema as follows - top level object having keys containing array of values. In this case the array is not coerced (multipleValues="value1" => raised the not an array error):
```json
schema: {
  "type": "object",
  "properties": {
    "stringValue": {
      "type": "string"
    },
    "multipleValues": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```
