### ISSUE TITLE
Single instance of openapi.json

### ISSUE THREAD

**Issue by hacksparrow** [loopbackio/loopback-next#6223]
Currently a LoopBack app can have two instances of `openapi.json`. One at `/openapi.json`, another at `/explorer/openapi.json`. This makes control over `openapi.json` more complex than it should be.

Eg: `openApiSpec.disabled = true` has no effect on `/explorer/openapi.json`.

**Comment by dhmlau** [comment]
@hacksparrow, is it a bug in this case?
