### ISSUE TITLE
docs: how to stub a relation repository

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#6225]
Currently, [Testing your application](https://loopback.io/doc/en/lb4/Testing-your-application.html) does not have information on stubbing a relation repository.

This can be a bit tricky for the typical lb4 user to stub as they may need a deeper understanding of how repository relations are resolved. This makes writings unit tests difficult.

We should be providing lb4 users a recommended method so as to reduce the fatigue from having to understand some of the inner-workings of lb4 repositories and relations.

## Suggestion

Add documentation on how to stub a relation repository.

## Use Cases

This would help lb4 users to write better unit tests for their lb4 applications.

For example, there was an inquiry on this:
- https://loopbackio.slack.com/archives/C01177XQN8N/p1598659494196700

## Examples

N/A

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Tabby-web** [comment]
##

**Comment by earllapura** [comment]
+1
