### ISSUE TITLE
passport-login example expose REST Explorer - steps

### ISSUE THREAD

**Issue by argupta23** [loopbackio/loopback-next#6246]
Playing around with the example last week, I wanted to share a few updates

1. You need to import @loopback/rest-explorer into the package
2. update src/application.ts file to include the following lines

`import {  RestExplorerBindings,  RestExplorerComponent,} from '@loopback/rest-explorer';
import path from 'path';`

within the constructor add the following
`    // Set up default home page
    this.static('/', path.join(__dirname, '../public'));
    // Customize @loopback/rest-explorer configuration here
    this.configure(RestExplorerBindings.COMPONENT).to({path: '/explorer',  });
    this.component(RestExplorerComponent);`

3. update index.html to read as
`  <h3>API Explorer: <a href="/api/explorer">/explorer</a></h3>`

You should now have the REST explorer at "localhost:3000/api/explorer"

Hope this helps.

**Comment by dhmlau** [comment]
@argupta23, thanks for sharing. Would you like to help improving our docs by submitting a PR to include your updates? Thanks.

**Comment by argupta23** [comment]
@dhmlau 

Yes, will do, lets see what response I get related to #6248 and the progress I make.

Thanks

**Comment by argupta23** [comment]
@dhmlau 

This question has been asked on Slack channel by other users, but I have not seen a good reply yet.

Can somebody please outline the steps to disable the JADE  application within this code?

Thanks
