### ISSUE TITLE
Provide safety nets for `lb4 update`

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#6251]
## Suggestion

Add a safety net for users of `lb4 update` such as `lb4 revert` to revert the changes of `lb4 update` (including `package-lock.json`), and a more prominent warning to take a snapshot of the project (e.g. with `git`) before proceeding.

## Use Cases

There has been quite a few instances of the community using `lb4 update` without taking a backup. Most probably because they assume the CLI would handle breaking changes (like Schematics).

## Examples

TBD

## Acceptance criteria

TBD - will be filled by the team.

**Comment by hacksparrow** [comment]
Great suggestion!
