### ISSUE TITLE
[GSSC-GVT][v10]English string in apic lb4 service

### ISSUE THREAD

**Issue by wxuwh** [loopbackio/loopback-next#6287]
"27.030.040": English string Service

Steps & Verification Points:
input ./apic lb4
input lbproject as Project aame and Click Enter
input lbproject as Project description and Click Enter
input lbproject as Project root directory and Click Enter
Leave application class name as default and click Enter
Click Enter
Wait until the project has been created
input cd lbproject and click Enter
input ../apic lb4 service and click Enter
and click Enter
Verify the strings in red circle.

# Screenshots + Video
English string in apic lb4 service
![image](https://media.github.ibm.com/user/106781/files/772ab800-f0fa-11ea-8a14-4904af82a33b)

**Comment by wxuwh** [comment]
I have no access to add label, could you please help to add GVT label for this issue? Thanks. @agnes512 @dhmlau

**Comment by dhmlau** [comment]
@wxuwh, I believe `Service` is a reserved word here and not meant to be translated. I've submitted PR https://github.com/strongloop/loopback-next/pull/6298 to specify that. Thanks.
