### ISSUE TITLE
Keep a consistent documentation flow

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#6337]
## User story

LoopBack 4 is an incredibly extensible meta-framework. While this provides flexibility, it can also be daunting to new users who may be unfamiliar with LoopBack 4.

For example, the Express Middleware documentation teachers users how to modify the middleware chain via Sequences when using `this.expressMiddleware()` is arguably a more simple and flexible method.

The user now has to understand Sequences before being able to understand the documentation. Furthermore, since modifying the Sequence is the first method shown on the documentation, the users may imply that it is the preferred method to adding Express middleware.

## Suggestion

Where possible, we should (re-)write documentation to provide solutions with the lowest "barrier of entry" at the top of the page.

For example, the Express Middleware documentation should inform users of `this.expressMiddleware()` and then explicitly classify the modification of the Sequence as an "advanced usage". This would keep the documentation simple of those who don't need the 

We should be easing the "onboarding experience" of new users by not bombarding them with any more concepts than necessary, while still providing "advanced usage" guides to allow power users to reap the benefits of the extensibility and flexibility of LoopBack 4.

## Acceptance criteria

TBD - will be filled by the team.

Potential candidate pages:
- https://loopback.io/doc/en/lb4/Middleware.html#extend-sequence-with-more-than-one-middleware-actions
- https://loopback.io/doc/en/lb4/Express-middleware.html#invoke-express-middleware-explicitly-in-the-sequence

**Comment by dhmlau** [comment]
@achrinza, thanks for the suggestion. Do you have a list of specific places where the changes should occur? It can be the acceptance criteria of this issue. Thanks.
