### ISSUE TITLE
Postgres model discovery doesn't correctly handle a primary key generated by a sequence

### ISSUE THREAD

**Issue by tomsaleeba** [loopbackio/loopback-next#6386]
I was going to file this in the loopback-datasource-juggler repo but it told me to come here.

I'm very open to the fact that I might be doing something wrong, and happy to be corrected.

This is a bug.

TL;DR: I think the discovery process should detect when there is a required field that is generated by the DB and mark it as *not* required.

Steps:
 - [create a sequence](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/64f978b400d83c2c3cb7299708ec47a488febf1c/schema.sql#L16) in Postgres
 - [create a table that uses that sequence](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/64f978b400d83c2c3cb7299708ec47a488febf1c/schema.sql#L19) to generate the primary key
 - use Loopback's tools to [discover the models](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/64f978b400d83c2c3cb7299708ec47a488febf1c/src/dynamic-models/magic-discovery.ts#L50), and then [create repository, controller](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/master/src/dynamic-models/magic-discovery.ts#L82-97), etc
 - go to use the REST CRUD API and do *not* supply the PK/id field

Expected:
The DB record is created and the DB handles generating the ID.

Actual:
The API returns the following error:
```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Bike` instance is not valid. Details: `id` can't be blank (value: undefined).",
    "details": {
      "context": "Bike",
      "codes": {
        "id": [
          "presence"
        ]
      },
      "messages": {
        "id": [
          "can't be blank"
        ]
      }
    }
  }
}
```

If you then provide the id field, you get a different error:
```
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": "",
        "code": "additionalProperties",
        "message": "should NOT have additional properties",
        "info": {
          "additionalProperty": "id"
        }
      }
    ]
  }
}
```

I have a reproduction of it in this repo: https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo. As it stands, this repo already has [a workaround](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/64f978b400d83c2c3cb7299708ec47a488febf1c/src/dynamic-models/magic-discovery.ts#L72), so to make it break you need to change [the list of tables with generated IDs that we apply to workaround to](https://gitlab.com/ternandsparrow/loopback-postgres-dynamic-models-demo/-/blob/64f978b400d83c2c3cb7299708ec47a488febf1c/docker-compose.yml#L19).
```diff
-      TABLES_WITH_GEN_ID: bike,person
+      TABLES_WITH_GEN_ID: z
```
Then you can follow the instructions to start the demo and hit the /bike or /person endpoints to POST a record.

With the workaround enabled, we just turn off the `required` flag for ID columns in the specified tables. The downfall is you need to specify which tables need the action taken. A real fix is for the discovery process to detect and handle this situation.

Thanks for the great library BTW :+1: :heart_eyes:

**Comment by agnes512** [comment]
Related to https://github.com/strongloop/loopback-next/issues/4557#issuecomment-582135041
