### ISSUE TITLE
Add debug instructions about memory profiling, CPU usage

### ISSUE THREAD

**Issue by jannyHou** [loopbackio/loopback-next#6465]
Follow up story of https://github.com/strongloop/loopback-next/issues/5701

## Suggestion

Add debug instructions about memory profiling, CPU usage. More conversation can be found here https://github.com/strongloop/loopback-next/issues/5701#issuecomment-667213187

## Acceptance criteria

- [ ] Add a new page for debug instructions about memory profiling, CPU usage. Link it under the troubleshooting page.

**Comment by dhmlau** [comment]
Capturing the info from Slack: https://loopbackio.slack.com/archives/C01177XQN8N/p1606581954022100

From @raymondfeng: 
> I would recommend https://www.npmjs.com/package/heapdump to analyze memory leaks
> https://blog.logrocket.com/understanding-memory-leaks-node-js-apps/


From @mrmodise:
> Side note, also ensure you set --max-old-space-size: https://medium.com/@vuongtran/how-to-solve-process-out-of-memory-in-node-js-5f0de8f8464c

From @bajtos:
> I have good experience with https://clinicjs.org. It makes it easy to do the profiling and can even detect common problems automatically.
