### ISSUE TITLE
Child model method with Parent.findOne( including Childs) creates Circular Dependency.

### ISSUE THREAD

**Issue by fredhansen25** [loopbackio/loopback-next#6485]
> **Maintainers' note**
> This issue has been posted elsewhere:
> - https://loopbackio.slack.com/archives/C01177XQN8N/p1601600664134400
> - https://stackoverflow.com/q/64164564

Hello,
How I fix Circular Dependency in a schema as: A.hasmany(B)  B.belongsTo(A), when method B.newItem needs to A.findOne(id,{  include: [ { relation: "b" }] })  ?

My loopback4 project contains two models 
   Order  - Order contains hasMany Report
   Report - Report belongsTo Order  

On ReportRepository.newReport method, I need to find and manipulate all data of Order, including reports. And this causes Circular Dependency.

Is this an issue, error on coding? How can I avoid this error?
If I remove orderRepositoryGetter from Report, what I use the findOne method?

Already tried:
 
 @bind({scope: BindingScope.SINGLETON}) - 
 https://stackoverflow.com/questions/61978534/how-to-implement-chained-models-with-loopback-4-without-getting-a-circular-depen
Ok for Circular Dependency but creates multi-tenancy issues, since I'm using Datasource-based tenant isolation described here https://github.com/strongloop/loopback-next/issues/5056  (starts saving/getting data from one particular tenant instead of the users tenant)

## Steps to reproduce

```
OrderRepository{ 
	public readonly reports: HasManyRepositoryFactory<Reports, typeof OrdemServico.prototype.id>;

	constructor(
		@repository.getter('ReportRepository')
		protected reportRepositoryGetter: Getter<ReportRepository>
	){
		this.reports = this.createHasManyRepositoryFactoryFor('reports', reportRepositoryGetter); // Getter.fromValue(this));
		this.registerInclusionResolver('reports', this.reports.inclusionResolver);
	}

}


ReportRepository {
	public readonly order: BelongsToAccessor<Order, typeof Reports.prototype.id>;

	constructor(
		 @repository.getter('OrderRepository') protected orderRepositoryGetter: Getter<OrderRepository>,
	){
	   this.order = this.createBelongsToAccessorFor('order', orderRepositoryGetter,);
	}


	async newReport(nReport: Omit<Report, 'id'>) : PromiseLike<Report> {
	   const oRepGet = await orderRepositoryGetter;
	   
	   return oRepGet.findOne({
			  where: {        
				Id: nReport.o
			  },
			  include: [ { relation: "reports" }]   // <--- Circular Dependency Detected
			  
			})
			.then ((rros) => {
			
			 .........
			 
			}); 
	   
	}
}

```
## Current Behavior

Runtime failing 
Unhandled error in POST /ordem-servico-etapas: 500 Error: Circular dependency detected: controllers.ReportController --> @ReportController.constructor[0] --> repositories.ReportReposi
tory --> @ReportRepository.constructor[1] --> repositories.OrderRepository --> @OrderRepository.constructor[7] --> repositories.ReportRepository

## Expected Behavior

return Order Object with Relations (in this case Reports[])

**Comment by hessman** [comment]
Hi you can not use the order repo in your report repo. 
You can only use the getter to define relations. 
If you want to implement this logic you need to do this in a controller or a service.
