### ISSUE TITLE
Change to ts-node

### ISSUE THREAD

**Issue by mdbetancourt** [loopbackio/loopback-next#6595]
## Suggestion
Is there any chance to use ts-node instead of build+node, also there exists ts-node-dev which is blazing fast for reloading ts-node, this solve issues like #3259 and others problems (i saw some issues with booters because .js and .ts files etc) for production could be used ts-node eliminating build step, i could help with this feature if it's okay

## Sample repository
https://github.com/mdbetancourt/ts-node-loopback

## Acceptance criteria

TBD - will be filled by the team.

**Comment by raymondfeng** [comment]
I think `ts-node` might have issue with `app.boot()` as our booters expect to use `.js` files.

**Comment by mdbetancourt** [comment]
@raymondfeng i already have implemented a loopback api with ts-node (and ts-node-dev) (with a complex structure) with some kind of a plugin system which extend existing injections through mixins and reinjecting, booters etc with zero problems, the reloading with ts-node-dev is almost instantaneous after a file change

**Comment by mdbetancourt** [comment]
also i'm researching to develop or find a package similar to ts-node-dev for mocha (instead of use require ts-node/register) so test re execution become so fast too

**Comment by raymondfeng** [comment]
@mdbetancourt Do you have a public github repo to share your work? If not, can you provide more details? Examples will be helpful.

**Comment by bradharms** [comment]
We have been successfully using ts-node for close to a year now. It's possible, but to do so you can't use loopback to its fullest potential because of issues like the above. This has influenced our coding style to move away from the style of a skeleton app as produced by the Loopback CLI. We are about to move to standard typescript so we can make better use of Loopback's features.

**Comment by mdbetancourt** [comment]
@bradharms and @raymondfeng, please check the sample repository which i added, also i used Yarn 2 (like commented in #6596) so pls try it with yarn

**Comment by lucaskuperman** [comment]
After more than 3 years , is there any way I can run loopback with ts-node/ts-node-dev ?
