### ISSUE TITLE
Migrate and recommend to use Yarn 2

### ISSUE THREAD

**Issue by mdbetancourt** [loopbackio/loopback-next#6596]
## Suggestion
Yarn 2 comes with a lot of new features https://yarnpkg.com/features/pnp some of then is reduction of node_modules size, also start time is improved (yarn 2 fix the node require issue) and best practices (like explicitly name every dep in package.json) which could help in issues like #257 because the cold start
We can start listing every dependency explicitly to be more yarn 2 "friendly" because currently is needed to use https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions

## Sample repository
https://github.com/mdbetancourt/ts-node-loopback

**Comment by bradharms** [comment]
Modern versions of Npm do a very good job as a package manager and is included by default with node. I know when Yarn was first introduced it dealt with issues that Npm had at the time, but since then Npm has improved substantially. Now Yarn is mostly additional tooling that the user has to install. I think it would be better if Yarn were an option to choose from as an alternative, but not as the default. That's just my opinion.

**Comment by mdbetancourt** [comment]
Hi @bradharms thank you for give your opinion, about some of your points

> Modern versions of Npm do a very good job as a package manager

i never said otherwise, i agreed with you

> is included by default with node.

I know but almost everyone has it installed in their machines (even node docker image already include it)

> Now Yarn is mostly additional tooling that the user has to install

I'm not talking about yarn itself (which also is a bit better just check [benchmarks](https://github.com/pnpm/benchmarks-of-javascript-package-managers)) but about PnP resolution of yarn

> I think it would be better if Yarn were an option to choose from as an alternative

Currently it's so (when you use lb4 it gives you to choose), i'm talking about migrate the current Yarn 1 (which provide the cli) to Yarn 2 (because to use yarn 2 from user land is a lot of work to do just check .yarnrc in the sample repo) and recommend the usage of yarn to the user because the startup time (which can help in serverless environments), better practice etc

**Comment by bradharms** [comment]
@mdbetancourt Ah, I see. Sorry for the confusion.
