### ISSUE TITLE
[Docs] How to debug a LoopBack application

### ISSUE THREAD

**Issue by dhmlau** [loopbackio/loopback-next#6613]
In the [troubleshooting guide](https://loopback.io/doc/en/lb4/Troubleshooting.html), we can add the information on how to set breakpoints in a LB4 app as debugging. 

Some high level information for VS code: 
-  go to Debug > create a launch.json. 
- edit the `program` properties in launch.json, so that it looks like:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/index.js"
    }
  ]
}
```
- set the breakpoint to the location you want
- go back to Debug tab in VS code and select the launch program you just created

**Comment by hectorleiva** [comment]
Hey @dhmlau !

Are you looking for someone to type up this VSCode procedure into the troubleshooting guide and to provide perhaps, a gif of this happening? Are you looking for as many different ways to debug a Node.js application as possible including this VSCode process? This seems like it is up my alley.

**Comment by dhmlau** [comment]
@hectorleiva, there were some questions on the [LoopBack Slack workspace](https://join.slack.com/t/loopbackio/shared_invite/zt-8lbow73r-SKAKz61Vdao~_rGf91pcsw) about setting breakpoints to debug a LoopBack application, so I created this issue to capture that. 
@jannyHou has a PR https://github.com/strongloop/loopback-next/pull/6615 to update the CLI template so that the launch.json will be included in a scaffolded app. I guess we can add some instructions based on the outcome of that PR.
