### ISSUE TITLE
Allow multiple routes decorated to a controller method

### ISSUE THREAD

**Issue by f-w** [loopbackio/loopback-next#6707]
## Suggestion

lb3 allows a custom remote method to handle multiple routes. lb4 limits # of operation decorators to 1 for a controller method. Even though it can be mitigated by creating separate methods calling common code, the API spec in parameter decorators of these methods have to be duplicated.

## Use Cases

Consider a self managed opt-in opt-out email subscription API server, user can unsubscribe by calling `DELETE /subscriptions/{id}` endpoint. But it is also a common practice to provide a `GET` endpoint in order to unsubscribe by clicking the unsubscribe link in email. Parameters and underlying business logic should be the same for both `GET` and `DELETE` endpoints.

## Examples
In lb3 this can be achieved using array for *http* property
```
  "methods": {
    "prototype.deleteItemById": {
      ...
      "http": [
        {
          "path": "/",
          "verb": "delete"
        },
        {
          "path": "/unsubscribe",
          "verb": "get"
        }
      ]
    },
  },
```

lb4 equivalent would be either

```
  @operation([{verb: 'GET', path: '/subscriptions/{id}/unsubscribe'}, 
              {verb: 'DELETE', path: '/subscriptions/{id}'}], 
             {...}: OperationObject)
  async deleteById(...){...}
```
or 

```
  @del('/subscriptions/{id}', {...}: OperationObject)
  @get('/subscriptions/{id}/unsubscribe', {...}: OperationObject)
  async deleteById(...){...}
```
in controller class. The first option is preferred because *OperationObject* spec can also be shared.

**Comment by mdbetancourt** [comment]
yes i get some problems with this too but is mainly caused because currently loopback decorators doesnt allow to decorate the same function, property (like models) twice

**Comment by raymondfeng** [comment]
It can be achieved as follows:

```ts
@del('/subscriptions/{id}')
async deleteById(...){...}

@get('/subscriptions/{id}/unsubscribe')
async deleteById2(...){
  return this.deleteById(...);
}
```

There are some complexity to mark a single method with multiple `@operation` or sugar decorators as we need to find out how to merge specs.

Maybe one compromise is to allow something like `aliasPaths` to allow extra routes for `@operation`

**Comment by f-w** [comment]
> It can be achieved as follows:
> 
> ```ts
> @del('/subscriptions/{id}')
> async deleteById(...){...}
> 
> @get('/subscriptions/{id}/unsubscribe')
> async deleteById2(...){
>   return this.deleteById(...);
> }
> ```

The drawback is explained in Suggestion section.

**Comment by raymondfeng** [comment]
@f-w If you are willing to contribute a patch to allow alternative verb/path for a given operation, we are happy to review.

**Comment by f-w** [comment]
@raymondfeng , is this alternative less complex?

```
@operation([{verb: 'GET', path: '/subscriptions/{id}/unsubscribe'}, 
              {verb: 'DELETE', path: '/subscriptions/{id}'}], 
             {...}: OperationObject)
  async deleteById(...){...}
```

**Comment by mdbetancourt** [comment]
> @raymondfeng , is this alternative less complex?
> 
> ```
> @operation([{verb: 'GET', path: '/subscriptions/{id}/unsubscribe'}, 
>               {verb: 'DELETE', path: '/subscriptions/{id}'}], 
>              {...}: OperationObject)
>   async deleteById(...){...}
> ```

i dont think so xd

**Comment by raymondfeng** [comment]
What I have in mind is something like:

```ts
@path('get', '/subscriptions/{id}/unsubscribe')
@delete('/subscriptions/{id}' , spec)
```

**Comment by f-w** [comment]
> What I have in mind is something like:
> 
> ```ts
> @path('get', '/subscriptions/{id}/unsubscribe') // it only accepts verb and path, not spec
> @delete('/subscriptions/{id}' , spec)
> ```
> 
> The `@path` is a placeholder. Maybe `@route` or `@alias` is better.

It limits # of routes to a method to 2.

**Comment by raymondfeng** [comment]
Not really. The `@path` can be applied more than once to the same method.

**Comment by achrinza** [comment]
My main concern with `@path()` is that it may be too restrictive. For example, in most cases, these endpoints might have a different `description`.

I favour supporting "stacking" `@operation()`, `@get()`, etc.

Also potentially allow the decorators to accept an array:

```
@get([
  {'/users/{id}' , spec},
  {'/users2/{id}' , spec},
])
```

This would enable developers to group their requests by their RESTful operations.

**Comment by mdbetancourt** [comment]
+1 to use
@get()
@post()

**Comment by raymondfeng** [comment]
My goal was to minimize the merging complexity. It will only allow 0-N `@path` in addition to one `@operation` (including `@get`, `@post`, etc). Merging specs is not fun.

```ts
@path('get', '/users2/{id}')
@path('get', '/subscriptions/{id}/unsubscribe')
@delete('/subscriptions/{id}' , spec)
```

**Comment by f-w** [comment]
> Not really. The `@path` can be applied more than once to the same method.

@raymondfeng , are you sure? The limitation of applying a decorator function maximum once to a method is imposed by [decorator-factory](https://github.com/strongloop/loopback-next/blob/afb99ebcbea9924b590f211c1db33c9b0d570152/packages/metadata/src/decorator-factory.ts#L275) rather than openapi-v3. If it's easy to allow multiple `path` decorators, then it's also easy to allow multiple operation decorators.

**Comment by raymondfeng** [comment]
@f-w See https://github.com/strongloop/loopback-next/blob/afb99ebcbea9924b590f211c1db33c9b0d570152/packages/metadata/src/decorator-factory.ts#L823. We have `MethodMultiDecoratorFactory<T>` which is used by `@response`
