### ISSUE TITLE
Let api explorer use a different protocol than the loopback server

### ISSUE THREAD

**Issue by Salketer** [loopbackio/loopback-next#6718]
## Suggestion

It would be useful to be able to define the protocol of the servers when defining the Api Specs. The loopback rest server can be turned on https, and while it is on, the swagger is set accordingly, but having swagger independent configuration is necessary.

## Use Cases

I want my loopback rest server to use http since it is behind a reverse proxy that handles the SSL matters. But that means I cannot use the swagger UI anymore since it tries to reach http endpoints and not https.

Even if  I set it explicitly, the config stays without SSL.
```
this.api({
      openapi: '3.0.0',
      info: {title: pkg.name, version: pkg.version},
      paths: {},
      servers: [{url: "https://mysite.com/api"}],
    });
```

## Acceptance criteria

TBD - will be filled by the team.

**Comment by Salketer** [comment]
Any thoughts on this? We would like to open up the explorer of our public API but we cannot do it for now because of this... If the team could list what should be done, we might be able to provide a PR.

**Comment by hacksparrow** [comment]
Please open a PR with a proposal, we can discuss the details there.

**Comment by ktaletsk** [comment]
Workaround for me was to set

```
setServersFromRequest: false,
servers: [{url: '/'}],
```

I use nginx ingress as a reverse proxy.
