### ISSUE TITLE
lb4 discover throws error UnhandledPromiseRejectionWarning: 

### ISSUE THREAD

**Issue by mtwinux** [loopbackio/loopback-next#6825]
my environment : 
Node.js [v12.18.4],NPM [ 6.14.8]

+-- @loopback/authentication@7.0.3
+-- @loopback/authentication-jwt@0.7.3
+-- @loopback/authorization@0.7.3
+-- @loopback/boot@3.1.0
+-- @loopback/build@6.2.6
+-- @loopback/core@2.12.0
+-- @loopback/eslint-config@10.0.2
+-- @loopback/repository@3.2.0
+-- @loopback/rest@9.0.0
+-- @loopback/rest-explorer@3.0.3
+-- @loopback/security@0.3.3
+-- @loopback/service-proxy@3.0.3
+-- @loopback/testlab@3.2.8
+-- @types/bcryptjs@2.4.2
+-- @types/node@10.17.44
+-- @types/nodemailer@6.4.0
+-- eslint@7.13.0
+-- ics@2.26.1
+-- loopback-connector-mysql@6.0.0
+-- moment@2.29.1
+-- moment-timezone@0.5.31
+-- nodemailer@6.4.16
+-- source-map-support@0.5.19
+-- strong-error-handler@4.0.0
+-- testcontainers@6.1.1
+-- tslib@2.0.3
`-- typescript@4.0.5

## Steps to reproduce
run database (mine is Mysql MariaDB).
ensure to set up datasource on loopback.

after updating i can no longer run lb4 discover
run command : lb4 discover

## Current Behavior
The command throws error : 

(node:8580) UnhandledPromiseRejectionWarning: TypeError: ds[key] is not a constructor
    at Object.loadDataSource (C:\Users\Marco\AppData\Roaming\npm\node_modules\@loopback\cli\lib\model-discoverer.js:49:17)
    at C:\Users\Marco\AppData\Roaming\npm\node_modules\@loopback\cli\generators\discover\index.js:108:23
    at Array.map (<anonymous>)
    at DiscoveryGenerator.loadAllDatasources (C:\Users\Marco\AppData\Roaming\npm\node_modules\@loopback\cli\generators\discover\index.js:107:46)
(node:8580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
> after updating i can no longer run lb4 discover

@mtwinux, could you please elaborate more on what you're updating which cause `lb4 discover` not working? Thanks.

**Comment by mtwinux** [comment]
I was saying it was after updating my loopback version with npm-check. But maybe it s not relevant.

I saw the issue is because it tries to instantiate the first property [0] guessing it s the data source class but it s not. It is the config property.

**Comment by dhmlau** [comment]
do you have a sample app that I can reproduce?

**Comment by mtwinux** [comment]
hi. that can be done, i will build one as soon as i find time !
as a workaround i had made some changes but i know maybe it's something i do wrong that may be the origin of the issue.

function loadDataSource(modulePath) {
    try {
        const ds = require(modulePath);
        //Looking for the DataSource
        for (const key of Object.keys(ds)) {
            if (key.indexOf('DataSource') >= 0) {
                //Returns the instance
                return new ds[key]();
            }
        }
        //If we get there, it's not good
        return Promise.reject("No DataSource ?!!");
    } catch (error) {
        return Promise.reject("Some kind of error happens ! " + error);
    }
}
