### ISSUE TITLE
Add a connector support checklist

### ISSUE THREAD

**Issue by achrinza** [loopbackio/loopback-next#6831]
## Suggestion

In each connectors' README, add a standard feature table to indicate which features are supported by the connector.

## Use Cases

Managing the behaviour and features across different databases is hard. Hence, it is a given that the connector feature support and the implementation of that functionality may differ.

Unfortunately, this means that LoopBack 4 users may have difficulty in discovering these limitations and in doing so, may grow frustrated as the connectors are seen as a blackbox with potentially undefined behaviour.

## Examples

The table may look something like this:

Connector: **MySQL**

| Feature | Supported? | Remarks
| --- | --- | ---
| CRUD | ✔️ | NIL
| KV | ❌ | NIL
| Transactions | ✔️ | NIL
| Strong relations | ✔️ | NIL
| Weak relations | ✔️ | NIL
| Native joins | ❌  | NIL
| Native arrays | ❌  | NIL
| Native dates | ✔️  | NIL
| Nested properties | ✔️  | NIL
| Discovery: Model | ✔️ | NIL
| Discovery: Strong relations | ❌ | NIL
| Discovery: Weak relations | ❌  | NIL

## Acceptance criteria

TBD - will be filled by the team.

**Comment by dhmlau** [comment]
@achrinza, thanks for opening this issue. I think after we agree on the feature list (as shown in your above example), we probably need to make it an epic, and create separate GH issues for individual connectors.

**Comment by mdbetancourt** [comment]
I wrote a mongodb connector following https://loopback.io/doc/en/lb4/Repository.html#persist-data-without-juggler-using-mysql-database where should i put it?
