### ISSUE TITLE
Easy Websocket Decorators

### ISSUE THREAD

**Issue by mightytyphoon** [loopbackio/loopback-next#6921]
Hi !

## Suggestion

I want to propose an easy way to create a websocket server bound to loopback, with security such as cookies and optimizations but without changing the architecture of loopback framework.

## Use Cases

If you want to create a mixed http2 / websocket server or if you want to create a full websocket server using loopback framework.

## Examples

If I take the ping controller as an example it would look like this :

```typescript
@WSController // controller decorator
export class PingController {
  private property: string = 'property !';

  @WSClient() private clients: any; // list of clients
  @WSServerDecorator() private wss: any; // ws server
  constructor(
    @repository(TestRepository) private testRepo: TestRepository
  ) { }

  @WSEndpoint('ping') // WS endpoint decorator with event name
  @get('/ping', {
    responses: {
      '200': PING_RESPONSE,
    },
  })
  ping(
    @inject(RestBindings.Http.REQUEST) req: Request
  ): object {
    return {
      greeting: 'Hello from LoopBack',
      date: new Date(),
      url: req.url,
      headers: Object.assign({}, req.headers),
    };
  }

  @WSEndpointDecorator('db-write')
  @post('/write') async writeDb( ) {
    return await this.testRepo.create({name: 'db write test'});
  }

  @WSEndpointDecorator('get some') getSome() {
    return 'some'
  }

  @WSEndpointDecorator('get property') getProperty() {
    return this.property;
  }


```
I am already able to get almost everything I need with decorators, for example the function getSome that returns 'some' works, the 'get property' works too to get instance private property and the 'db-write' also works to write something in db. I only have trouble to bind methods with loopback decorators such as @inject(RestBindings.Http.REQUEST) req: Request. the @repository decorator works though. I know the problem comes from my lack of understanding how @inject is used with loopback, and I have trouble to find what's wrong.

My solution almost already works, actually if we get rid of ``@inject(RestBindings.Http.REQUEST) private req: Request`` in constructor it works but I would like it to be fully working with loopback framework. The problem is that once websocket is open, there is no more req, it's just a tunnel communication between client and server. So I would like to find a way or idea to implement this.

If you are interested, on Websocket server side, there is a hashtable of endpoints and clients. Each client have listeners to websocket events ('message' event for example). When the event happens for a client, endpoint is found thanks to the event name in the hashtable, then the bound method to controller can be called. I will add decorator properties @WSClients()  that will give the possibility of sending data to specific list of clients or to all clients and a @WSServer() that will give a reference to the websocket server itself.

Thanks in advance for any help on that @inject(RestBindings.Http.REQUEST) which is the only thing I can't get to work.

**Comment by achrinza** [comment]
`@inject(RestBindings.Http.REQUEST)` tells LB4 to put an instance tied to that key into a variable during (controller) resolution time. As the name suggests, this binding is meant for REST only and is only populated when passed through the REST server. When the Controller is resolved outside of the "REST handler" workflow, this binding key is not bound to any value - Hence, the error.

You can consider separating the WebSocket and REST functions (if possible) and using [Optional Dependencies](https://loopback.io/doc/en/lb4/Dependency-injection.html#optional-dependencies).

**Comment by mightytyphoon** [comment]
@achrinza thanks a lot for your response.

after a bit of tries I finally managed to inject my own req using function bindings. It works like this :

```typescript
 const pingRes = this.endpoints['ping'].method.apply(null , [{url: '/ping-websocket' , headers: {websocket: 'some headers'}}]); // inject our req

// pingRes with websocket
{
  greeting: 'Hello from LoopBack',
  date: 2020-12-16T15:43:16.707Z,
  url: '/ping-websocket',
  headers: { websocket: 'some headers' }
}
// pingRes from http call
{
"greeting":"Hello from LoopBack",
"date":"2020-12-16T15:43:25.241Z",
"url":"/ping",
"headers":{"host":"localhost:3000","connection":"keep-alive","cache-control":"max-age=0","sec-ch-ua":"\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"","sec-ch-ua-mobile":"?0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"}}

// using this from default ping controller
  @WSEndpoint('ping') // WS endpoint decorator with event name
  @get('/ping', {
    responses: {
      '200': PING_RESPONSE,
    },
  })
  ping(
    @inject(RestBindings.Http.REQUEST) req: Request
  ): object {
    return {
      greeting: 'Hello from LoopBack',
      date: new Date(),
      url: req.url,
      headers: Object.assign({}, req.headers),
    };
  }
```

So the 2 protocols should be able to work together. Now I need to implement all default @inject bindings and I need to make an optimized filter that will inject the wanted params by default and check if params given by user have the good types for the method. For example reject requests which don't have the required params or requests with wrong types for params.

**Comment by mightytyphoon** [comment]
For anyone interested, I tried in local websocket request vs http request for ping function, and the websocket server gives the answer more than 100x faster than XMLHttpRequest (deprecated) and 6x faster than fetch.

ws: 0.05908203125 ms
http-XMLHttpRequest: 7.02685546875 ms
http-fetch: 0.38720703125 ms


![testwshttp](https://user-images.githubusercontent.com/4013025/102496951-5cac9700-4078-11eb-8da2-8bf21e7b0771.png)
