### ISSUE TITLE
Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.

### ISSUE THREAD

**Issue by JorisPalings** [loopbackio/loopback-next#7006]
I have a MongoDB database with approximately 80k records and a pretty basic Loopback 4 API to perform simple CRUD operations on it.

To paginate these 80k records, my frontend sends the following request to the API:
`GET /articles?filter[limit]=100&filter[skip]=80200&filter[order][0]=publication_date%20DESC&filter[order][1]=language%20DESC`

This returns an error 500 to my frontend.
In the terminal where I'm running the API, I get the following:
```
Request GET /articles?filter[limit]=100&filter[skip]=80200&filter[order][0]=publication_date%20DESC&filter[order][1]=language%20DESC failed with status code 500.
MongoError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.
Aborting operation. Pass allowDiskUse:true to opt in.
```

The solution seems simple enough: `Pass allowDiskUse:true to opt in.`
Except I'm not sure _where_ to pass this.
I've tried passing it as the `option` argument to my ArticleController's `find()` method:
`return this.articleRepository.find(filter, {allowDiskUse: true});`
as well as as a chained method as listed [here](https://stackoverflow.com/questions/53584326/is-allowdiskuse-valid-for-find-method-in-mongodb):
`return this.articleRepository.find(filter).allowDiskUse();`
but to no avail. 

According to Google, `allowDiskUse:true` is meant to be used with aggregate() rather than find().
Except I don't need an aggregation, I'm just trying to sort a large collection of records.

Any pointers would be much appreciated!

**Comment by yshing** [comment]
@JorisPalings That's a MongoDB issue. You shall set index on any field you're planning to sort on. And compound index when you need to sort on multiple fields, in this case you'll need to create compound index on `publication_date` and `language`.

Loopback cannot help you with this issue.😅

**Comment by TeoMihuc** [comment]
hello, has anybody found the solving to this problem?

**Comment by achauhanvonage** [comment]
Any update on this?

**Comment by jaidev228** [comment]
Any idea about this issue ?
