### ISSUE TITLE
loopback 4 services - how to configure keep-alive agent in lb4 service calls

### ISSUE THREAD

**Issue by vinutha93bnvs** [loopbackio/loopback-next#7012]
Greetings, 

To enhance the performance of a http requests (http.Agent), npm offers few packages like **keepaliveAgent** (https://www.npmjs.com/package/agentkeepalive)

This can improve the overall performance for frequent http calls by keep-alive connection and open sockets.

Can someone please guide how to configure KeepAliveAgent while making service calls with **loopback 4 services** ?

**Comment by vinutha93bnvs** [comment]
Can i get some help

**Comment by marioestradarosa** [comment]
@vinutha93bnvs  I am a little bit confused, please clarify. Do you want to enable keep-alive whenever you call other serves from your loopback 4 application or you want to enable other clients to call your loopback 4 application and honor keep-alive: true requests ?

**Comment by vinutha93bnvs** [comment]
@marioestradarosa 

I am trying to optimize the connections on my server. i.e. enable keep-alive whenever you call other serves from my loopback 4 application. 
More precisely, I am looking for enabling keep-alive / re-use connections on my Rest-Connector

**Comment by marioestradarosa** [comment]
@vinutha93bnvs   do you have the property ` gracePeriodForClose` in your index.ts file ?.  If so try to remove it since it should default to infinity.

Check: https://loopback.io/doc/en/lb4/apidocs.http-server.basehttpoptions.graceperiodforclose.html

**Comment by vinutha93bnvs** [comment]
@marioestradarosa 
I have not configured **gracePeriodForClose**  in my application.
