### ISSUE TITLE
Switch from Travis to Github action for connector repos

### ISSUE THREAD

**Issue by agnes512** [loopbackio/loopback-next#7054]
To keep track of the status of all connector repos.

- [x] [`loopback-connector-mongodb`](https://github.com/strongloop/loopback-connector-mongodb)
- [x] [`loopback-connector-mysql`](https://github.com/strongloop/loopback-connector-mysql) [WIP strongloop/loopback-connector-mysql#439]
- [ ] [`loopback-connector-cassandra`](https://github.com/strongloop/loopback-connector-cassandra)
- [x] [`loopback-connector-postgresql`](https://github.com/strongloop/loopback-connector-postgresql) [WIP strongloop/loopback-connector-postgresql#473]
- [x] [`loopback-connector-kv-redis`](https://github.com/strongloop/loopback-connector-kv-redis)

- [x] [`loopback-connector`](https://github.com/strongloop/loopback-connector)
- [x] [`loopback-connector-soap`](https://github.com/strongloop/loopback-connector-soap)
- [x] [`loopback-connector-rest`](https://github.com/strongloop/loopback-connector-rest)
- [ ] ~[`loopback-connector-swagger`](https://github.com/strongloop/loopback-connector-swagger)~ -> this repo hasn't been updated for 1.5 years 👀 . Deprecated. 
- [ ] ~[`loopback-component-storage`](https://github.com/strongloop/loopback-component-storage)~ -> only for LB3. Reached EOL.
- [x] [`loopback-connector-jsonrpc`](https://github.com/strongloop/loopback-connector-jsonrpc)
- [ ] [`loopback-connector-openapi`](https://github.com/strongloop/loopback-connector-openapi)

**Comment by agnes512** [comment]
https://github.com/strongloop/loopback-connector-mongodb/pull/613

**Comment by dhmlau** [comment]
Thanks @agnes512. I believe the loopback-connector-swagger has deprecated. loopback-connector-openapi should be used. So i think it's safe not to switch to GitHub Actions. 
@raymondfeng, thoughts?

**Comment by dhmlau** [comment]
Also `loopback-component-storage` reached end of life, so there's no need to move to GH Actions.

**Comment by bajtos** [comment]
AFAICT, `loopback-connector-openapi` does not require any special setup, it's just `npm install` and `npm test`. The transition from Travis to GitHub action should be pretty trivial.

See [`loopback-connector-openapi/.travis.yml`](https://github.com/strongloop/loopback-connector-openapi/blob/8db05a578b3fe8e5183b4fa0ef5b616768d944ad/.travis.yml):

```yaml
language: node_js
node_js:
 - 10
 - 12
 - 14
```

(It would be great to remove Node.js 10 and add Node.js 15 to the build matrix after the migration is done.)

**Comment by bajtos** [comment]
> (It would be great to remove Node.js 10 and add Node.js 15 to the build matrix after the migration is done.)

Well, Node.js 10 is reaching end of life on 2021-04-30, so we should keep it for few more weeks.
