### ISSUE TITLE
express middleware not executed in sequence

### ISSUE THREAD

**Issue by sf-kansara** [loopbackio/loopback-next#7089]
## Steps to reproduce
1. Create todo app with `lb4 example` and select todo app
2. Add `morgan` express middleware as [specified in documentation](https://loopback.io/doc/en/lb4/Express-middleware.html#register-express-middleware-to-be-executed-by-invokemiddleware-actions).

## Current Behavior
Sequence does not execute morgan middleware with `this.invokeMiddleware()`

## Expected Behavior
Sequece should execute morgan middleware with `this.invokeMiddleware()`

## Link to reproduction sandbox
https://github.com/sf-kansara/lb4-express-middleware

## Additional information
linux x64 12.20.0
@loopback/example-todo@3.9.3 /home/dell/dev/loopback4-example-todo
├── @loopback/boot@3.2.0
├── @loopback/core@2.14.0
├── @loopback/repository@3.4.0
├── @loopback/rest@9.1.2
├── @loopback/rest-explorer@3.0.6
├── @loopback/service-proxy@3.0.6
├── loopback-connector-rest@4.0.1

**Comment by achrinza** [comment]
Looks like the reproduction sandbox is using the old [sequence-bassed middleware](https://github.com/sf-kansara/lb4-express-middleware/blob/6a817f3d6e13f722fdb291c89cb25d17d16615a1/src/sequence.ts). Could you try using the new [middleware-based sequence](https://loopback.io/doc/en/lb4/REST-middleware-sequence.html) instead?

```typescript
# src/sequence.ts (middleware-based)

import {MiddlewareSequence} from '@loopback/rest';

export class MySequence extends MiddlewareSequence {}
```

On a side-note; I noticed that the [linked docs](https://github.com/strongloop/loopback-next/blob/86aa11aed5afb358891e6a6c9d6b01e2a493585b/docs/site/Express-middleware.md#invoke-express-middleware-explicitly-in-the-sequence) provided an example on using the sequence-based approach; We should probably update that to include the middleware-based approach too.
