### ISSUE TITLE
Add  --tables/--models arguments to `lb4 discover` command

### ISSUE THREAD

**Issue by rigibore-charlie** [loopbackio/loopback-next#7104]
## Suggestion

Add arguments `--tables` or `--models` to `lb4 discover` command.

## Use Cases

I'm a new user to Loopback trying to create a REST API for two large existing SQL Server databases, each database has in excess of 200 tables spanning 8+ schemas, and scrolling the list in the interactive prompts to find just the 8 tables required is near impossible, and made worse by the fact that the results don't seem to be in any particular order...?

![image](https://user-images.githubusercontent.com/63846513/107537750-26dce800-6bbb-11eb-81bf-0fe408ef8bd0.png)

This would also allow you to selectively discover models later in development much easier.

## Examples

`lb4 discover --tables=customers,contacts,quotes,parts`
`lb4 discover --models=customers,contacts,quotes,parts`

**Comment by dhmlau** [comment]
Transferred!

**Comment by dhmlau** [comment]
It would be a useful feature. For database migration, we can list which models to migrate, but not for discovery.

**Comment by igbenic** [comment]
Any other way of doing this in the meantime? I have 2500 tables, impossible navigate with CLI

**Comment by prespic** [comment]
WORKAROUND:

` lb4 discover --all --outDir=src/models/all`

Generates all models. Then you can easily pick the right ones and remove the others.

**Comment by aaqilniz** [comment]
`lb4 discover --model` is available now. Have a look at the [PR](https://github.com/loopbackio/loopback-next/pull/9092).
