### ISSUE TITLE
Prompt issue by creating datasource with specified config

### ISSUE THREAD

**Issue by canmustu** [loopbackio/loopback-next#7361]
## Steps to reproduce

I specified all options to create datasource not to prompt me any question but It still prompts me the all fields. Prompt me the connector and then url, host, port etc.
I tried these options by passing config file and other way which is `--connector mongodb` way but same behaviour.

My `config.json`
```
{
  "connector": "mongodb",
  "url": "",
  "host": "localhost",
  "port": "27017",
  "user": "",
  "password": "",
  "database": "test",
  "useNewUrlParser": true,
  "skipInstall": true,
  "skipCache": true
}
```

My datasource creation `CLI command`:

```
lb4 datasource test --config config.json
```

## Current Behavior

Prompt me to choose a connector:

```
? Select the connector for test:  (Use arrow keys)
❯ In-memory db (supported by StrongLoop) 
  In-memory key-value connector (supported by StrongLoop) 
  IBM Object Storage (supported by StrongLoop) 
  IBM Db2 (for Linux, Unix, Windows) (supported by StrongLoop) 
  IBM i (Db2 for i) (supported by StrongLoop) 
  IBM Db2 for z/OS (supported by StrongLoop) 
  IBM DashDB (supported by StrongLoop) 
(Move up and down to reveal more choices)
```

## Expected Behavior

Generating datasource by specified config without any prompt.

**Comment by pktippa** [comment]
@canmustu As suggested in https://github.com/strongloop/loopback-next/issues/7362#issuecomment-830781408 please try and check 

```sh
$ lb4 datasource test --config config.json --yes
```
