### ISSUE TITLE
Prompt issue by creating repository with specified config

### ISSUE THREAD

**Issue by canmustu** [loopbackio/loopback-next#7362]
## Steps to reproduce

I specified all options to create repository not to prompt me any question but It still prompts me the repository base class.
I tried these options by passing config file and other way which is `--repositoryBaseClass DefaultCrudRepository` way but same behaviour.

My `config.json`
```
{
  "datasource": "test",
  "model": "test",
  "repositoryBaseClass": "DefaultCrudRepository"
}
```

My repository creation `CLI command`:

```
b4 repository test --config config.json
```

## Current Behavior

Prompt me to choose a repository base class:

```
? Please select the repository base class (Use arrow keys)
❯ DefaultCrudRepository (Juggler bridge) 
  ----- Custom Repositories -----
```

## Expected Behavior

Generating repository by specified config without any prompt.

**Comment by pktippa** [comment]
@canmustu as per https://loopback.io/doc/en/lb4/Repository-generator.html#notes
could you please try with **-y, --yes** `Skip all confirmation prompts with default or provided value`

like
```sh
$ lb4 repository test --config config.json --yes
```
