### ISSUE TITLE
@response decorator bug cause removing of security scheme object from route specs

### ISSUE THREAD

**Issue by Niks218** [loopbackio/loopback-next#7420]
## Steps to reproduce

1. Add `@authenticate` decorator to controller or its method.
2. Add `@oas.response` decorator to the same method.
3. Check generated openapi scheme

```typescript
export class MainController {
  constructor() {}

  @response(500, GenericError)
  @authenticate('basic')
  @get('/test')
  test() {
    return;
  }
}
```

## Current Behavior

No authentication provided for this route

## Expected Behavior
Every route, secured with `@authenticate` decorator must have security object in its spec

## Link to reproduction sandbox

https://github.com/Niks218/loopback-security-scheme

## Additional information

linux x64 14.15.1

loopback-security-scheme@0.0.1 /home/nikita/loopback-security-scheme
├── @loopback/authentication@7.2.0
├── @loopback/boot@3.3.1
├── @loopback/core@2.15.1
├── @loopback/repository@3.5.1
├── @loopback/rest-explorer@3.2.1
├── @loopback/rest@9.2.1
├── @loopback/security@0.4.1
├── @loopback/service-proxy@3.1.1

Most likely the problem is in `@response` decorator, since everything is fine without it. Maybe it's because `allowInheritance: false` option it passes to `createDecorator` function

**Comment by marioestradarosa** [comment]
@Niks218 have you tried to change the order on the decorator as such:

Notice the authenticate goes first in this example.


```ts
  @authenticate('basic')
  @response(500, GenericError)
  @get('/test')
   test() {
     return;
  }

```

**Comment by Niks218** [comment]
Yes, I tried it both ways

**Comment by achrinza** [comment]
Closed by https://github.com/loopbackio/loopback-next/pull/8563
