### ISSUE TITLE
loopback-datasource-juggler depends on shortid, which is deprecated

### ISSUE THREAD

**Issue by jaishirole** [loopbackio/loopback-next#7584]
The 'shortid' dependency is deprecated and suggests the use of 'nanoid' instead.

From: https://github.com/dylang/shortid
>shortid is deprecated, because the architecture is unsafe. we instead recommend Nano ID, which has the advantage of also being significantly faster than shortid

The README.md of shortid has a line on screenshots being licensed under 'CC-BY-SA' whereas the nanoid has no such mention. It seemed problematic.

In short, moving dependency from shortid to nanoid will help with
1. supported module
2. no legal concerns.

Note: While creating issue in juggler repo, the first comment said that if using loopback4 raise the issue in this repo.

**Comment by achrinza** [comment]
Closed by https://github.com/loopbackio/loopback-datasource-juggler/pull/1903

**Comment by jaishirole** [comment]
@achrinza @marioestradarosa 
I see that the file package.json (https://github.com/loopbackio/loopback-datasource-juggler/blob/fe82f6ac7919138e91c2690c5482ff8eb9b58215/package.json#L61) has the change reflected, but the latest tagged 4.26.0 version at npmjs (https://www.npmjs.com/package/loopback-datasource-juggler) still has the 'shortid' dependency.
It seems the code change hasn't made it to a published release.
The `npm audit` tool continues to report this as a moderate vulnerability.
Any idea, by when this would show up in a release that `lb4 update` will reflect for us the consumers ?

**Comment by jaishirole** [comment]
@dhmlau Can you help get some update on above comment? The 'npm audit' continues to show us the vulnerabilities and I look forward to juggler package versioned higher than 4.26.0 to be available in npmjs library.

**Comment by achrinza** [comment]
Sorry for the delay @jaishirole. We'll cut a new release alongside with the rest LoopBack 4 sometime this week.
