### ISSUE TITLE
Filter With Complex Query , Where -> and with or Issue with last Object Parse

### ISSUE THREAD

**Issue by sohaibahsan007** [loopbackio/loopback-next#7756]
For Example, if you have a query

```
filter[where][and][0][or][0][status]:approve
filter[where][and][0][or][1][status]:processed
```
when you run this, then in API, the status column is coming as `[status]` instead of `status`. which is a retuning error in Postgres SQL.  in where it's working fine and status is parsed as status.

this is the value in API: `[ { '[status]': 'approve' }, { '[status]': 'processed' } ]` , in this `[status]`should be `status`.

I think on 5th child, it's not fetching objects.

**Comment by achrinza** [comment]
You might be running up a hard limit preset for [`qs`](https://www.npmjs.com/package/qs):

https://github.com/loopbackio/loopback-next/issues/6222

A method around this is to used stringified JSON instead.

**Comment by sohaibahsan007** [comment]
Thank you @achrinza
