### ISSUE TITLE
@loopback/cron runOnInit option not working and preventing the app to start correctly

### ISSUE THREAD

**Issue by hessman** [loopbackio/loopback-next#7841]
## Steps to reproduce

On a basic project created with `@loopback/cli` or not :
* use `runOnInit: true`  in the configuration of a CronJob
* use a non-static method of the CronJob in the `onTick` callback
* start the project

```
import {CronJob, cronJob} from '@loopback/cron';

@cronJob()
class TestJob extends CronJob {
  constructor() {
    super({
      name: 'test-job',
      onTick: () => {
        this.helloWorld()
      },
      cronTime: '* * * * * *',
      runOnInit: true,
    });
  }

  helloWorld() {
    console.log('Hello world !');
  }
}

export default TestJob;
```

## Current Behavior

An error prevent the application to start correctly :

```
Cannot start the application. ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at TestJob.onTick (/home/hessman/Documents/sdbox/cron-sandbox/src/crons/test.cron.ts:9:9)
    at TestJob.fireOnTick (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/cron/lib/cron.js:600:23)
    at new CronJob (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/cron/lib/cron.js:572:15)
    at new CronJob (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/cron/src/types.ts:49:5)
    at new TestJob (/home/hessman/Documents/sdbox/cron-sandbox/src/crons/test.cron.ts:6:5)
    at /home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/resolver.ts:76:14
    at Object.transformValueOrPromise (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/value-promise.ts:298:12)
    at Object.instantiateClass (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/resolver.ts:69:35)
    at /home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/binding.ts:883:21
    at Binding._getValue (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/binding.ts:721:14)
    at /home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/binding.ts:545:23
    at /home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/resolution-session.ts:109:13
    at tryCatchFinally (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/value-promise.ts:222:14)
    at Object.tryWithFinally (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/value-promise.ts:197:10)
    at Function.runWithBinding (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/resolution-session.ts:108:12)
    at Binding.getValue (/home/hessman/Documents/sdbox/cron-sandbox/node_modules/@loopback/context/src/binding.ts:535:40)
```

## Expected Behavior

The CronJob should be triggered on application init :
* No error should be thrown
* The task of the CronJob should immediately be triggered

## Link to reproduction sandbox

I made a basic sandbox with minimal features to reproduce the bug : https://github.com/hessman/loopback-cron-bug

You just need to :

```
git clone https://github.com/hessman/loopback-cron-bug
cd loopback-cron-bug
npm i
npm start
```

## Additional information

linux x64 12.22.3

├── @loopback/boot@3.4.2
├── @loopback/core@2.16.2
├── @loopback/cron@0.5.2
├── @loopback/repository@3.7.1
├── @loopback/rest@10.0.0
├── @loopback/rest-explorer@3.3.2
├── @loopback/service-proxy@3.2.2

## Related Issues

No related issues found.

**Comment by achrinza** [comment]
Thanks for creating the sandbox, @hessman! Unfortunately this is a JavaScript thing - `this` cannot be referenced before `super()` is called (nor can it be referenced within `super()` itself).

> use a non-static method

Are there certain limitations with using a static class member?

Or as an alternative, could `helloWorld` be extracted into its own class, and have `TestJob` initialize an instance of that class in the constructor?

**Comment by NorthBlue333** [comment]
Hi @achrinza!
I am facing the same issue. When using services injections, would you recommend argument injections in static methods instead of using constructor injections, which would allow not to use `this` ?

Thank you for your answer :)

**Comment by mrmodise** [comment]
Hope it helps:

```typescript
import {CronJob, cronJob} from '@loopback/cron';
import {inject} from '@loopback/context';
import {CachingComponentBindings, RedisConnector} from '..';
import {log} from '..';

function everyHour() {
  return '0 * * * *';
}

@cronJob()
export class DevCacheCronJob extends CronJob {
  constructor(
    @inject(CachingComponentBindings.SINGLETON.key)
    protected redisConnector: RedisConnector,
  ) {
    super({
      name: 'every-2-hours',
      onTick: () => {
        if (process.env.DEPLOY_ENV === 'dev') {
          this.redisConnector
            .deleteAll()
            .then(r => log.info(r))
            .catch(e => log.error(e));
        }
      },
      cronTime: everyHour(),
      start: false,
    });
  }
}
```

**Comment by NorthBlue333** [comment]
Thanks for your answer @mrmodise but this does not help. You have not set `runOnInit` to `true` in your exemple, which is the issue here.

**Comment by hessman** [comment]
@achrinza thanks for your response, I know this is a javascript issue but what is the best practice with the loopback UX ? 
As you know, we often need to inject services or repositories, if we cannot use this on this implementation of cron it's problematic. 
We should inject on the method and not the class ? The documentation is not describing the best practice for the usage of service/repo and runOnInit.

**Comment by achrinza** [comment]
Thanks for the clarification @hessman; I believe that @mrmodise's code should work; I've tested a similar code with `runOnInit` and _constructor injection_ and got it working:

```typescript
import {service} from '@loopback/core';
import {cronJob, CronJob} from "@loopback/cron";
import {TickService} from '../services';

@cronJob()
export class MainSchedulerCron extends CronJob {
  constructor(
    @service(TickService)
    tickService: TickService,
  ) {
    super({
      name: 'main-scheduler',
      cronTime: '*/5 * * * * *',
      onTick: tickService.sayTick,
      onComplete: function () {console.log(this.name + ' completed')},
      start: false,
      runOnInit: true,
    });

    this.onError(err => {
      console.error('cron error: ' + err)
    })
  }
}
```

Hope it helps!

**Comment by hessman** [comment]
Thanks it helps ! 😀

**Comment by hessman** [comment]
Thanks it helps ! 😀
