### ISSUE TITLE
Add POST example to Calling REST APIs

### ISSUE THREAD

**Issue by mrmodise** [loopbackio/loopback-next#7947]
The [Calling REST APIs](https://loopback.io/doc/en/lb4/Calling-rest-apis.html) section demonstrates how to use LoopBack 4 to call GET APIs. It would be benefiting to the broader community to demonstrate how to call POST APIs. I have the [todo-jwt](https://test-loopback-4-deployment.herokuapp.com/explorer/#/UserController/UserController.signUp) example hosted in Heroku that could be used in the documentation to help illustrate the practical aspects of the topic. Feel free to use any open source POST API or placeholders to demonstrate the idea

## Acceptance criteria

- [ ] Split the page into 2 sections; a) calling GET APIs and b) calling POST APIs
- [ ] Include step by step instructions of how to set up the 2 types of API calls
- [ ] Provide evidence of what the success or failure result would look like 
- [ ] Include Common Task section that links out to further readings on the topics discussed such as datasources, controllers, services and models

**Comment by Ashwithabg** [comment]
Can I work on this change?

**Comment by mrmodise** [comment]
Thanks for your interest. Please go ahead @Ashwithabg

**Comment by neel-desh** [comment]
@dhmlau can I pick this up?

**Comment by neel-desh** [comment]
I might not be able to pick this. sorry. Someone else could go ahead and pick this up.

**Comment by BharathA14** [comment]
Can i pick this up?
