### ISSUE TITLE
lb4 datasource --config results in an error - "function () { [native code] }" is generated

### ISSUE THREAD

**Issue by xw-patrick** [loopbackio/loopback-next#8089]
## Steps to reproduce

create a new data source with --config
`lb4 datasource -c '{"name": "dbname","connector": "postgresql", "url": "", "host": "psql-svc", "port": "5432", "user": "psql", "password": "pw", "database": "dbname"}' -y` 
then start the lb4 app:
`npm start`

creates errors like:
```src/datasources/test.datasource.ts:37:36 - error TS1005: ',' expected.

37         log: function () { [native code] },
```

When I use the exact same values through using the prompt, there are no issues when starting the lb4 app.

## Current Behavior

creates errors like:
```src/datasources/test.datasource.ts:37:36 - error TS1005: ',' expected.

37         log: function () { [native code] },
                                      ~~~~

src/datasources/test.datasource.ts:38:37 - error TS1005: ',' expected.

38         warn: function () { [native code] },
                                       ~~~~

src/datasources/test.datasource.ts:39:36 - error TS1005: ',' expected.

39         dir: function () { [native code] },
                                      ~~~~

src/datasources/test.datasource.ts:40:37 - error TS1005: ',' expected.

40         time: function () { [native code] },
                                       ~~~~
```
etc...

## Expected Behavior

The lb4 application should start with no errors - as when using the prompt process.
Interestingly, creating the datasource works when using 

## Additional information

`$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 16.13.0
`

`$ npm ls --prod --depth 0 | grep loopback
+-- @loopback/boot@4.0.0
+-- @loopback/cli@3.0.0
+-- @loopback/core@3.0.0
+-- @loopback/repository@4.0.0
+-- @loopback/rest-explorer@4.0.0
+-- @loopback/rest@11.0.0
+-- @loopback/service-proxy@4.0.0`

## Related Issues

Many issues reported that a prompt appears - but it doesn't when using the -y flag.
But haven't found anyone reporting the issue that the data source doesn't work when created using --config.

**Comment by kreuzwerker-patrick** [comment]
Anyone interested to help with this?
https://www.upwork.com/jobs/~01fe3de0ce6c6c4737
You have the chance to contribute to an open source project and get paid for it :-)
