### ISSUE TITLE
ENOENT: no such file or directory, scandir '[dir]/_.gitignore'

### ISSUE THREAD

**Issue by l0u1sg** [loopbackio/loopback-next#8115]
Hello everyone

I'm trying to start a project with loopback, but I have a problem when I want to initialize it with the `lb4 app` command the questions work and as soon as it starts to initialize it I get this error like it can't find the gitignore. Do you have a solution?

I use
NodeJS : v17.1.0
NPM : v8.1.2
Yarn v1.22.5 (My default package manager)

**Comment by achrinza** [comment]
Hi @l0u1sg, as per-the [bug template](https://github.com/loopbackio/loopback-next/issues/new?assignees=&labels=bug&template=Bug_report.md), could you please provide the following information?

- Platform OS and architecture (`node -e 'console.log(process.platform, process.arch, process.versions.node)')
- LoopBack CLI version (`npm ls --global --depth=0 | grep loopback` if installed globally)

**Comment by l0u1sg** [comment]
Yep, sorry :
- MacOS High Sierra 10.13.6 ; darwin x64 17.1.0
- @loopback/cli version: 3.0.0

**Comment by achrinza** [comment]
Thanks; I wasn't able to replicate it with  macOS Big Sur.

Could you please try the following:

1. Reinstall and re-run the CLI
    ```sh
    npm uninstall --global @loopback/cli
    npm install --global @loopback/cli
    lb4
   ```
2. Use `npx`
    ```sh
    $ npx @loopback/cli
    ```

/cc: @dhmlau Would you be able to test this?

**Comment by jbovatsek** [comment]
I had this issue as well:
win32 x64 17.2.0
@loopback/cli@3.0.0

A workaround that worked for me is to downgrade to Node 16.9.1

**Comment by l0u1sg** [comment]
Ok I will try to downgrade my node

**Comment by dhmlau** [comment]
@achrinza, I'm also on macOS Big Sur.
I have the following Node.js and npm versions and `lb4` seems to run fine for me:
Node.js - v16.13.1, also tried v17.2.0
npm - v8.1.4

**Comment by l0u1sg** [comment]
I don't know why, but after a reboot of my mac, it works. Thanks for your help
