### ISSUE TITLE
swagger-dist-ui dependency needs an upgrade

### ISSUE THREAD

**Issue by fidgi** [loopbackio/loopback-next#8116]
## Steps to reproduce

run npm audit

## Current Behavior

# npm audit report

swagger-ui-dist  
Severity: moderate
Server side request forgery in SwaggerUI - https://github.com/advisories/GHSA-qrmm-w75w-3wpx
No fix available
node_modules/swagger-ui-dist
  @loopback/rest-explorer  
  Depends on vulnerable versions of swagger-ui-dist
  node_modules/@loopback/rest-explorer

2 moderate severity vulnerabilities

## Expected Behavior

No moderate or higher vulnerability reported by npm audit

Apply recommanded workaround (https://github.com/advisories/GHSA-qrmm-w75w-3wpx) or move to version swagger-ui 4.1.3

## Link to reproduction sandbox

N/A

## Additional information
linux x64 16.13.1
├── @loopback/boot@4.0.0
├── @loopback/context@4.0.0
├── @loopback/core@3.0.0
├── @loopback/openapi-v3@7.0.0
├── @loopback/repository@4.0.0
├── @loopback/rest-explorer@4.0.0
├── @loopback/rest@11.0.0
├── @loopback/service-proxy@4.0.0

## Related Issues
None

**Comment by frbuceta** [comment]
It will be updated when we launch a new version of our package

**Comment by rakeshp89** [comment]
@frbuceta - Can you please let us know as to when the package (@loopback/rest-explorer) will be updated on npmjs? The version shows it was updated 2 months ago. Thanks in advance
 https://www.npmjs.com/package/@loopback/rest-explorer

**Comment by frbuceta** [comment]
> @frbuceta - Can you please let us know as to when the package (@loopback/rest-explorer) will be updated on npmjs with the updated swagger-ui-dist version? The version shows it was updated 2 months ago. Thanks in advance https://www.npmjs.com/package/@loopback/rest-explorer

This week the team will do an update on all packages. Sorry for the delay.

**Comment by achrinza** [comment]
A release has been published: https://github.com/loopbackio/loopback-next/commit/4a8886403cd9cb3ae529cb69712f077623cba2c2

**Comment by rakeshp89** [comment]
@achrinza @frbuceta - Thank you very much for the update.
