### ISSUE TITLE
Wrong glob generated when using a nested directory or array of directories in booters options

### ISSUE THREAD

**Issue by vvandens** [loopbackio/loopback-next#8201]
### Describe the bug

Setting `dirs` to either a directory or an array of directories in a booter options generates a bad glob pattern under the hood when one of the dir path is deeply nested (i.e. contains a `/` in its relative path).

When setting `dirs: ['dirA/sub', 'dirB']` in a booter options, the glob directories part generated is : `@(dirA/sub|dirB)` from `BaseArtifactBooter.configure()`. This breaks the loading of the resources from both directories. Same applies for a single nested directory `dirs: 'dirA/sub'`.  `@` pattern matching should not be used for directories, only for extensions.

To solve the issue, a *brace expansion* should be generated for dirs, i.e. `{dirA/sub,dirB}`, when dirs is an array and *nothing at all* when it's a single string.

### Reproduction

https://codesandbox.io/s/vigorous-andras-fhpeb?file=/src/application.ts

**Comment by achrinza** [comment]
Thanks for opening the issue, @vvandens! I was able to replicate it at my end.

For others' future reference, this "limitation" has been documented by the `node-glob` maintainer himself: https://github.com/isaacs/node-glob/issues/278#issuecomment-237291298

A workaround for now is to use `glob` which will take precedence over the other options.

**Comment by vvandens** [comment]
Thanks for the feedback @achrinza.
Reading your pending fix, I don't think that it will work when `dirs` is set as a string pointing to a nested directory (i.e. `dirs: 'dir/sub'`). *Brace expansion* will only work when there is  more than one expression passed to it. In this case, I believe that the directory string should be used as-is when constructing the `glob`.

**Comment by achrinza** [comment]
Thanks for the clarification, @vvandens. You're right, brace expansion does not work for single expressions. I've updated the PR.
