### ISSUE TITLE
Automatic linter enforcing our file naming convention

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#833]
In #612, we are starting a file naming convention based on Angular style:

```
src/decorators/authenticate.decorator.ts
```

To avoid unnecessary discussions on GitHub, we should have an automated tool that will check the convention is honored and that will be run as part of our CI setup.

**Comment by privateOmega** [comment]
@bajtos I am guessing you could use [fs-lint](https://www.npmjs.com/package/fs-lint) to the CI setup.

**Comment by bajtos** [comment]
@privateOmega nice, thank you for the link! Does fs-lint allow us to specify that all files in `decorators` directory must have `.decorator` suffix? IIUC fs-link's documentation, this is cannot be enforced right now. Could you perhaps help us by contributing a pull request to fs-link to add support for custom naming patterns?

**Comment by privateOmega** [comment]
@bajtos Okay. Well I recently found another project [fnlint](https://github.com/usabilla/fnlint). Even though that project doesn't support the required feature, I have coded our requirement into it and created a PR. Awaiting review and merge. As soon as it's done, I hope it can be added to the CI pipeline.

**Comment by privateOmega** [comment]
@bajtos Finally fnlint has merged the file extension linting. I hope this provides support for required use-case.

**Comment by bajtos** [comment]
@privateOmega nice! Would you like to contribute this change to loopback-next yourself?
