### ISSUE TITLE
[BUG]: @service() + asProxyWithInterceptors not work!

### ISSUE THREAD

**Issue by skypesky** [loopbackio/loopback-next#8357]
# What is the problem
When I use the global interceptor:
method `@inject() + asProxyWithInterceptors` work.
but, method `@service() + asProxyWithInterceptors` doesn't work.
```typescript
export class UserController {
  constructor(
    // proxy success
    @inject(`Services.ProxySuccessService`, {asProxyWithInterceptors: true})
    private proxySuccessService: ProxySuccessService,

    // proxy fail !!!
    @service(ProxyFailService, {asProxyWithInterceptors: true})
    private proxyFailService: ProxyFailService,
  ) { }

  @get('/users/proxy')
  public async existsByUsername(): Promise<void> {
    await this.proxySuccessService.work();
    await this.proxyFailService.work();
  }

}
```

# Expected behavior

- console log output:

```cmd
ProxySuccessService#work() interceptor success!
ProxySuccessService loaded!
ProxyFailService#work() interceptor success!
ProxyFailService loaded!
```

# Actual behavior

- console log output: Missing log => `ProxyFailService#work() interceptor success!`
```cmd
ProxySuccessService#work() interceptor success!
ProxySuccessService loaded!
ProxyFailService loaded!
```

# How to reproduce the problem

1. git clone https://github.com/skypesky/loopback4-proxy-issue
2. npm install 
3. npm start
4. visit url [http://[::1]:3000/users/work](http://[::1]:3000/users/work)
5. view console log output

### Reproduction

https://github.com/skypesky/loopback4-proxy-issue

**Comment by raymondfeng** [comment]
@skypesky Thank you for reporting the issue. Please verify the fix in #8358.

**Comment by skypesky** [comment]
@raymondfeng @achrinza 
Thank you for your help. I think the submitted PR(#8358) has achieved the expected results.
(Because I saw you write the test, do I need to do additional verification for this?)

**Comment by skypesky** [comment]
I found that this proxy method is not supported: `@repository + asProxyWithInterceptors`.
This way we are forced to use inject....
```typescript
export class UserController {
  constructor(

    // not support !
    @repository(UserRepository, {asProxyWithInterceptors: true})
    private userRepository: UserRepository,

  ) { }

}
```
