### ISSUE TITLE
ejs dependancy needs an upgrade

### ISSUE THREAD

**Issue by clewisln** [loopbackio/loopback-next#8479]
## Steps to reproduce

run npm audit
## Current Behavior
# npm audit report
```
async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
fix available via `npm audit fix --force`
Will install @loopback/rest-explorer@2.1.1, which is a breaking change
node_modules/async
  jake  >=8.0.1
  Depends on vulnerable versions of async
  node_modules/jake
    ejs  >=3.1.2
    Depends on vulnerable versions of jake
    node_modules/ejs
      @loopback/rest-explorer  >=2.1.2
      Depends on vulnerable versions of @loopback/rest
      Depends on vulnerable versions of ejs
      node_modules/@loopback/rest-explorer
      strong-error-handler  >=3.5.0
      Depends on vulnerable versions of ejs
      node_modules/strong-error-handler
        @loopback/rest  >=5.2.0
        Depends on vulnerable versions of strong-error-handler
        node_modules/@loopback/rest
          @loopback/authentication  >=4.2.9
          Depends on vulnerable versions of @loopback/rest
          node_modules/@loopback/authentication
          @loopback/authentication-jwt  >=0.4.3
          Depends on vulnerable versions of @loopback/rest
          node_modules/@loopback/authentication-jwt
```

8 high severity vulnerabilities
## Expected Behavior
No moderate or higher vulnerability reported by npm audit

## Additional information
The project dependencies are compatible with @loopback/cli@3.2.0

Deps 
├── @loopback/authentication-jwt@0.11.2
├── @loopback/authentication@8.1.2
├── @loopback/authorization@0.11.2
├── @loopback/boot@4.1.2
├── @loopback/build@8.1.2
├── @loopback/core@3.1.2
├── @loopback/eslint-config@12.0.4
├── @loopback/repository@4.1.2
├── @loopback/rest-explorer@4.1.2
├── @loopback/rest@11.1.2
├── @loopback/service-proxy@4.1.2
├── @loopback/socketio@0.5.2

## Related Issues

None

### Reproduction

n/a

**Comment by frbuceta** [comment]
https://github.com/loopbackio/loopback-next/blob/23ce18084714cbae16469ec325540f173f6789f6/packages/rest-explorer/package.json#L45

The EJS dependency is up to date

**Comment by clewisln** [comment]
@frbuceta, my rest explorer is at version 4.1.2, the latest.

**Comment by frbuceta** [comment]
> @frbuceta, my rest explorer is at version 4.1.2, the latest.

Can you tell me if your problem could be this? https://github.com/loopbackio/loopback-next/issues/8478

**Comment by clewisln** [comment]
@frbuceta, yes, it is the same issue.

I posted the full audit log in the ticket, which you can see "async" at the top of the tree.

The common package that _loopback_ references, which depends on the vulnerable async module, is ejs. That is why this ticket is calling out the ejs module instead of async.

**Comment by achrinza** [comment]
I'll re-open the issue for now, but regardless of the issue status, it's currently not actionable from our end and, AFAIK, only affect the `devDependencies` tree (i.e. It doesn't affect production installation and deployments).

@renovate-bot will automatically bump all of our dependencies when they come through.

**Comment by clewisln** [comment]
@achrinza, understood.

I have, these past few days, learned how some of these audit reports are false positives; so apologies for any churn.

**Comment by fidgi** [comment]
@achrinza jake is in the production dependency tree of ejs which is in the production dependency tree of strong-error-handler , etc ... so IMHO, it might affect application based on loopback-next/rest package .

The good news is that the resolution is on it way out : https://github.com/jakejs/jake/commit/6470ead916cc244bd2e9a17b7a9b829754889704

**Comment by achrinza** [comment]
Closing this as solved.

From https://github.com/loopbackio/loopback-next/pull/8486#issuecomment-1103915691:

> Since the fixes are applied within the existing dependencies' semver range, the benefits are already propagated to the users without any action from the LoopBack Maintainers.
