### ISSUE TITLE
lb4 app command on win10 does not work

### ISSUE THREAD

**Issue by meir100** [loopbackio/loopback-next#8484]
### Describe the bug

try to install loopback4 on win10-pro + node 16.14.2 
npm i -g @loopback/cli  works, but: lb4 app does not work.

'lb4' is not recognized as an internal or external command,
operable program or batch file.

### Reproduction

lb4 app

**Comment by achrinza** [comment]
These errors are typically caused by an environment-specific issue (e.g. improper `PATH`). The general recommendation is to re-install Node.js LTS and/or use `npx @loopback/cli`.

Unfortunately we can't provide any more help beyond that as historically these issues are hard to debug.
