### ISSUE TITLE
Loopback 4 auto generated model with required id failing validation

### ISSUE THREAD

**Issue by iluxav** [loopbackio/loopback-next#8572]
### Describe the bug

I'm using an automated script that runs an auto-generation model using lb4 cli. Looks like validation expects id to be provided, but swagger missing it in its schema. Why I can't see the id property in swagger?

PLEASE NOTE! I don't want to modify manually my models
(https://stackoverflow.com/questions/72141571/loopback-4-auto-generated-model-with-required-id-failing-validation)
lb4 model activity --dataSource DS --table activity
Created model:

```
export class Activity extends Entity {
  @property({
    type: 'string',
    required: true,
    id: 1,
    postgresql: {
      columnName: 'id',
      dataType: 'uuid',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  id: string;
...
}
```
When I run the swagger tool and try to POST new activity, it missing the id field and returns the following error:

```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Activity` instance is not valid. Details: `id` can't be blank (value: undefined).",
    "details": {
      "context": "Activity",
      "codes": {
        "id": [
          "presence"
        ]
      },
      "messages": {
        "id": [
          "can't be blank"
        ]
      }
    }
  }
}
```
If I add a property id manually, then it throws a validation error:

```
{
  "error": {
    "statusCode": 422,
    "name": "UnprocessableEntityError",
    "message": "The request body is invalid. See error object `details` property for more info.",
    "code": "VALIDATION_FAILED",
    "details": [
      {
        "path": "",
        "code": "additionalProperties",
        "message": "must NOT have additional properties",
        "info": {
          "additionalProperty": "id"
        }
      }
    ]
  }
}

```

### Additional information

https://stackoverflow.com/questions/72141571/loopback-4-auto-generated-model-with-required-id-failing-validation

### Reproduction

https://stackoverflow.com/questions/72141571/loopback-4-auto-generated-model-with-required-id-failing-validation

**Comment by achrinza** [comment]
> PLEASE NOTE! I don't want to modify manually my models

Could you clarify on this? Based on the code snippet provided, the model was either auto-generated using `lb4 discover`, or modified manually, as `lb4 model` does not generate database-specific fields.

**Comment by iluxav** [comment]
I don't have code pushed to git yet, it is a work in progress. Both the `lb4 discover` and `lb4 model` produces the same result. 
I'm using an example DB from here: https://www.mysqltutorial.org/mysql-sample-database.aspx

Commands are:
1. `lb4 app demo --applicationName mysq`
2. `lb4 datasource DS --connector mysql` - BTW, --connector prop doesn't work as well, the interactive menu shows up[ to select the db
3. `lb4 discover --schema classicmodels --dataSource DS`
4. `lb4 rest-crud`

**Comment by iluxav** [comment]
@achrinza  Apparently `lb4 rest-crud` when crates *`.rest-config.ts` files in `model-endpoints` folder by default omits all the primary keys. If I generate repository and then controller, in the menu I can select not to omit `id`  and it shows in the open-api UI. If I select to omit it, it will not appear there however I got a validation error.

**Comment by achrinza** [comment]
Thanks for the clarifications, @iluxav; The additional info cleared up quite a bit and I think I've got the full picture of the setup.

My understanding thus far is:

1. `lb4 model activity --dataSource DS --table activity` in the parent comment is supposed to be `lb4 discover`
2. `lb4 rest-crud` was used instead of the `lb4 controller` + `lb4 repository` combo

I'll try to replicate the issue at my end and get back on this.
