### ISSUE TITLE
CLI not detecting custom base repositories

### ISSUE THREAD

**Issue by deepaksinghsolanki1989** [loopbackio/loopback-next#8637]
### Describe the bug

I have recently updated my loopback 4 cli to version 4.0.0 that upgrade @loopback/repository from version 4.1.0 to 5.0.0. Now if I run **lb4 repository** command in the terminal then it is not showing the "Please select the repository base class" option i.e. it's not detecting my base repository class and directly generated repository with DefaultCrudRepository.

<img width="588" alt="Screenshot 2022-05-26 at 11 15 45 PM" src="https://user-images.githubusercontent.com/5346129/170545586-8c26cd35-1333-4978-ab47-9eedf99ee264.png">

Expected Result: Cli should display "Please select the repository base class" option and list custom repository

### Reproduction

https://github.com/deepaksinghsolanki1989/loopback-demo

**Comment by hardik-ebiz** [comment]
+1

**Comment by achrinza** [comment]
@hardik-ebiz Please use the ":+1:" reaction on the parent comment instead of commenting "+1", thanks!

**Comment by deepaksinghsolanki1989** [comment]
This issue is fixed with the below pull request:

https://github.com/loopbackio/loopback-next/pull/9238
