### ISSUE TITLE
change the loop

### ISSUE THREAD

**Issue by AhmedAlaufi** [loopbackio/loopback-next#8660]
### Describe the bug

use while loop instead of for efficiency @ 

### Additional information

use while loop instead of for efficiency @

### Reproduction

*

**Comment by dhmlau** [comment]
@AhmedAlaufi, thanks for your suggestion. Would you like to submit a PR and see how we can improve the code? Thanks.

**Comment by achrinza** [comment]
There isn't much info in this issue that showcases the performance improvements, and the reason behind it.

Hence, there isn't much that's actionable at the moment.

Closing it for now.
