### ISSUE TITLE
docs/site/Model.md

### ISSUE THREAD

**Issue by Momepukku** [loopbackio/loopback-next#8681]
### Describe the bug

invalid link on document page docs/site/Model.md

`- [Discover models from databases](DIscovering-models.md)`

should be
`- [Discover models from databases](Discovering-models.md)`

NOTE: capital letter "i"

### Reproduction
go to page https://loopback.io/doc/en/lb4/Model.html#common-tasks and click on the link "Discover models from databases"
ref: https://github.com/loopbackio/loopback-next/blame/master/docs/site/Model.md#L149

**Comment by dhmlau** [comment]
@Momepukku, would you be interested to submit a PR? thanks.
