### ISSUE TITLE
[Juggler] Spike: simplify DataAccessObject API 

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#897]
Remove data-access APIs we don't want to support anymore, both from juggler  and connectors, e.g. `updateOrCreate`, `findOrCreate`, etc.

See https://github.com/strongloop/loopback-next/issues/537#issuecomment-359005023

**Comment by achrinza** [comment]
Should we be removing these functions? I'm not too familiar with Juggler's codebase, but there are some potential benefits to keeping and/or revamping them:

- Reduce amt. of code for common actions
- Enforce atomic transactions
- Mitigate coding errors
