### ISSUE TITLE
[Blog] Why we decided to keep Juggler as our ORM

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#899]
Write a blog post about the discussion we had in https://github.com/strongloop/loopback-next/issues/537 and the decision we reached.

 - Explain why this discussion started in the first place
 - Summarize the arguments for keeping juggler and for switching to a different ORM
 - Explain why we decided to keep Juggler
 - Tell readers about the next steps we are planning

**Comment by shimks** [comment]
This should be given a priority (dp3 or non-dp3). I'd rather have this be part of DP3, but we may already be overloaded enough so I'm also ok with it being non-DP3 as well.

**Comment by dhmlau** [comment]
With "juggler-next" as the top of our backlog, I'd like this to mark as `tob` to explain our approach on "juggler-next".

**Comment by richardpringle** [comment]
@bajtos, any updates on a blog post date? (no pressure 😉)
