### ISSUE TITLE
entityToData method in legacy-juggler-bridge is not async function but mentioned as async

### ISSUE THREAD

**Issue by samarpanB** [loopbackio/loopback-next#9071]
### Describe the bug

This function here - https://github.com/loopbackio/loopback-next/blob/02778f373627ae6c5d61c5320e3019df3b6cda9d/packages/repository/src/repositories/legacy-juggler-bridge.ts#L785

Below here, this function is not doing any asynchronous operation so we dont need it to be async.

```
protected async entityToData<R extends T>(
    entity: R | DataObject<R>,
    options = {},
  ): Promise<legacy.ModelData<legacy.PersistedModel>> {
    return this.ensurePersistable(entity, options);
  }
```

### Reproduction

There are no side effects visible for this. It's just causing unnecessary promises await.

**Comment by cwiesenekker** [comment]
Hmmm. We actually do have written async code inside this function what now breaks. I also think that, if you have to do something here you always wnat this to be down with an await. So nonetheless the base code never used async code some of our extended repos does use this function and if we want to use it we surely want to be this async. Can you please undo this 'fix'?
