### ISSUE TITLE
lb4 command not found on windows 10.

### ISSUE THREAD

**Issue by arjunsubedi-varosa** [loopbackio/loopback-next#9095]
> **Maintainers' Note:** This has been posted elsewhere:
> - https://groups.google.com/d/msgid/loopbackjs/b0e92fd5-98fc-4ebe-9b88-7daf34ec3d
5dn@googlegroups.com

### Describe the bug

System information.
Windows 10,
Node Version: 16.15.1
Npm Version: 8.11.0

<img width="220" alt="lb4 not found" src="https://user-images.githubusercontent.com/118448464/202596198-fa9a1086-283f-47f4-a7ff-77a1a3c1a643.PNG">

### Logs

```shell
lb4 command not found
```

### Reproduction

https://github.com/arjunsubedi-varosa/loopback

**Comment by shubhamp-sf** [comment]
What were the logs when you ran `npm i -g @loopback/cli`?
Was there no error or warning during installation?

**Comment by achrinza** [comment]
I'll proceed to close this issue as it seems to have been resolved in the conversation at the loopback mailing list.
