### ISSUE TITLE
@loopback/cli fails to install when using Node.js 19

### ISSUE THREAD

**Issue by youssefhabri** [loopbackio/loopback-next#9120]
### Describe the bug

Hello,

The docs say that [here](https://loopback.io/doc/en/lb4/Getting-started.html#prerequisites) that we need node.js version 10 or higher, but it fails to install on v19.

I'm aware that node.js 19 only recently came out. I'm opening this issue simply to shed light on it, and hopefully have the cli's add support for node.js v19.

Thanks in advance.

### Additional information

I used `yarn global add @loopback/cli` to install, but I assume the same issue would arise when using npm, as this is simply a node version check, and only `14 || 16 || 17 || 18` are supported as per the `package.json`

### Reproduction

N/A

**Comment by mauriceKA** [comment]
I am facing the same issue. If this  is only because the declaration is not updated but the tests run also on v19, the engine dependency should be updated.
