### ISSUE TITLE
FULLTEXT | MYSQL | failed with status code 500. Error: ER_PARSE_ERROR: You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by MwSpaceLLC** [loopbackio/loopback-next#9133]
### Describe the bug

Hi there,

Today we try to fulltextsearch with mysql, after install system, and configure as follow:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/29952045/205524423-58e3ed74-0a2e-4408-a585-66696bf454bb.png">

Our application model:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/29952045/205525299-4c0c150c-d283-45a2-bdce-7e40e50f740c.png">

Our request crud (get):
<img width="623" alt="image" src="https://user-images.githubusercontent.com/29952045/205524485-65619562-fffc-47b3-a303-a3ee9b147501.png">

Server response:
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/29952045/205524523-3014d5e6-72c4-45df-93e5-d6ec8ff6a998.png">

System as installed with clear installation and clear mode, repo & crud generation.

### Additional information

Install loopback, generate model, add fulltextindex, add mysql datasource, query with match fulltext query

### Reproduction

Sorry, dataset has private, we can reproduce error with dataset demo.

**Comment by MwSpaceLLC** [comment]
https://github.com/loopbackio/loopback-connector-mysql/issues/475

**Comment by achrinza** [comment]
Hi @MwSpaceLLC, I'll proceed to close this issue in favour of the other one linked above so as to ease tracking.

I've added the other issue to the icebox for triaging.
