### ISSUE TITLE
npm test under packages/cli fails for one scenario

### ISSUE THREAD

**Issue by aaqilniz** [loopbackio/loopback-next#9180]
### Describe the bug

`npm test` fails under packages/cli for one of the test scenarios. The reason for this test failing is the fact that `$schema` under `tsconfig.json` in the examples under the repository has the value: `https://json.schemastore.org/tsconfig`. While the [examples available at npm registry](https://www.npmjs.com/package/@loopback/example-todo?activeTab=explore) has `http://json.schemastore.org/tsconfig`.

### Logs

```
1) lb4 example
       removes project references from tsconfig:

      AssertionError: expected Object {
  $schema: 'http://json.schemastore.org/tsconfig',
  extends: '@loopback/build/config/tsconfig.common.json',
  compilerOptions: Object { outDir: 'dist', rootDir: 'src', composite: false },
  include: Array [ 'src/**/*', 'src/**/*.json' ]
} to equal Object {
  $schema: 'https://json.schemastore.org/tsconfig',
  extends: '@loopback/build/config/tsconfig.common.json',
  compilerOptions: Object { outDir: 'dist', rootDir: 'src', composite: false },
  include: Array [ 'src/**/*', 'src/**/*.json' ]
} (at $schema, A has 'http://json.schemastore.org/tsconfig' and B has 'https://json.schemastore.org/tsconfig')
      + expected - actual

       {
      -  "$schema": "http://json.schemastore.org/tsconfig"
      +  "$schema": "https://json.schemastore.org/tsconfig"
         "compilerOptions": {
           "composite": false
           "outDir": "dist"
           "rootDir": "src"
      
      at Assertion.fail (/***/loopback-next/packages/testlab/node_modules/should/as-function.js:275:17)
      at Assertion.value (/***/loopback-next/packages/testlab/node_modules/should/as-function.js:356:19)
      at /***/loopback-next/packages/cli/test/integration/generators/example.integration.js:125:33
```

### Reproduction

https://github.com/loopbackio/loopback-next/tree/master/packages/cli

**Comment by aaqilniz** [comment]
Not sure if it is relevent but [this](https://github.com/loopbackio/loopback-next/blob/be8952dfcca0edfaf4d4bdb78d516c2c6ea941f2/packages/cli/generators/project/templates/tsconfig.json.ejs#L2) template tsconfig.json file has the $schema set to http://json.schemastore.org/tsconfig

**Comment by aaqilniz** [comment]
I think the tests are failing after [this](https://github.com/loopbackio/loopback-next/commit/be8952dfcca0edfaf4d4bdb78d516c2c6ea941f2) commit. Not sure if I got this correctly. Can you verify this @frbuceta.

**Comment by frbuceta** [comment]
> I think the tests are failing after [this](https://github.com/loopbackio/loopback-next/commit/be8952dfcca0edfaf4d4bdb78d516c2c6ea941f2) commit. Not sure if I got this correctly. Can you verify this @frbuceta.

It will be solved with the next release of the examples and the CLI.

**Comment by dhmlau** [comment]
Closing as resolved.
