### ISSUE TITLE
Set multiple properties as unique in lb4 model

### ISSUE THREAD

**Issue by himanshut0305** [loopbackio/loopback-next#9295]
### Describe the bug

while setting multiple property in lb4 as unique while using a mongodb datasource dont work, for example
`
import { Entity, model, property } from '@loopback/repository';
import { ObjectID } from 'mongodb';

@model()
export class User extends Entity {
  @property({
    type: 'string',
    id: true,
    mongodb: {
      dataType: 'ObjectID',
    },
  })
  id: ObjectID;

  @property({
    type: 'string',
    required: true,
    unique: true,
    index: {
      unique: true,
    },
  })
  email: string;

  @property({
    type: 'string',
    required: true,
    unique: true,
    index: {
      unique: true,
    },
  })
  username: string;

  @property({
    type: 'string',
    required: true,
  })
  password: string;
}
`
here both username and email property is set to unique still can create multiple entries with same username, or email?
Any help will be appreciated

### Reproduction

create a model with lb4 model cli and mark property as unique true in model class generated.

**Comment by nflaig** [comment]
Hey @himanshut0305  👋 

are the indexes created in the database? uniqueness is enforced there, not in the code, see [Mongodb Unique Indexes](https://www.mongodb.com/docs/manual/core/index-unique/).

LoopBack will create these indexes for you based on how you defined your models, just run `npm run migrate`.

You can learn more about [Database Migrations](https://loopback.io/doc/en/lb4/Database-migrations.html) in the docs.

**Comment by himanshut0305** [comment]
Thanks for the response, @nflaig will use mongo indexes.
