### ISSUE TITLE
Update Docs: allow defaultMetadata for methods not decorated with [@authenticate]

### ISSUE THREAD

**Issue by thiscode** [loopbackio/loopback-next#9338]
### Describe the bug

The Documentation describe howto to set a default authentication enforcement for methods that are not explicitly decorated with `@authenticate`. To do so, we have to configure the authentication component with defaultMetadata.

The doc example is:

```js
app
  .configure(AuthenticationBindings.COMPONENT)
  .to({defaultMetadata: {strategy: 'xyz'}});
```

But this is not working. You have to set `defaultMetadata` as an array:

```js
app
  .configure(AuthenticationBindings.COMPONENT)
  .to({defaultMetadata: [{strategy: 'xyz'}]});
```

Maybe since this Commit: `ae6c0e68a58a2b574fd534242e599aa2a96fc855`

### Additional information

Fixed in Fork/Branch:

https://github.com/thiscode/loopback-next/tree/update-docs-defaultMetadata

The sandbox contains two controller:

- ping: without decorator
- ping-auth: with decorator

In `application.ts` you will see the code as mentioned in the docs.

Result: The ping-controller is accessible without authentication.

### Reproduction

https://codesandbox.io/p/sandbox/still-star-0t9ogf?welcome=true&file=%2FREADME.md

**Comment by nflaig** [comment]
Thanks for highlighting this, seems like the docs are outdated. Would be great if you could open a PR with your changes
