### ISSUE TITLE
Bug 9071 wasnt a bug, now it creates bugs

### ISSUE THREAD

**Issue by cwiesenekker** [loopbackio/loopback-next#9374]
### Describe the bug

In https://github.com/loopbackio/loopback-next/issues/9071 the function entityToData removed the async sign which removed the ablitity to do some async await stuff inside that function. We are relying on that function to be async. In my humble opinion making that funciton non-async makes not a lot of sence since if you do something with the data in that function you surely want it to be async

### Reproduction

NA

**Comment by samarpanB** [comment]
@cwiesenekker Can you share an example where you are using this method as async ? I just need to ensure that we understand the use case.

**Comment by harshal619** [comment]
@samarpan-b 
For me, the use case was I was adding a few metadata properties to the instance by overriding entityToData function.
The advantage was I did not have to override all necessary CRUD operation methods.

Let us know if there is any plan to revert this.

**Comment by nflaig** [comment]
`entityToData` is commonly overriden  to modify an entity before persisting it. There is even a tutorial for this created by bajtos which outlines this approach (https://youtu.be/s2yDaKiNYCg?t=441), and even there it is async.

@samarpan-b what are the benefits of making this method sync? I think this change must be reverted as it was not properly highlighted as a breaking change.

**Comment by samarpanB** [comment]
Raised a PR for restoring it. Thanks for pointing out the use case @nflaig @harshal619 .
