### ISSUE TITLE
[@loopback/sequelize] Race condition / initialization issue for repository calls on application start up

### ISSUE THREAD

**Issue by KalleV** [loopbackio/loopback-next#9606]
### Describe the bug

When I tried replacing the juggler ORM with Sequelize, I started seeing errors like “cannot call findAll of undefined” on server start up.

I traced this to a delayed initialization issue. Stepping through with the debugger and breakpoints, I’m seeing repositories being constructed before the datasource “sequelize” property is initialized here: https://github.com/loopbackio/loopback-next/blob/e7f02ab659f0c9849c3dc0a734c67d33cb1cfe6f/extensions/sequelize/src/sequelize/sequelize.datasource.base.ts#L52

This is causing all the repository methods trying to use the “sequelizeModel” initialized here to be undefined: https://github.com/loopbackio/loopback-next/blob/e7f02ab659f0c9849c3dc0a734c67d33cb1cfe6f/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L87

### Logs

<img width="1594" alt="Screenshot 2023-06-07 at 6 29 28 PM" src="https://github.com/loopbackio/loopback-next/assets/5942028/7b64f8ee-71bd-4b21-8b6b-4da259609908">

### Additional information

As an experiment, I tried changing the lifecycle order groups to run the datasource init before everything else but it didn’t work: constructors injecting repositories would still run before the Sequelize property is initialized.

Delaying the injection for downstream repositories via Getters somewhat works but doing so adds a lot of boilerplate code.

### Reproduction

https://codesandbox.io/p/sandbox/great-surf-1ll97i?file=%2Fsrc%2Fobservers%2Fexample.observer.ts%3A1%2C1

**Comment by KalleV** [comment]
Moving the Sequelize instance creation into the SequelizeDataSource constructor instead of the “init” lifecycle hook seems to resolve the issue with no other changes required.

**Comment by shubhamp-sf** [comment]
The app won't start until the `init()` inside the datasource is done assigning the sequelize connection object based on the booting behaviour. Can you share a reproduction to what you're trying to do?

**Comment by KalleV** [comment]
Sure, I added a repro link on Codesandbox.
