### ISSUE TITLE
[@loopback/sequelize] Empty entity updates with MySQL datasource lead to Entity Not Found errors

### ISSUE THREAD

**Issue by KalleV** [loopbackio/loopback-next#9618]
### Describe the bug

Calling updateById on an existing entity without changing any properties leads to an Entity Not Found Error when using the Sequelize extension with MySQL. This doesn’t seem to occur with the Juggler ORM and MySQL connector.

References:
 - https://github.com/loopbackio/loopback-next/blob/f02c6d868a8c5b51edd56a9e37237ec5555f01b0/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L192
 - https://github.com/loopbackio/loopback-connector-mysql/blob/edf176b09234b82796f925203ff006843e045498/lib/mysql.js#L280

### Reproduction

N/A

**Comment by shubhamp-sf** [comment]
Interestingly this is not the case with postgres it returns the affectedRow count even if the patch data is same.
