### ISSUE TITLE
[@loopback/sequelize] Error context missing from Sequelize model error classes

### ISSUE THREAD

**Issue by KalleV** [loopbackio/loopback-next#9626]
### Describe the bug

When using the SequelizeCrudRepository as the base class, errors from Sequelize such as "SequelizeDatabaseError" or "UniqueConstraintError" are being replaced by a new default Error instance. This prevents downstream calls from using the Sequelize error classes for conditional logic such as:
```js
if (error instanceof SequelizeValidationError) {
  / * custom logic */
}
```

### Additional information

This seems to be caused by the default Error instances wrapping the custom Sequelize errors such as here: https://github.com/loopbackio/loopback-next/blob/28e8f0ab466c9cbafda2e5faaed5bd342f552d23/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L231

### Reproduction

N/A

**Comment by shubhamp-sf** [comment]
@KalleV Raised the fix PR linked above ^

Thanks for pointing it out.
