### ISSUE TITLE
[@loopback/sequelize] Attempting to query a relation that does not exist using the Loopback "include" filter leads to uncaught TypeError

### ISSUE THREAD

**Issue by KalleV** [loopbackio/loopback-next#9635]
### Describe the bug

This section of "includeReferencesIfRequested" is throwing a TypeError if the include filter references a relation that does not exist on the entity: https://github.com/loopbackio/loopback-next/blob/eec85bfa2847c0d1e9a80faf8d13c5f36b2ccbac/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L977-L978 

Error:
```
TypeError: Cannot read properties of undefined (reading 'type')
```

### Reproduction

N/A

**Comment by shubhamp-sf** [comment]
@KalleV Thanks for raising this.

Above mentioned PR solves it by throwing the `INVALID_INCLUSION_FILTER` error (similar to what we get without sequelize).
