### ISSUE TITLE
Recognizing Contributions BIG and small

### ISSUE THREAD

**Issue by virkt25** [loopbackio/loopback-next#981]
## Type
- [ ] Question
- [x] Suggestion
- [ ] Feature
- [ ] Bug / Issue

## Description / Steps to Reproduce / Suggestion

This is a follow up issue from https://github.com/strongloop/loopback-next/issues/943#issuecomment-363836167

I would like to propose that to get more community involvement we should follow the `all-contributors` standards ... basically means we recognize all contributions big and small (not just code PRs). This includes answering questions, design help, feature suggestions, bug reports, blogs, documentation, talks, tutorials, etc. etc. etc.

The contributors will be listed in a `CONTRIBUTORS.md` file at the top level of the repo. There is a tool that can help track GitHub contributions (and it provides a CLI interface for adding other contributors (blogs, talks, tutorials, etc.)). The tool formats the page so it looks good and makes it easy to update / maintain. 

### Reference Links
- [All Contributors Standard + Tool](https://github.com/kentcdodds/all-contributors)
- Carbon Components (Example Repo using above tool): https://github.com/carbon-design-system/carbon-components

**Comment by dhmlau** [comment]
From @bajtos: https://github.blog/changelog/2019-05-23-triage-and-maintain-roles-beta/. 
There are users/contributors who have done a pretty good job in answering others' issues.  We can use the new "Triage" role to recognize them.

**Comment by achrinza** [comment]
I realized that this issue was opened just before submitting a new issue, here's a snippet of it

---

Currently, the community contributions can only be viewed from [GitHub contributor graph](https://github.com/strongloop/loopback-next/graphs/contributors). This may be a bit too obscure, especially since it sorts by commit count by default.

## Suggestion



I think that utilizing the [@all-contributors bot](https://allcontributors.org/docs/en/bot/overview) will help increase visibility of community contributions:

![image](https://user-images.githubusercontent.com/25147899/75095160-38ee0100-55cd-11ea-87f1-6d3383bcac07.png)

Inside README:

![image](https://user-images.githubusercontent.com/25147899/75095153-2d023f00-55cd-11ea-8d28-e2b946f9f0d9.png)

## Use Cases



This will encourage community contributors by increasing visibility of their contributions in a high-visibility section (README).

**Comment by dhmlau** [comment]
+1
Does it show all the contributors (since the beginning of this repo)? If yes, it will be 100+. It might be good just to show the pictures? I saw it in some repos but forgot where it is. 

@strongloop/loopback-maintainers, WDYT?

**Comment by frbuceta** [comment]
> +1
> Does it show all the contributors (since the beginning of this repo)? If yes, it will be 100+. It might be good just to show the pictures? I saw it in some repos but forgot where it is.
> 
> @strongloop/loopback-maintainers, WDYT?

Something like this?
https://frbuceta.github.io/restify-jwt-community/#contributing
https://github.com/frbuceta/restify-jwt-community/blob/master/docs/index.md

**Comment by nabdelgadir** [comment]
> Something like this?
> https://frbuceta.github.io/restify-jwt-community/#contributing
> https://github.com/frbuceta/restify-jwt-community/blob/master/docs/index.md

I like the first one https://frbuceta.github.io/restify-jwt-community/#contributing, although since there are 100+ contributors, would it be too cluttered?

**Comment by achrinza** [comment]
I've created draft PR #4756 to show how it'd look like on this repo's README

**Comment by dougal83** [comment]
> I like the first one https://frbuceta.github.io/restify-jwt-community/#contributing, although since there are 100+ contributors, would it be too cluttered?

+1 to preference for first example.  I think this is one situation that looking cluttered and busy might be a good thing; demonstrating the volume of people deciding to get involved.

**Comment by dhmlau** [comment]
> Something like this?
> https://frbuceta.github.io/restify-jwt-community/#contributing
> https://github.com/frbuceta/restify-jwt-community/blob/master/docs/index.md

Maybe it's just me. It shows broken images for me on the 2nd link. 

@dougal83, any reason you don't want bot? I think it would be ideal to have bot to update the contributors for us, because it's hard to keep track manually.

**Comment by frbuceta** [comment]
Interesting, the truth is that it has never occurred to me to delete the bots

**Comment by dougal83** [comment]
> @dougal83, any reason you don't want bot? I think it would be ideal to have bot to update the contributors for us, because it's hard to keep track manually.

@dougal83 A bot to update the list is fine.  I'm just anti bot when it comes to their inclusion on a contribution list. 😄 Just a nice to have... I see bots as noise in this context.
