### ISSUE TITLE
OpenAPI 3 feature: Support parameter location "in: cookie"

### ISSUE THREAD

**Issue by jannyHou** [loopbackio/loopback-next#997]
### Description 

Original discussion see: https://github.com/strongloop/loopback-next/pull/916#discussion_r168457983

>Cookie support is not so straightforward. It's a recommended practice to encrypt cookie values using a server-configured secret. We will need a way how to tell @loopback/rest what is this secret, otherwise it won't be able to decode cookie values.

Current workaround: 
> Throw a helpful error here, explain that cookie parameters are not supported yet and point people to the GH issue tracking this feature.

OpenAPI official reference: https://swagger.io/docs/specification/describing-parameters/#cookie-parameters

**Comment by achrinza** [comment]
It's been a while since this issue was visited;

@bajtos - is there any reason we need lb4 to transparently handle encrypting the cookies? IMO this reduces flexibility and interoperability and should be handled by the controller and be up to the user to encrypt.
